aws/aws-sdk-php

src/ClientFactory/ClientFactory.php
src/ClientFactory/CloudSearchDomain.php
src/ClientFactory/DynamoDb.php
src/ClientFactory/Glacier.php
src/ClientFactory/Route53.php
src/ClientFactory/S3.php
src/ClientFactory/Sqs.php
src/ClientFactory/Sts.php
src/Sdk.php
tests/Api/Serializer/ComplianceTest.php
tests/ClientFactory/ClientFactoryTest.php
tests/ClientFactory/CloudSearchDomainTest.php
tests/ClientFactory/DynamoDbTest.php
tests/ClientFactory/GlacierTest.php
tests/ClientFactory/Route53Test.php
tests/ClientFactory/S3Test.php
tests/ClientFactory/SqsFactoryTest.php
tests/StsClientTest.php

1. Allows us to see which clients have custom factories.
2. More consistent with how exceptions are now namespaced.

Moving client factories to a single directory

---

src/Aws/Common/Client/AbstractClient.php
src/Aws/Common/Signature/SignatureListener.php
tests/Aws/Tests/Common/Client/AbstractClientTest.php
tests/Aws/Tests/Common/Signature/SignatureListenerTest.php

Creating a new S3Client using NullCredentials, then setting legitimate credentials later on causes Authorization errors.  This is because the SignatureListener is only added when the client is created with NullCredentials, meaning the listener cannot respond to the client.credentials_changed event.  This pull request changes things so the listener is always added, and moves the check for NullCredentials into the SignatureListener plugin.

Always add SignatureListener, even on NullCredential requests

---

src/S3/StreamWrapper.php
tests/S3/StreamWrapperTest.php

This PR adds an LRU cache to the S3 stream wrapper so that listing files in S3 buckets is cached for subsequent is_file, is_dir, stat, etc. calls. When the cache size exceeds 1000 entries, the cache is halved by removing the least recently used items from the cache.
I thought that I could leverage PHP's built-in clearstatcache() related functionality, but unfortunately it doesn't seem you can seed the internal stat cache from within a function calls that was triggered from a custom stream wrapper function.

Adding an LRU cache to the stream wrapper

---

src/ClientFactory.php
src/S3/S3Factory.php
src/Signature/Provider.php
tests/ClientFactoryTest.php
tests/S3/S3FactoryTest.php
tests/Signature/ProviderTest.php
tests/WaiterTest.php

This PR adds a signature provider that can be used to create signature objects by name. This is now utilized in the ClientFactory, and could be utilized by customers to create custom signature objects to, for example, create a presigned URL.

Adding a signature provider

---

src/S3/Transfer.php
src/Utils.php
tests/S3/TransferTest.php
tests/UtilsTest.php

This commit adds a Utils class where we can place useful and generic
functionality (e.g., a directory iterator that doesn't call readdir()
and rewinddir() when constructed).
This commit also updates the recursive directory iterator to not require
each level of directory traversal be cached in memory.

Adding a Utils class and using less dir buffering

---

build/option-docs.php
src/ClientFactory.php
src/S3/S3Factory.php
src/Sdk.php
tests/ClientFactoryTest.php

Added a new static method for client factories that allows you to get a
hash of valid arguments. This result can be used to generate
documentation, and I've added a build script for generating the Sdk
class docblock that describes client factory arguments.
You can now provide a "doc" string for each argument.
You can now provide a "valid" key for an argument to describe the valid
types or class names. These will then be automatically validated when
handling client factory options.
The class_name argument now must be a full class name.
Added the exception_class argument.
Removed the no longer needed per-argument validation.

Added more functionality to client factory options

---

docs/configuration.rst
docs/service-cloudsearchdomain.rst
src/Aws/CloudSearch/CloudSearchClient.php
src/Aws/CloudSearchDomain/CloudSearchDomainClient.php
src/Aws/CloudSearchDomain/CloudSearchDomainClientBuilder.php
src/Aws/Common/Client/ClientBuilder.php
src/Aws/Common/Client/DefaultClient.php

This now shows "endpoint" only in the docs, but "base_url" will continue to be supported.

Add support for "endpoint" for forward compat w/ v3

---

src/S3/BucketStyleSubscriber.php
src/S3/S3Factory.php
tests/S3/BucketStyleSubscriberTest.php
tests/S3/S3FactoryTest.php

If you provide "bucket_endpoint" => true when creating an S3Client, then
requests are sent to a bucket-specific endpoint, allowing users to send
requests and create pre-signed URLs for CNAME style buckets, local S3
mocks.

Adding bucket endpoint functionality.

---

src/Ec2/CopySnapshotSubscriber.php
src/Ec2/Ec2Factory.php
tests/Ec2/CopySnapshotSubscriberTest.php
tests/Ec2/Ec2FactoryTest.php

I decided to pass in a serializer and endpoint provider into the subscriber rather than have the subscriber create a new client with a different endpoint and signer (like we did with v2).

Add pre-signed URLs for CopySnapshot

---

composer.json
src/Api/Service.php
src/AwsClient.php
src/AwsClientInterface.php
src/ClientFactory.php
src/Ec2/CopySnapshotSubscriber.php
src/Ec2/Ec2Factory.php
src/S3/S3Client.php
src/S3/S3Factory.php
src/S3/UploadBuilder.php
src/Signature/AnonymousSignature.php
src/Signature/Provider.php
tests/AwsClientTest.php
tests/ClientFactoryTest.php
tests/Ec2/CopySnapshotSubscriberTest.php
tests/S3/ApplyMd5SubscriberTest.php
tests/S3/S3FactoryTest.php
tests/S3/UploadBuilderTest.php
tests/Signature/AnonymousSignatureTest.php
tests/Signature/ProviderTest.php
tests/UsesServiceTrait.php

This commit updates clients to no longer provide a getSignature()
method, but rather utilizes an internal signature provider, that
provided a version, service, and region returns a SignatureInterface
object used to sign requests. This allows customers to inject custom
signature providers, allows customers to provide a signature version
override to use when signing requests (e.g., for S3, use v4 instead),
and allows clients to vary the signature version on a per/operation
basis (e.g., this is already a possibility as some operations are not
signed while others are signed).
This commit also updates the SDK to use a few recent Guzzle Command
changes: client options are now immutable, so some of the setOption
calls have been refactored to use a new "config" client factory
option type, which …

Adding signature providers.

---

docs/configuration.rst
docs/requirements.rst
src/ClientResolver.php
src/Sdk.php
tests/ClientResolverTest.php
tests/WaiterTest.php

This PR allows the `client` option to be a callable that returns a Client instance. This removes the ringphp_handler argument which helps to better decouple the SDK from a Guzzle implementation detail.

Removing ringphp_handler option in favor of allowing a callable client option

---

src/AwsClient.php
src/Waiter.php
tests/Integ/WaiterTest.php
tests/UsesServiceTrait.php
tests/WaiterTest.php

Here's the waiter's coroutine implementation. Unit and integ tests (at least for the waiters themselves) are passing with 100% coverage. I wanted to get this up here so you can see it.
```php
$client->waitUntil('TableExists', ['TableName' => 'Foo']);
```
```php
$promise = $client->waitUntil('TableExists', [
'TableName' => 'Foo',
'@future' => true
]);
```

Reimplemented waiters using promise coroutines.

---

src/Api/ErrorParser/XmlErrorParser.php
src/Api/Parser/Crc32ValidatingParser.php
src/AwsClient.php
src/ClientResolver.php
src/DynamoDb/DynamoDbClient.php
src/Middleware.php
src/RetryMiddleware.php
src/S3/S3Client.php
tests/Api/ErrorParser/XmlErrorParserTest.php
tests/DynamoDb/DynamoDbClientTest.php
tests/MiddlewareTest.php
tests/RetryMiddlewareTest.php
tests/S3/S3ClientTest.php

- Removed retry_logger option. This can be done using a custom
middleware if needed.
- Updating the XML error parser to set the error code to "NotFound" when
there is no body and the status code is 404. Removed custom S3 error
parsing for bucket vs object not found.
- Updated DynamoDB to uses a response parser that ensures the response
x-amz-crc32 header is valid.

Adding retries

---

src/AwsClient.php
src/ClientResolver.php
src/DynamoDb/DynamoDbClient.php
src/Ec2/Ec2Client.php
src/HandlerList.php
src/Route53/Route53Client.php
src/S3/ApplyMd5Middleware.php
src/S3/S3Client.php
src/S3/SSECMiddleware.php
src/Sqs/SqsClient.php
tests/CommandTest.php
tests/DynamoDb/StandardSessionConnectionTest.php
tests/DynamoDb/WriteRequestBatchTest.php
tests/HandlerListTest.php
tests/MiddlewareTest.php
tests/Sqs/SqsClientTest.php

This commit updates the handler list to remove the "sticky" attribute
and instead now has a "name" that can be associated with a middleware by
providing a ":name" after a step (e.g., "init:name"). A step is now
required when calling append and prepend, and you can optionally provide
a name for any middleware. Providing a name allows you to add middleware
before or after another middleware by name or remove a middleware by
name.
In addition to naming middleware, this commit adds more introspection
into the HandlerList: you can now print the list for debugging purposes
and you can provide an interpose function (a function that is triggered
before each middleware is invoked). Interposing is useful for things
like debugging and tracing through a middleware invocation.

Updating handler list to allow names.

---

src/AwsClient.php
src/ClientResolver.php
src/TraceMiddleware.php
tests/ClientResolverTest.php
tests/TraceMiddlewareTest.php

This change outputs state changes between middlewares. For example, here's the output from encountering an error:
```
-> Entering step init, name 'validation'
----------------------------------------
command was set to array (
'instance' => '00000000476c214f000000016d19c25b',
'name' => 'PutItem',
'params' => 
array (
'TableName' => 'foo',
'Item' => 
array (
'bar' => 
array (
'S' => 'baz',
),
),
'@http' => 
array (
'headers' => 
array (
'User-Agent' => 'aws-sdk-php/3.0.0-beta.1',
),
'debug' => NULL,
),
),
)
request was set to array (
)
-> Entering step build, name 'builder'
--------------------------------------
command.params.@http.debug changed from NULL to NULL
request.instance was set to 00000000476c2178000000016d19c25b
request.method was set to POST
request.headers was set to array ( …
```

Adding the ability to trace through state changes between middlewares

---

tests/bootstrap.php

When running individual tests in PHPStorm, the cwd is set to the path of the file you are testing. This fixes not being able to resolve `test_services.dist.json`.

Fix assuming tests are run from the project root.

---

src/Aws/Common/Signature/SignatureV4.php

If presigned url created for PutObject using V4 Signature ( e.g. V4 is required for eu-central-1 region ), url not working because presigned url created with 'GET' mehtod name.

Method name fix for creating PresignedUrl

---

src/Aws/S3/Exception/NoSuchTagSetException.php

This exception was never thrown because of the wrong name.

Fix S3 NoSuchTagSetException

---

src/CacheInterface.php
src/LruArrayCache.php
src/S3/StreamWrapper.php
tests/LruArrayCacheTest.php
tests/S3/StreamWrapperTest.php

- You can now inject a cache into the stream wrapper in a contect or in
the default context options.
- Added a CacheInterface for simple get/set/remove caching.
- Added a single cache implementation LruArrayCache that implements an
LRU cache using PHP's ordered associative arrays.
- Added support for creating a stream wrapper using a custom protocol.
Closes #531. Closes #536.
Example:
```php
<?php
require 'vendor/autoload.php';
$s3 = new Aws\S3\S3Client([
'region'  => 'us-east-1',
'version' => 'latest',
// use debug to ensure that no requests are sent.
'debug'   => true
]);
// Create an LRU cache
$cache = new \Aws\LruArrayCache();
// Create a dummy return value.
$cache->set('s3://t1234/test', ['size' => 123, 7 => 123]);
// Register the stream wrapper with the cache and a protocol name. …
```

Added support for injectable cache to stream wrapper.

---

src/Aws/Route53/Resources/route53-2013-04-01.php

Use the correct element name when extracting CIDRs from a GetCheckerIpRangesResponse.

Return results for GetCheckerIpRanges

---

docs/guide/waiters.rst
src/AwsClient.php
src/AwsClientInterface.php
src/Waiter.php
tests/ResultPaginatorTest.php
tests/WaiterTest.php

- Adding waiter documentation.
- Waiters are now fulfilled with the command that last succeeded. This
provides a relatively useful indicator of which waiter succeeded when
working with multiple promises and pairs well with the addition of the
before argument.
- Waiters now accept a "before" callback that takes the command about
the be executed and the number of attempts.
- Removed the "retry" callback from waiters.
- Custom waiter configs are now injected in the `@waiter` key value pair
of the `$args` parameter for `getWaiter()` and `waitUntil()`.
- Removed the `$config` array from paginators as this does not have a
valid use case.

Updating waiters (and docs) and paginators.

---

src/Api/Serializer/QueryParamBuilder.php

As via gitter.im - I had a problem with `ElasticBeanstalk::describeEnvironments` when passing through `IncludeDeleted => false` as param.
Currently it would typecast it into a string, which PHP will just make a empty string out of it. With this path it will check if value is a boolean and replace it with actual 'true' or 'false' strings.

Fix bool typecasting of request param values

---

src/Ec2/CopySnapshotMiddleware.php
src/S3/S3Client.php
src/Signature/AnonymousSignature.php
src/Signature/S3Signature.php
src/Signature/SignatureInterface.php
src/Signature/SignatureV2.php
src/Signature/SignatureV4.php
tests/S3/S3ClientTest.php
tests/Signature/AnonymousSignatureTest.php
tests/Signature/S3SignatureTest.php
tests/Signature/S3SignatureV4Test.php
tests/Signature/SignatureV2Test.php
tests/Signature/SignatureV4Test.php

Updated the SignatureInterface to change createPresignedUrl to presign. Changed S3's createPresignedUrl to createPresignedRequest.
Consumers can get the presigned URL (and other information like headers) from the presigned request object. Formerly, only the URLs were returned, and getting the header values needed to actually make requests to the presigned URLs was not possible with custom middleware.

[v3] Signature::presign and S3Client::getPresignedRequest

---

src/Aws/Ec2/CopySnapshotListener.php
tests/Aws/Tests/Ec2/CopySnapshotListenerTest.php

Fixes a bug in the EC2 CopySnapshotListener so it works with temporary credentials.

Temporary credentials with cross-region CopySnapshot

---

src/AwsClient.php
src/ClientResolver.php
src/DynamoDb/DynamoDbClient.php
src/Ec2/Ec2Client.php
src/Glacier/GlacierClient.php
src/HandlerList.php
src/Multipart/AbstractUploader.php
src/Route53/Route53Client.php
src/S3/S3Client.php
src/Sqs/SqsClient.php
tests/DynamoDb/StandardSessionConnectionTest.php
tests/DynamoDb/WriteRequestBatchTest.php
tests/HandlerListTest.php
tests/MiddlewareTest.php
tests/S3/ApplyMd5MiddlewareTest.php
tests/S3/BucketStyleMiddlewareTest.php
tests/S3/SSECMiddlewareTest.php
tests/S3/StreamWrapperTest.php
tests/S3/TransferTest.php
tests/Sqs/SqsClientTest.php
tests/TraceMiddlewareTest.php

This commit updates the HandlerList to include the step name as part of
adding a middleware to a handler. This adds methods for each step
prefixed with "append" or "prepend". I believe this to be a better API
as it does not require string parsing (e.g., "init:foo") and makes the
steps explicit and auto-completable.

Making the step name part of the method for HandlerList

---

build/docs/classes/ExampleBuilder.php
src/Api/DateTimeResult.php
src/Api/Parser/AbstractRestParser.php
src/Api/Parser/JsonParser.php
src/Api/Parser/XmlParser.php
tests/Api/DateTimeResultTest.php
tests/Api/Parser/ComplianceTest.php

This change updates the SDK to parse timestamp shapes into custom DateTimeResult objects. These objects extend DateTime and implement `__toString` and `JsonSerializable`. This allows the object to work with JMESPath as well.
This is a good change because it normalizes the timestamp result type across different protocols but still allows users to work with it as if it is an ISO 8601 date string.

Now converting timestamps to DateTimeResult objects

---

README.md

URL did not support HTTPS, and resulted in a connection refused error.
Purely a documentation change

Fixed url scheme for guzzle related projects link

---

composer.json

This commit updates the SDK to use older composer.json syntax to support older builds of composer. This converts `^` usage to `~` and `||` usage to `|`. I'm not sure if `|` is exactly equivalent to `||`, but it seems to be based on testing it locally.
/cc @GrahamCampbell

Using older composer version syntax to support older builds of composer

---

src/MachineLearning/MachineLearningClient.php
tests/MachineLearning/MachineLearningClientTest.php

Fixing the Machine Learning client to use the provided PredictEndpoint as the host for the Predict operation.

Fixing MachineLearningClient to use PredictEndpoint

---

src/Exception/CouldNotCreateChecksumException.php
src/S3/StreamWrapper.php
src/Signature/SignatureV4.php
src/TraceMiddleware.php
tests/Signature/SignatureV4Test.php
tests/TraceMiddlewareTest.php

This commit makes a few enhancements to the SDK based on #604:
1. Context parameters like cache and client are now removed from the
parameters that are sent when executing commands in the S3 stream
wrapper. When these parameters were present, they resulted in
lengthy debug messages with the TraceMiddleware, and even caused
stream resources to enter an invalid state after dumping them.
2. Updated TraceMiddleware to better provide debug information about
exceptions. These debug messages previously var_dump'd the exception,
causing a massive dump to the debug output. This is now handled by
extracting specific pieces of information from exceptions and
formatting in a more readable way.
3. Added a try/catch to the signature version 4 signer such that if a
stream claims it's readable, but …

Various enhancements related to #604

---

src/Api/Serializer/JsonBody.php
tests/Api/test_cases/protocols/input/json.json

Added a check to the json serializers to ensure empty maps get serialized to {} instead of []

Handle empty maps in JSON serializer

---

.travis.yml
Makefile
build/test-phar.php
src/JsonCompiler.php
tests/JsonCompilerTest.php

Closes #610.
This commit updates the JsonCompiler class to normalize paths to always
use "/" instead of using DIRECTORY_SEPARATOR. This works for all SDK
usage because the SDK uses relative paths for everything, and any
absolute paths that would have been mangled through this transformation
(e.g., 'C:/path/to/sdk/foo/bar.json.php') are modified to remove the base
directory of the SDK from the path (e.g., 'foo/bar.json.php' ->
'foo_bar.json.php).
This commit also removes a duplicate call to normalizePath().
Phar testing has been updated to include loading a paginator.
Phars are now built and tests on every Travis build.

Always using Unix style paths for Windows compat.

---

src/Signature/S3SignatureV4.php
src/Signature/SignatureV4.php
tests/Integ/SignatutePathEncodingTest.php
tests/Signature/SignatureV4Test.php

Related to forum post: https://forums.aws.amazon.com/thread.jspa?threadID=182601
CR PLZ: @mtdowling @jeskew

Fixing an issue with path encoding in SigV4 that affects Cognito

---

src/Api/ApiProvider.php
src/AwsClient.php
src/Sdk.php
src/functions.php
tests/SdkTest.php

This PR:
- Centralizes the relationship between endpoint prefixes and namespaces, without the need to manually maintain the list in the SDK code.
- Makes it easier for users to create a client from the `Aws\Sdk`, because you don't need to know the casing, and specifying either the service's namespace or endpoint prefix will work.
- Reuses the existing manifest file.
- Fixes #635 a different way.
/cc @mtdowling @jeskew

Use manifest file to resolve service names when creating clients

---

src/Aws/Common/Command/AwsQueryVisitor.php
tests/Aws/Tests/Common/Command/AwsQueryVisitorTest.php

Fixes how empty lists are serialized in some cases.
/cc @mtdowling

Fixes #479. Affects serialization for specific ELB and CFN operations.

---

src/S3/StreamWrapper.php
tests/S3/StreamWrapperTest.php

This pull request allows the stream wrapper to use a custom protocol. This is achieved by parsing the protocol out of the path each time the stream wrapper is invoked for a creational type of method.
Closes #639
@jeremeamia @jeskew

Allow custom stream wrapper protocol

---

src/DynamoDb/SessionHandler.php

Otherwise fromClient() does not work correctly from objects that extend Aws\DynamoDb\SessionHandler
This change should not effect existing functionality of those who call fromClient() directly on Aws\DynamoDb\SessionHandler.

Use late static binding for self instantiating the DynamoDb SessionHandler

---

src/Aws/Common/Credentials/CacheableCredentials.php
src/Aws/Common/Credentials/Credentials.php
tests/Aws/Tests/Common/Credentials/CredentialsTest.php

If a `credentials.cache` option is passed into the `Credentials::factory` method, that cache should be checked for an instance of `CredentialsInterface` before attempting to build one from the environment. Since `CredentialsInterface` extends `Serializable`, we can rely on implementations to properly restore themselves when retrieved from cache.
/cc @mtdowling @jeremeamia

Check the provided cache before attempting to build credentials

---

src/S3/StreamWrapper.php
tests/S3/StreamWrapperTest.php

enforced by PHP to match.
Issue #693

bugfix(S3/StreamWrapper) Init protocol from passed path. Protocols are

---

src/S3/MultipartUploader.php
tests/Integ/S3MultipartTest.php

The integration test on multipart uploads of nonseekable streams was failing. Switching the checksum encoding from base64 to hex fixes that.

Use hex instead of base64 output for S3 SigV4 checksum

---

src/S3/S3Client.php

The implicit `$this` binding on the functions affected by this patch was leaving a circular reference and preventing some memory allocated to instances of `Aws\S3\S3Client` from being freed.

Unbind middleware closures from $this

---

src/Credentials/CredentialProvider.php

Enclosing over a pending call `$provider` seems to prevent variables accessible to the promise (but not the value with which it is fulfilled) from being eligible for garbage collection. In the case of `Aws\CredentialProvider::defaultProvider`, this included an instance of `Aws\HandlerList`, an instance of `Aws\Api\ShapeMap`, and all of their member properties.

Defer inspection of memoized credential provider

---

src/JsonCompiler.php

If two or more processes execute the code, the 1st may create the
directory after the is_dir call, while the 2nd will fail with "mkdir():
File exists". Suppressing the error while adding a 2nd is_dir call is
necessary.

Suppress error from mkdir

---

src/S3/Transfer.php

Resolve an issue where S3 Transfer was attempting to upload objects with an empty key when uploading to the root of an S3 bucket.
Also ensures that there is no `//` between prefix and path, to avoid uploading objects one level deeper than expected inside a directory with empty name.
This does appear to resolve the issue reported in #653 but I am unsure whether it has other implications.

Calculate correct S3 Transfer key with or without prefix (fixes #653)

---

.travis.yml
src/Aws/S3/StreamWrapper.php
tests/Aws/Tests/S3/StreamWrapperTest.php

Currently the S3 StreamWrapper will trigger an error and return true when opening an invalid `s3://` path for reading. This PR ensures that calling `fopen` will return false on failure, which will prevent `file_get_contents` from returning an empty string (as mentioned on #609).
e4f078a is unrelated but it's the only way to get Travis to actually finish a build.

Ensure that fopen calls return false when errors are encountered

---

.travis.yml

PHP 7 has moved from alpha to beta, and our test suite is currently green on Travis.

Make PHP 7 failures fail the build

---

src/Aws/Common/Credentials/RefreshableInstanceProfileCredentials.php
src/Aws/Common/InstanceMetadata/InstanceMetadataClient.php
tests/Aws/Tests/Common/Credentials/RefreshableInstanceProfileCredentialsTest.php

This class was serializing with just the credentials it had at the time `serialize` was called, so any attempt to subsequently refresh the credentials would have `null` where it was expecting an instance of `Aws\Common\InstanceMetadata\InstanceMetadataClient`. Would address #710.

Ensure that an unserialized RefreshableInstanceProfileCredentials object is still useful

---

src/ClientResolver.php
tests/ClientResolverTest.php
tests/CloudSearchDomain/CloudSearchDomainTest.php

Currently, it's very easy to copy a value from the CloudSearchDomain console and be greeted with an opaque error message ('cURL error 3'). As described in #722, this is what happens when you supply a custom `endpoint` to a client that cURL will not be able to use directly. This PR adds a validation function to the ClientResolver that ensures endpoints have a scheme and host.

Ensure that custom endpoints have a defined scheme and host

---

src/S3/S3Client.php
tests/S3/S3ClientTest.php

It seems that S3 connection errors were not being retried due to a function signature mismatch.

Ensure that connect errors on S3 are retried as configured

---

build/Burgomaster.php
build/packager.php

Another attempt to resolve #563. Other projects that distribute a phar (including Composer, PHPUnit, and Behat) include a call to Phar::mapPhar($filename)) in their phar stubs, and its absence could explain why aws-autoloader.php cannot be found when aws.phar is loaded from opcache instead of from the filesystem.
/cc @mtdowling

Map phar in stub file and set a versioned alias

---

build/packager.php
composer.json

Breaking out the SNS validator was great for users who are comfortable with composer and don't need the rest of the SDK. This makes sure the functionality is still present for phar users who are upgrading from v2 to v3.

Add SNS message validator to the distributables 

---

composer.json
docs/guide/configuration.rst
src/ClientResolver.php
src/Credentials/CredentialProvider.php
src/Credentials/Credentials.php
src/DoctrineCacheAdapter.php
tests/ClientResolverTest.php
tests/Credentials/CredentialProviderTest.php
tests/DoctrineCacheAdapterTest.php

This PR allows users to pass an instance of `Aws\CacheInterface` as the `credentials` in their client configuration. The default provider chain will still be used, but the cache will hold on to credentials returned by the Ec2 instance metadata service.
Additionally, this PR includes an adapter for instances of `Doctrine\Common\Cache\Cache`, as the only bundled implementation of `Aws\CacheInterface` is an in-memory cache.

Add a mechanism for caching InstanceProfile credentials

---

src/S3/BatchDelete.php
tests/S3/BatchDeleteTest.php

When trying to run batch delete and there are no object with given prefix PHP Warning is thrown.
When running following code and there are no object with `path/to` key prefix.
```
$d = Aws\S3\BatchDelete::fromListObjects($this->s3, ['Bucket' => 'bucket', 'Prefix' => "path/to/"]);
$d->delete();
```
```
Warning: Invalid argument supplied for foreach() in /path/to/app/vendor/aws/aws-sdk-php/src/S3/BatchDelete.php on line 73
```

Fix warning when doing batch delete and there are no object in S3 bucket

---

src/AwsClient.php

Allow `getIterator()` calls to non-paginated APIs, such as
```php
$ec2->getIterator('DescribeSubnets');
```
to continue to work as they did in v2 instead of failing with
```
Call to undefined method Aws\Command::search()
```

Allow getIterator() to continue to work without a *_token

---

src/Credentials/CredentialProvider.php
tests/ClientResolverTest.php
tests/Credentials/CredentialProviderTest.php

This change allows the documented field to be used for session token as stated in my [issue](https://github.com/aws/aws-sdk-php/issues/773) here.

Should respect documented fields in credentials file

---

features/smoke/cloudfront/cloudfront.feature
tests/Integ/IntegUtils.php
tests/Integ/SmokeContext.php

Rather than specifying the credentials profile in `Aws\Test\Integ\IntegUtils`, the integration test runner should just use the default credential provider. Profiles can be specified by setting the `AWS_PROFILE` environment variable.
Additionally, the CloudFront integration test no longer relies on accounts being in a particular state, as that will allow more flexibility with which accounts may execute tests.
/cc @mtdowling

Allow cucumber tests to run with Ec2 instance profile credentials

---

src/CloudFront/UrlSigner.php

When using the CloudFront component for url signing, if a url contains non RFC compliant characters, the url passed to the canned policy creation will not match the actual url generated by the GuzzleHttp\Psr7\Uri component, resulting in the generation of an invalid signed url. This pr simply passes the correct url, which may have characters encoded in some use cases, to the createCannedPolicy method.

Pass the same uri object url to the canned policy creation

---

src/S3/S3Client.php
tests/S3/S3ClientTest.php

This PR allows custom location constraints to be supplied.

Respect client-supplied location constraints on createBucket commands

---

docs/service/s3-multipart-upload.rst
src/S3/MultipartCopy.php
src/S3/S3Client.php
tests/S3/S3ClientTest.php
tests/UsesServiceTrait.php

This PR adds `uploadAsync` and `copyAsync` methods to `Aws\S3\S3Client`, both of which return promises that will be fulfilled with the result of the underlying operation. `upload` and `copy` now simply call `uploadAsync` and `copyAsync` respectively and wait on the returned promise.
/cc @mtdowling

Add async counterparts to S3Client::upload and S3Client::copy

---

src/DynamoDb/SessionHandler.php
tests/DynamoDb/SessionHandlerTest.php

Rather than have the session handler keep track of the current session id, this PR punts that responsibility to the runtime. `session_id` is therefore called in the `close` handler instead of the `open` handler, as some users had reported that certain runtimes would not return a valid session ID when `session_id` was called before `session_start` had completed.
/cc @chrisradek @mtdowling

Let the RT keep track of session IDs

---

src/DynamoDb/DynamoDbClient.php
src/RetryMiddleware.php
tests/RetryMiddlewareTest.php

This PR converts the delay value provided from the SDK to Guzzle from seconds to milliseconds. Guzzle is expecting MS, so the previous behavior was to delay for trivial amounts of time (as reported in #815). Since I was already mucking about in the backoff code, I threw in some randomness.
One thing I'm not clear on is if the delay times are correct. [The DynamoDB docs advise delaying  (50 * (int) pow(2, $retries - 1)) between retries](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ErrorHandling.html), whereas the standard AWS guideline is to [wait pow(2, $retries - 1) * 100 milliseconds](http://docs.aws.amazon.com/general/latest/gr/api-retries.html). When adding jitter, should I aim to make those values match the maximum possible retry delay (which is what I've done …

Backoff in MS (not seconds) and throw in some jitter

---

src/DynamoDb/StandardSessionConnection.php
tests/DynamoDb/StandardSessionConnectionTest.php

This PR converts exceptions thrown within the DynamoDB session handler into warning-level errors. The current behavior of the handler (returning false on failure) is not changed, but errors will become more visible (as requested in #585).

Trigger errors when the session handler fails to write or delete data

---

src/CognitoIdentity/CognitoIdentityProvider.php
src/Sts/StsClient.php
tests/CognitoIdentity/CognitoIdentityProviderTest.php
tests/Sts/StsClientTest.php

The added provider uses a Cognito Identity's anonymous APIs to create credentials. It also moves the `createCredentials` method from `Aws\Sts\StsClient` into a trait.

Add a CognitoIdentity credential provider

---

src/Api/ErrorParser/JsonParserTrait.php
src/Api/ErrorParser/XmlErrorParser.php
src/WrappedHttpHandler.php
tests/WrappedHttpHandlerTest.php

Should help with the visibility of errors when responses do not necessarily follow the expected error format (e.g., #823).

Allow the error handler to recover from error parser errors

---

src/Aws/DynamoDb/Session/SessionHandler.php
tests/Aws/Tests/DynamoDb/Session/SessionHandlerTest.php

This PR removes three protected members from the DynamoDb `SessionHandler`: `$dataRead`, `$openSessionId`, and `$sessionWritten`. In their place, the session handler uses `session_id` to get the open session ID and will look up session data and whether a session was written dynamically based on the current session ID in arrays at `$sessionDataRead` and `$sessionsWritten`. 
Since PHP does not allow `__get` methods to be declared `protected`, this PR has a side effect of making the `->dataRead` and `->sessionWritten` members publicly readable, but this information could always have been accessed from anywhere in the process using PHP's `session_*` functions.
The motivation for this PR is that the session handler as it is written is unable to detect when `session_regenerate_id` is called, as …

Take account of the fact that session IDs can and should change.

---

src/Ses/SesClient.php
tests/Ses/SesClientTest.php

Based on [this section of the SES docs](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html#smtp-credentials-convert).

Add a helper function to generate SMTP password from credentials

---

src/S3/S3Client.php
tests/S3/S3ClientTest.php

This PR makes a code path in the S3 retry handler more specific by only checking error-level responses for the string "Your socket connection to the server..." The branching logic was also catching 200-level responses with reset connections, meaning that they weren't retried.

Ensure errors with unparseable responses are retried when idempotent

---

src/Route53/Route53Client.php
tests/Route53/RouteClient53Test.php

The fix 1b4688c4ba19ef8431e8ba96c8ebbe573fe83d43 seems incomplete:
It works for `GetReusableDelegationSet` request, where the parameter's name is `Id`
But does not work for `CreateHostedZone` request, where the parameter is `DelegationSetId`
That is the reason I've workarounded here: https://github.com/plesk/ext-route53/blob/master/plib/library/Client.php#L158

Clean DelegationSetId in Route53Client

---

composer.json
src/S3/Transfer.php
tests/S3/TransferTest.php

Iterators must yield absolute paths and must be paired with a `base_dir` option. We document that using iterators with the transfer manager is possible, but they are currently not supported.

Add support for supplying source iterators to the transfer manager

---

src/Api/Parser/AbstractRestParser.php
tests/Api/test_cases/protocols/input/rest-json.json
tests/Api/test_cases/protocols/input/rest-xml.json
tests/Api/test_cases/protocols/output/query.json
tests/Api/test_cases/protocols/output/rest-json.json

This PR prevents the SDK from attempting to parse the payload of responses for which no output shape has been defined. This will address an error described in [the AWS forums](https://forums.aws.amazon.com/thread.jspa?threadID=223125), which was caused by an endpoint w/o any defined response shape returning the string `OK`.
/cc @mtdowling @xibz

Skip undefined output shapes

---

tests/Aws/Tests/Common/Credentials/CacheableCredentialsTest.php

The test was checking for the existence of something in a cache, but the item must have an expiration in the future for Doctrine 1.6 to report that it contains that key. Our 2.8 build is failing because of this.
/cc @mtdowling @chrisradek @xibz

Update credentials cache to check for updated Doctrine behavior

---

composer.json
src/PsrCacheAdapter.php
tests/PsrCacheAdapterTest.php

The added class allows users to create an instance of `Aws\CacheInterface` from an instance of `Psr\Cache\CacheItemPoolInterface`.

Add a cache adapter for the psr-6 interface

---

src/DynamoDb/WriteRequestBatch.php
tests/DynamoDb/WriteRequestBatchTest.php

This PR ensures that when unprocessed items are requeued from the response to a BatchWriteItem operation in a WriteRequestBatch flush, they keep their PutRequest/DeleteRequest identifier.
/cc @mtdowling @xibz

Correctly requeue throttled WriteRequestBatch items

---

src/AwsClient.php
tests/AwsClientTest.php

Clients are not serializable, but the error message produced when attempting to serialize isn't particularly helpful. It's usually `Serialization of 'Closure' is not allowed` or something similar. This PR would short-circuit that attempt and immediately throw a RuntimeException. SDK consumers who need to serialize a client should implement and use a serialization proxy. This resolves #891.
/cc @mtdowling @chrisradek @xibz

Throw an exception when attempting to serialize an AwsClient

---

docs/guide/configuration.rst
src/Api/Validator.php
src/ClientResolver.php
src/Middleware.php
tests/Api/ValidatorTest.php
tests/ClientResolverTest.php

This commit updates the SDK to allow customers to configure exactly what
they want to validate client side. I've added the ability to provide
validation constraints as feature flags to a Validator and to the
validate client option. This commit also updates the SDK to no longer
validate "max" by default.
@jeskew

Updating validation to be more flexible

---

.gitattributes
build/Burgomaster.php
build/packager.php
composer.json

This PR updates Burgomaster's recursiveCopy method to take an optional iterator of files to copy, then uses an iterator to exclude docs-2.json.php and examples-1.json.php files from the phar and zip.
This cuts the phar down to 4.2 MB and brings the zip to under 800 KB.

Prune docs and examples from the phar and zip

---

docs/faq.rst

HHVM fixed the syntax issue with yield, but the semantics are still different. Updating the docs to reflect the new issue number.
/cc @chrisradek @xibz

Update HHVM issue referred to in FAQ

---

src/S3/S3Client.php
tests/S3/S3ClientTest.php

This PR sets 'decode_content' to `false` on HeadObject requests. If an object has a content-encoding of 'gzip' or 'deflate,' leaving 'decode_content' unset will cause the 'ContentLength' and 'ContentEncoding' headers to be swallowed.
/cc @mtdowling @chrisradek @xibz

Disable content decoding on HeadObject

---

src/S3/Transfer.php

This PR reverts 4b69d2a068b2c1b07017220cedffb4b63358240a, which can cause issues on large buckets.
/cc @mtdowling @chrisradek @xibz

Use an array of commands instead of mapping an iterator

---

src/Middleware.php
tests/MiddlewareTest.php

The timer middleware released recently included a bug where the rejection handler returned an exception rather than throwing it or returning a rejected promise.
/cc @cjyclaire @xibz @chrisradek

Return a rejection from Middleware::timer rejection handler.

---

src/DynamoDb/Marshaler.php
tests/DynamoDb/MarshalerTest.php

When marshaling a SetValue, the set is de-duped, but the process of de-duping leaves the keys in a state where json_encode will treat the set as an associative array making DynamoDB queries fail. Wrapping around array_values fixes this.

Fix non-sequential keys when SetValue with duplicates is de-duped

---

build/docs/classes/CodeSnippetGenerator.php
build/docs/classes/DocsBuilder.php

The ElasticBeanstalk examples cover operations that do not have an input shape defined. This PR makes the example generator use an empty array when no example input is defined.
/cc @cjyclaire

Make the input for an API example optional

---

src/Glacier/TreeHash.php
tests/Glacier/TreeHashTest.php

When you tried to calculate the tree hash of the string "0" (without quotes), you got the hash `TreeHash::EMPTY_HASH` instead of the expected `5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91b46729d73a27fb57e9`.

Fix wrong tree hash if content is a single zero

---

src/Aws/Common/Credentials/AbstractRefreshableCredentials.php
src/Aws/Common/Credentials/RefreshableInstanceProfileCredentials.php
src/Aws/Common/Signature/SignatureListener.php
tests/Aws/Tests/Common/Credentials/AbstractRefreshableCredentialsTest.php
tests/Aws/Tests/Common/Credentials/RefreshableInstanceProfileCredentialsTest.php

This PR addresses the same issue as https://github.com/boto/botocore/pull/764. In v2 of the SDK, if refreshable credentials expire during the signing process, the key, secret, and token may be pulled from different credential sets, as a call to `->refresh()` can be triggered by credentials being expired during calls to `->getAccessKeyId()`, `->getSecretKey()`, `->getSecurityToken()`. This PR updates the signature listener to instead get credentials using an atomic `->getCredentials()` method, which provides only a single opportunity for a refresh.
/cc @mtdowling @cjyclaire

Refresh credentials as a set when signing requests

---

src/Signature/SignatureV4.php
tests/Signature/SignatureV4Test.php

This PR changes the `X-Amz-SignedHeaders` value from 'Host' to 'host' to match [the spec](http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html) and [the Ruby SDK's implementation](https://github.com/aws/aws-sdk-ruby/blob/ef9f2d3655c4bacb3adff580a6b295df510f78fe/aws-sdk-core/lib/aws-sdk-core/signers/v4.rb#L183). This resolves #951.
/cc @mtdowling @cjyclaire

Lowercase signed header names in presigned request

---

docs/service/s3-stream-wrapper.rst
src/S3/ObjectCopier.php

`copy` cannot accurately report failure when the target is an S3 path. This PR adds a note to the stream wrapper guide to that effect.
/cc @cjyclaire @xibz

Document limitations of copy method wrt stream wrapper

---

src/S3/StreamWrapper.php
tests/S3/StreamWrapperTest.php

This PR updates the StreamWrapper wipe the cached stats on a path when writing new data to S3 in `stream_flush`. Previously, the stat would be cached in PHP stat cache and in the internal cache.
/cc @xibz @cjyclaire @mtdowling

Clear stat cache on stream_flush

---

behat.yml
features/bootstrap/Aws/Test/Integ/S3Context.php
features/s3/presignedUrls.feature
src/Command.php
src/S3/S3Client.php
src/Signature/S3SignatureV4.php
tests/Ec2/CopySnapshotMiddlewareTest.php
tests/Integ/S3Context.php
tests/S3/S3ClientTest.php

When creating presigned URLs, requests are first signed with `Middleware::signer` and then presigned. This PR updates the `createPresignedRequest` method to remove the signing middleware before serializing the command into a request. It also adds some presigned URL integ tests to make sure everything's hunky-dory.
Resolves #954.
/cc @mtdowling @xibz @cjyclaire

Presign without signing

---

docs/service/s3-stream-wrapper.rst

This PR adds a note to the stream wrapper docs explaining what permissions a client is expected to have vis-a-vis the objects accessed with the stream wrapper.
/cc @mtdowling

Document stream wrapper permissioning limitations.

---

src/Api/Parser/JsonRpcParser.php
tests/Api/Parser/JsonRpcParserTest.php

We already do this for REST-JSON and REST-XML.
/cc @mtdowling @cjyclaire

Do not attempt to parse the response body when no output shape is defined in JSON-RPC

---

src/Api/Serializer/RestSerializer.php
tests/Api/test_cases/protocols/input/rest-json.json
tests/Api/test_cases/protocols/input/rest-xml.json

`True` and `false` should serialize to "true" and "false," respectively. They were previously being rendered as "1" and "", which is not how [other SDKs](https://github.com/aws/aws-sdk-go/blob/master/private/protocol/rest/build.go#L244) are handling these values.
/cc @cjyclaire @xibz @mtdowling

Ensure booleans are serialized as strings (not ints) in querystrings

---

docs/faq.rst
docs/guide/configuration.rst
docs/guide/handlers-and-middleware.rst
tests/S3/S3ClientTest.php

~~This PR documents Guzzle's `decode_content` option as part of the HTTP handler configuration and defaults it to `false` in the S3 client. This should take care of #986 and any similar issues related to content encoding in S3.~~
This PR documents Guzzle's `decode_content` option as part of the HTTP handler configuration and documents the need to set it to `false` when dealing with compressed objects in S3. I do not believe the
default can be changed due to backwards compatibility concerns.
/cc @xibz @mtdowling @cjyclaire

Document how to disable content decoding

---

src/S3/Transfer.php

Normalizing filename before comparing with already normalized "base_dir".
(Windows problem)
```
'base_dir' => 'C:\data\example\files'
```
Before:
```
Transferring C:\data\example\files\test\file.txt -> s3://bucket/C:\data\example\files\test\file.txt (PutObject)
```
After:
```
Transferring C:/data/example/files/test/file.txt -> s3://bucket/test/file.txt (PutObject)
```

S3: Transfer - normalize path

---

docs/guide/paginators.rst

Fix a typo in documentation for Paginators.
cc:\ @xibz

Fix a typo in paginator documentation

---

composer.json
tests/Signature/SignatureV4Test.php

With newer `guzzlehttp/psr7` version upgrade, ci build is failing.
This PR fix the failure corresponds to `Psr7\parse_request()` behavior.
Removing hard-code duplicate headers signing test case.
:cc\ @mtdowling @xibz

Fix ci build failure

---

src/Credentials/CredentialProvider.php
src/Credentials/EcsCredentialProvider.php
tests/Credentials/CredentialProviderTest.php
tests/Credentials/EcsCredentialProviderTest.php

Add ECS Credential Provider which provides refreshable credentials within Amazon EC2 Container Service containers when enabled. Using ECS credential before fetching credentials from EC2 instance metadata in default credential chain.
cc:\ @mtdowling

Add ECS credential into credential chain

---

src/CloudSearchDomain/CloudSearchDomainClient.php
tests/CloudSearchDomain/CloudSearchDomainTest.php

This fix remove query string in URI when converting GET to POST.
Fix issue #1047 
cc: @chrisradek @LiuJoyceC

Remove query string in URI when converting GET to POST

---

tests/Api/Parser/JsonRpcParserTest.php
tests/Api/Serializer/ComplianceTest.php
tests/DoctrineCacheAdapterTest.php
tests/PsrCacheAdapterTest.php
tests/S3/AmbiguousSuccessParserTest.php
tests/S3/MultipartCopyTest.php
tests/S3/RetryableMalformedResponseParserTest.php
tests/S3/S3MultiRegionClientTest.php
tests/S3/TransferTest.php
tests/UsesServiceTrait.php
tests/WaiterTest.php

[PHPUnit](https://github.com/sebastianbergmann/phpunit) Api `getMock()` Api is tagged as [deprecated](https://github.com/sebastianbergmann/phpunit/blob/5.4/src/Framework/TestCase.php#L1557) since PHPUnit 5.4.0, and there is announcement a month ago about its [`backward-compatibility-break`](https://github.com/sebastianbergmann/phpunit/issues/2194) in PHPUnit 6.
To maintain backward-compatibility in SDK, with composer dependency ` "phpunit/phpunit": "4.0|5.0"`, replacing `getMock()` with `getMockBuilder()`.
Referring original [`getMock()`](https://github.com/sebastianbergmann/phpunit/blob/5.4/src/Framework/TestCase.php#L1536) method, and [`MockBuilder`](https://github.com/sebastianbergmann/phpunit-mock-objects/blob/master/src/Framework/MockObject/MockBuilder.php) in PHPUnit.
cc:\ …

Fix CI Warning caused by PHPUnit Api deprecation

---

src/RetryMiddleware.php
tests/RetryMiddlewareTest.php

Fix issue #1049 
When using some customized PHP installation approaches in certain OS environments, PHP Fatal Error sometimes couldn't be surfaced at first place. Current retry mechanism checks exceptions and ignores error, this caused trouble for silent failing and retrying succeed requests when dependency is missing in parsing responses.
cc: @mtdowling @xibz

When PHP Fatal Error is not surfaced, disable retry on certain errors

---

src/DynamoDb/Marshaler.php

Hello,
It seems the argument `mapAsObject` has been forgot to the method `unmarshalItem` as the
method description already reference it and the `unmarshalValue` method implementation.

DynamoDB Marshaler mapAsObject argument

---

src/S3/PostObjectV4.php
tests/S3/PostObjectV4Test.php

Hi,
I've been using locally the PostObjectV4 to create form inputs that allowed to directly upload to S3.
This worked perfectly while using access keys. However once deployed and using temporarily credentials, this didn't work.
After a lot of research, it appears that you need to pass an additional "x-amz-security-token" to the policy, and this token must also be set in the HTML form. cf: http://stackoverflow.com/questions/18884683/browser-uploads-to-s3-with-instance-roles/19024044
I've tested this fix and it works :).

Properly set security token for S3 direct upload when using temporary credentials

---

src/S3/S3ClientTrait.php
tests/S3/S3ClientTest.php

Addressing issue #1065 
Adding a rejected promise handler to `determineBucketRegionAsync` to surface exception immediately when making a `HEAD` bucket request.
cc:\ @mtdowling @xibz @jeskew

Adding a rejected promise handler to determineBucketRegionAsync

---

build/docs/classes/DocsBuilder.php

In current [API doc](http://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html), there exists 2 EC2 QuickLinks leads to 2 versions of `Ec2Client`.
This bug is introduced in PR #1072 that intends to fix the problem of ELB and ELBV2 sharing same service title by indexing them with `title` and `shortTitle` separately. In `quickLink` part, since now each service version has different key in `services` array, the latest version of the service needs to be kept.
@mtdowling

[Doc Fix] Duplicate "EC2" in Doc quicklink

---

tests/S3/S3ClientTest.php

The CI failure caused by:
PHPUnit version bump from 5.6.4 to 5.6.5, working on fixing
@mtdowling

Fix PHPUnit Mock object failing (5.6, 7.0)

---

src/DynamoDb/LockingSessionConnection.php

Between attempts to access a locked session, the handler is meant to
wait for a configurable number of microseconds. The handler code was
previously multiplying the wait time by 10^-6 before passing it to
usleep, even though the values were already in microseconds. For the
default min and max wait time values of 10000 and 50000, the usleep
argument would always be less than one and so the handler wouldn't
wait at all between attempts.
This commit removes the multiplication by 10^-6, so the handler sleeps
for the intended amount of time between requests.

Fix DynamoDB session handler sleep time

---

docs/service/s3-presigned-url.rst

I received a complaint that 'us-standard' is not a valid region. Changed to 'us-east-1'.

change us-standard to us-east-1 in doc example

---

src/S3/PostObjectV4.php
tests/S3/PostObjectV4Test.php

Fixing issue #1129 
The bug: When virtual-style endpoint is hard coded by `endpoint` configuration, `PostObjectV4` doesn't detect it, will still trying to convert it to virtual-style, which causes 2 buckets in the url looks like: `https://bucket.bucket.s3.amazonaws.com`.
@mtdowling @xibz

Fix PostObjectV4 ignoring customized virtual-style endpoint

---

Makefile

```
sed -i  '' -e "s/VERSION = '.*'/VERSION = '3.20.15'/" src/Sdk.php
```
The above command would fail on GNU. 
The update works fine on both GNU and OSX 10.9+
Reference:
- http://www.grymoire.com/Unix/Sed.html#uh-62h
- http://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux

Fix sed to work on GNU

---

build/docs/classes/CodeSnippetGenerator.php

Considering that manually maintain and fix example file might not be a best practice, which would introduce burden into CI process as well, since having out-dated documentation is bad, this PR skips invalid example code snippets with helpful message instead of letting it stops doc generation.
@imshashank @mtdowling
#1152 
Added notes:
I do have concerns that this solution will make it easy to ignore existing example discrepancy.
Edited:
Personally, I think this PR should only be merged when there is no better option when integrate with full CI

Skip invalid example snippets instead of breaking the doc

---

src/S3/S3ClientTrait.php

When these methods were moved to from `Aws\S3\S3Client` to `Aws\S3\S3ClientTrait`, they ceased automatically inheriting their documentation from `Aws\S3\S3ClientInterface`. This PR adds `@see` annotations on all methods in the trait linking them to the methods in the interface. (In the generated API docs, the fully qualified method names are resolved to hyperlinks.)
/cc @imshashank @mtdowling

Link docs for S3ClientTrait methods to the S3ClientInterface methods they implement

---

src/DynamoDb/Marshaler.php
tests/DynamoDb/MarshalerTest.php

Some PHP versions will create references to keys instead of copying them
after doing a foreach-by-reference, which can cause unexpected state
mutations. Remove those foreach-by-reference calls to prevent that from
happening
Example: https://3v4l.org/jNSeb

Fix Marshaler leaving dangling references

---

features/smoke/application-autoscaling.feature
src/ClientResolver.php
tests/ClientResolverTest.php

This change addresses a regression introduced in #1192 that affects services that share an endpoint prefix. The `signingName` metadata member present in the service model is used instead of the one returned by the endpoint provider.
/cc @cjyclaire && @imshashank

Prefer the signing name provided by the service model to that provided by the endpoint provider

---

composer.json
src/S3/PostObject.php
src/S3/PostObjectV4.php

This change allows the SDK to pull in new versions of the Guzzle PSR7 package other than 1.4.0. It also addresses deprecation notices that arise when using `Aws\S3\PostObject` and `Aws\S3\PostObjectV4`.
Resolves #1195 
/cc @cjyclaire && @imshashank

Update version constraint on guzzlehttp/psr7 to allow 1.4.1

---

src/Endpoint/Partition.php
src/MultiRegionClient.php
src/S3/ObjectCopier.php
src/S3/S3MultiRegionClient.php
tests/MultiRegionClientTest.php
tests/S3/S3MultiRegionClientTest.php

This PR would resolve #1207.
The root cause of the issue was that 'regionalizing' commands within the `S3MultiRegionClient` was occurring inside the client's `executeAsync` method, where the command would be executed and, on failure, recreated using the appropriate region. The trouble with that approach was that the multipart uploader was keeping track of completed and failed parts by adding middleware to the UploadPart command's handler list, and this list was not shared between different regionalized commands.
This PR removes the custom implementation of `executeAsync` in favor of applying regionalization via a 'determine_region' middleware. MultiRegion clients now have and execute their own (usually empty) middleware stacks, the core handler of which executes the operation on the …

Update MultiRegionClient and S3MultiRegionClient to honor middleware

---

src/Exception/AwsException.php
tests/Exception/AwsExceptionTest.php

Had a request from a customer to get a concise message like PHP SDK v2.
This is a simple PR to add a new method `getErrorMessage()`. 
Please review the PR.
@cjyclaire @jeskew

Add method to get service error message if available (like v2)

---

tests/ClientResolverTest.php
tests/Credentials/CredentialProviderTest.php

Environment Variable `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` is set by Codebuild and ECS.
This PR unsets the variable during the unit tests.

Fix broken tests when SDK built in codebuild or ECS

---

src/Sqs/SqsClient.php
tests/Sqs/SqsClientTest.php

Cope with SQS' .fifo/:fifo ARN inconsistency, with included test.
Fix for #1255

Fix SQS' fifo Queue ARN Generation

---

features/streams/streamWrapper.feature
tests/Integ/NativeStreamContext.php

This scenario relied on the use of error_clear_last for its Given, which is only available in PHP 7.0+. Given/And clauses of the scenario have been removed, along with their context functions, and the scenario has been renamed.

Update integration scenario to not use PHP7+ functionality

---

.changes/nextrelease/fix_transfer_download_directory_traversal.json
src/S3/Transfer.php
tests/S3/TransferTest.php

Add S3Exception for keys that leave the path root, supplemented by tests.

S3 Transfer Download Patch

---

src/S3/Transfer.php

Revert behavior to correctly download contents directly in to destination folder instead of the including the Key portion of the source path.
Fixes #1282

Fix Transfer Download Sink Resolution

---

.changes/nextrelease/sqs_message_attribute_validation.json
src/Sqs/SqsClient.php
tests/Sqs/SqsClientTest.php

Validate SQS Message Attributes via MD5 with encoded input string, supplemented with tests. Checks are done in the same `validateMd5` function so users who unregister the `sqs.md5` receive no new exceptions.
PR to complete #1148

SQS Message Attribute Validation

---

Makefile
build/docs.php
build/docs/classes/CodeSnippetGenerator.php
build/docs/classes/DocsBuilder.php

Instead of skipping Code Snippets that have issues, track them and add an option to log them out to a file.

Log on Broken Doc Shapes

---

.changes/nextrelease/host_style_default.json
src/S3/S3Client.php
src/S3/S3EndpointMiddleware.php
tests/FunctionsTest.php
tests/Integ/GuzzleV6StreamHandlerTest.php
tests/S3/BucketEndpointMiddlewareTest.php
tests/S3/ObjectCopierTest.php
tests/S3/ObjectUploaderTest.php
tests/S3/S3ClientTest.php
tests/S3/S3EndpointMiddlewareTest.php
tests/S3/S3MultiRegionClientTest.php
tests/S3/StreamWrapperPathStyleTest.php

Change the default URI to use host style over path style, including with dual-stack, with a fallback for incompatibilities. Configuration options have been added and detailed for the S3Client and its sub-command. Tests that relied on path-style but did not alter the URI have been updated to bucket style. A significant amount of tests that relied on it and altered the URI have been duplicated to verify both the host style and path style.

S3 Host-Style URIs By Default

---

.changes/nextrelease/multipart_params.json
src/S3/MultipartCopy.php
src/S3/MultipartUploader.php
src/S3/MultipartUploadingTrait.php
src/S3/ObjectCopier.php
src/S3/ObjectUploader.php
tests/S3/MultipartCopyTest.php
tests/S3/MultipartUploaderTest.php
tests/S3/ObjectCopierTest.php
tests/S3/ObjectUploaderTest.php

Added 'params' passthrough for MultipartUploader/Copy. Increased functionality of ObjectUploader/Copier with regards to 'params'. Added 'before_lookup' option to ObjectCopier to operate on its 'HeadObject' command.
Addresses #1312 / #1291 and #1232 / #1238 in a consistent way that upgrades functionality while maintaining the contract established by each high-level abstraction.

Bug Fix + Functionality Updates for MultipartUploader/Copy and ObjectUploader/Copier

---

.changes/nextrelease/contentlength_set.json
src/S3/MultipartUploader.php
tests/S3/MultipartUploaderTest.php

Fixes #1326 - not setting the ContentLength for all MultipartUploader::createPart streams, therefore potentially using an incorrect, $options['params'] value.

ContentLength Fix for MultipartUploader::createPart

---

.changes/nextrelease/multiregion_auth_header_fix.json
src/S3/S3ClientTrait.php
src/S3/S3MultiRegionClient.php
tests/S3/S3MultiRegionClientTest.php

Properly handle reading mismatched regions from S3's AuthorizationHeaderMalformed exception for S3MultiRegionClient, updated host-style tests to reflect correct behavior.
Fixes #1324

Fix for S3MultiRegionClient receiving AuthorizationHeaderMalformed with host-style

---

.travis.yml
src/History.php
src/LruArrayCache.php
tests/DynamoDb/DynamoDbClientTest.php
tests/DynamoDb/SessionHandlerTest.php
tests/S3/BatchDeleteTest.php

Without this:
```
$ php72 vendor/bin/phpunit  -d memory_limit=1G  --testsuite=unit --no-coverage
PHPUnit 5.7.20 by Sebastian Bergmann and contributors.
.............................................................   61 / 2121 (  2%)
.............................................................  122 / 2121 (  5%)
.............................................................  183 / 2121 (  8%)
.............................................................  244 / 2121 ( 11%)
.............................................................  305 / 2121 ( 14%)
.............................................................  366 / 2121 ( 17%)
.................................................SSSSSSSSSSSS  427 / 2121 ( 20%)
SSSSSSSSSSSSSSSSSS..........................................E  488 / 2121 ( 23%) …
```

Fix for upcoming PHP 7.2

---

build/docs/classes/DocsBuilder.php

Just wading into making my first contribution to the documentation. :-) Fixes typo, timestamp was mistyped as timesamp.

Fixed typo

---

.changes/nextrelease/config_option_message_fix.json
src/ClientResolver.php
tests/ClientResolverTest.php

Correctly provide information on required parameters that are set to `null` when resolving a client.
Resolves the messaging issue from #1051

Config option message fix

---

.changes/nextrelease/guzzle5_SaveAs_file_fix
src/Handler/GuzzleV5/GuzzleHandler.php
tests/Handler/GuzzleV5/HandlerTest.php

Fixes an issue where exceptions weren't being fully loaded when using a `SaveAs` parameter set to a file path on Guzzle v5.
Fixes #1355

Guzzle5 Exception SaveAs Fix

---

src/Ses/SesClient.php

Update SES RawMessage documentation to reflect that it will be base64 encoded automatically.
Fixes #1295 
Fixes #1345

SES RawMessage Doc Update

---

.changes/nextrelease/update-composer-dependencies.json
compatibility-test.php
composer.json

Move required dependencies to Composer `require`

---

.changes/nextrelease/path_style_abstraction_updates.json
src/S3/PostObject.php
src/S3/PostObjectV4.php
tests/S3/PostObjectTest.php
tests/S3/PostObjectV4Test.php

`PostObject[V4]` classes now obey the `'use_path_style_endpoint'` client configuration in form generation.
Fixes #1399

Obey 'use_path_style_endpoint' in PostObject[V4]

---

.changes/nextrelease/pagination_next_command_params_fix.json
src/ResultPaginator.php
tests/ResultPaginatorTest.php

Override passed in starting token for a `ResultPaginator` when moving to the next command.
Fixes #1396

ResultPaginator createNextCommand Arguments Fix

---

.changes/nextrelease/presign_sourceregion_fix.json
src/PresignUrlMiddleware.php
src/Rds/RdsClient.php
tests/PresignUrlMiddlewareTest.php
tests/Rds/RdsClientTest.php

Update `PresignUrlMiddleware` to take an optional `'require_different_region'`, default `false`, for providing presigned urls only if the source and destination regions differ. Require this for `RdsClient` operations that use the middleware.
Fixes #1415

PresignUrlMiddleware 'require_different_region' Option

---

.changes/nextrelease/aad_fix.json
src/S3/Crypto/S3EncryptionClient.php

Fixes an issue with loading @CipherOptions on getObject[Async] decryption.
/cc @jeskew 
Fixes #1426

S3EncryptionClient getObjectAsync CipherOptions Fix

---

.changes/nextrelease/refactoring-tests
tests/AwsClientTest.php
tests/ClientResolverTest.php
tests/Credentials/AssumeRoleCredentialProviderTest.php
tests/Credentials/CredentialProviderTest.php
tests/Credentials/EcsCredentialProviderTest.php
tests/Credentials/InstanceProfileProviderTest.php
tests/DynamoDb/LockingSessionConnectionTest.php
tests/DynamoDb/MarshalerTest.php
tests/Handler/GuzzleV5/HandlerTest.php
tests/Integ/NativeStreamContext.php
tests/Integ/S3Context.php
tests/S3/Crypto/S3EncryptionClientTest.php
tests/S3/S3ClientTest.php
tests/S3/StreamWrapperPathStyleTest.php
tests/S3/StreamWrapperTest.php
tests/Signature/SignatureV4Test.php
tests/WrappedHttpHandlerTest.php

I've refactored some tests, using:
- `assertFileExists` and `assertFileNotExists` instead of `file_exists` method
- `assertInternalType` instead of `is_*` methods;
- `assertNull` instead of strict comparisons with `null` keyword;
- `assertFalse` instead of strict comparisons with `false` keyword;
- `assertStringEqualsFile` when comparing strings and file;
- `assertCount` instead of `count` method.

Refactored some tests with PHPUnit assert methods

---

.changes/nextrelease/refactoring-more-tests
tests/Api/ShapeTest.php
tests/Build/Changelog/ChangelogBuilderTest.php
tests/CommandTest.php
tests/DynamoDb/MarshalerTest.php
tests/S3/StreamWrapperPathStyleTest.php
tests/S3/StreamWrapperTest.php

Continuing to refactory tests, like #1430, I've used:
- `assertArrayHasKey` and `assertArrayNotHasKey` instead of `isset` function;
- `assertCount` instead of `count` and `iterator_count` ([`PHPUnit` handles it](https://github.com/sebastianbergmann/phpunit/blob/5.7/src/Framework/Constraint/Count.php#L61))

Refactoring more tests

---

.changes/nextrelease/fluent-mock
tests/Handler/GuzzleV5/HandlerTest.php

Another `PHPUnit 6` future compatibility: `getMock` was removed, so, we should use fluent interface when defining our mocks. This was the last occurrence.

Use fluent interface when defining mocks

---

docs/service/dynamodb-session-handler.rst

While setting up a DDB table for Session persistence, I felt a lack of guidance around which IAM permissions developers/resources should have access to.
It's somehow written between the lines in the [guide](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/dynamodb-session-handler.html) about this matter, but a developer won't be sure until he/she start reading the [StandardSessionConnection.php](https://github.com/aws/aws-sdk-php/blob/master/src/DynamoDb/StandardSessionConnection.php) which may take some time. 
So I decided to append to the guide the required permissions to make DynamoDB Session Handler feature work. Then again, there is always room for enhancement, isn't there?
If you think this will be beneficial for aws-sdk-php, please accept this PR.
I confirm I'm releasing …

Add required IAM permissions for DDB Session Handler

---

.changes/nextrelease/env_disable_ec2_metadata_access.json
docs/guide/credentials.rst
src/Credentials/InstanceProfileProvider.php
tests/Credentials/InstanceProfileProviderTest.php

Add support for an `AWS_EC2_METADATA_DISABLED` environment variable to short-circuit requests for credentials via the InstanceProfileProvider.
/cc @cjyclaire

Add AWS_EC2_METADATA_DISABLED Environment Variable

---

src/PhpHash.php

With PHP 7.2, the `hash` extension was updated to use objects instead of resources. See https://secure.php.net/manual/en/migration72.incompatible.php#migration72.incompatible.hash-ext-to-objects .

Update `Aws\PhpHash::$context` docblock with `HashContext` type.

---

.changes/nextrelease/retry_curl56.json
src/RetryMiddleware.php
tests/RetryMiddlewareTest.php

Implements a method to retry `CURLE_*_ERROR` based failures for `AwsExceptions` preceeded by `ConnectExceptions` that do not return true from `->isConnectionError()`.
Resolves #924 
/cc @jeskew

Retry Specific cURL Error Codes

---

.changes/nextrelease/verify_curl_extension.json
README.md
src/RetryMiddleware.php
tests/RetryMiddlewareTest.php

Verify we have the `'curl'` extension before retrying on the `CURLE_RECV_ERROR` curl const. Updates README.md language to match `composer.json` and documentation language.
Fixes #1480

Fix Missing CURLE_RECV_ERROR

---

src/S3/Transfer.php

The docs didn't match the implementation, adjust the docs to be
correct.
It's been this way since 2015 -- 74f8c50c0bde2ef8d8ec57b195c4a20857056f9f

S3\Transfer::construct(): correct docs

---

.changes/nextrelease/signer_int_fix.json
src/CloudFront/Signer.php
tests/CloudFront/SignerTest.php
tests/CloudFront/UrlSignerTest.php

Updates the `Signer` to force expire timestamps to match CloudFront required unquoted integers.
Fixes #1499

Signer Unquoted Integers Fix

---

.changes/nextrelease/fix_curl_retry.json
src/RetryMiddleware.php
tests/RetryMiddlewareTest.php

Hello,
we have upgraded to the latest AWS SDK because the retry of `CURLE_RECV_ERROR` was fixed in https://github.com/aws/aws-sdk-php/releases/tag/3.52.0
Unfortunately after deploy of the new application version with updated AWS SDK we are still receiving occasional `CURLE_RECV_ERROR` errors.
I've tried to debug a code and I've noticed that `GuzzleHttp\Exception\ConnectException` exception is expected in AWS SDK https://github.com/aws/aws-sdk-php/blob/299ac47ff5171d6a25f788dc333c0a3c8db40f69/src/RetryMiddleware.php#L104 but `GuzzleHttp\Exception\RequestException` is  thrown in Guzzle https://github.com/guzzle/guzzle/blob/748d67e23a984e7a2562847994fd133fd4e629a6/src/Handler/CurlFactory.php#L154 . 
So I think that `CURLE_RECV_ERROR` is never retried. 
This PR should fix it.
thanks

CURLE_RECV_ERROR  error retry fixed

---

.changes/nextrelease/preceding_slash_signing_fix.json
src/Signature/S3SignatureV4.php
tests/Signature/S3SignatureV4Test.php

Fixes an issue that would strip a preceding slash from a key during the signing process on virtual host style pathing, resulting in an invalid signature.
Fixes #1507 
/cc @jeskew

Preceding Slash Signing Fix

---

.gitattributes

this includes codecov.yml which shouldn't be needed in the export

Updated gitattributes

---

.changes/nextrelease
src/Waiter.php

Fixes docblock `@param` tags to reference Result class with a consistent case.
This did not affect any functionality, but confused static analyzers (see vimeo/psalm#673)

Consistent Result class casing for docblocks

---

.changes/nextrelease/update_ecs_smoke_test.json
features/smoke/ecs.feature
tests/Integ/SmokeContext.php

Adds the ability for Integ/Smoke tests to check status codes. Updates ECS Handling errors to use a status code check.

Status Code Checking in Smoke/Integ Tests

---

tests/Integ/S3Context.php

Move an `assertStringFileEquals` to an `assertEquals` due to underlying changes that broke the validation.

S3Context Validation Fix

---

.changes/nextrelease/dti_update.json
src/Signature/SignatureV4.php
tests/Signature/SignatureV4Test.php

Added the ability for signatures to be generated off of \DateTimeInterface objects that are not based on \DateTime.
Resolves #1513
Resolves #1514

Signatures to be generated from any \DateTimeInterface

---

build/docs/classes/DocsBuilder.php

Update sorting for Service APIs to be sorted by namespace, like the sidebar.
Resolves #1539 
No changelog document because it doesn't affect the SDK itself.

Sort 'Service APIs' by namespace

---

.changes/nextrelease/security_token_header_fix.json
src/Signature/SignatureV4.php
tests/Signature/SignatureV4Test.php

Updates the `SignatureV4` presigning process to not sign, and subsequently require on use, the `'X-Amz-Security-Token'` header when it's already signed in the query string.
Fixes #1609

`'X-Amz-Security-Token'` Presign Fix

---

.changes/nextrelease/ini_scanner_raw_update.json
src/Credentials/CredentialProvider.php
tests/Credentials/CredentialProviderTest.php

Update`::ini` parsing to handle unquoted components that contain equals signs.
Fixes #1526
Closes #1563

Add ini parse directive

---

.changes/nextrelease/jsonSerialisationBugfix.json
src/Api/Serializer/JsonBody.php
tests/Api/Serializer/JsonBodyTest.php

Fix to correctly format 'structure' options into JSON, when they have no valid values.
Fixes #1638

Json serialisation bugfix

---

.changes/nextrelease/bump-guzzlehttp
.travis.yml
composer.json

See https://github.com/guzzle/guzzle/pull/2112 and https://github.com/laravel/framework/pull/26125

Bump patch version of Guzzle for PHP 7.3 compatibility

---

.changes/nextrelease/spl-extension
composer.json

Since PHP 5.3.0, the SPL extension is always available and it can not be disabled.
Ref: https://php.net/manual/en/spl.installation.php

Remove requirement of always available extension

---

.changes/nextrelease/api_validate_assoc_array
src/Api/Validator.php
tests/Api/ValidatorTest.php

https://github.com/aws/aws-sdk-php/issues/1722
The existing heuristic for determining an assoc array looks only
for the presence of a `0` index.  However to correctly determine
whether a php array will be serialized (json) or marshaled (DynamoDB)
into a list (array) or map (assoc), the hueristic must be to check
for sequential integer keys starting at 0.
This change will walk the array checking the key against an incrementing
integer.  at any point where the key does not meet the expected integer
value, the iteration will stop and the array will be considered
associative. (this implementation is similar to the DynamoDB marshaler)
For any array not having a 0 index, this method will return after
the first iteration, so for the shape of the assoc arrays that this
method successfully …

Fixes validation on assoc arrays having a 0 index

---

build/docs/theme/js/main.js

* Remove unnecessary height adjustment on the API docs pages script, which combined with the CSS overflow settings causes anchor links to jump back to the top of the page.
Fixes #1729

Fix for anchor links in docs issue

---

.changes/nextrelease/iterator_test_refactor.json
tests/AwsClientTest.php
tests/fixtures/aws_client_test/ec2/2019-03-04/api-2.json
tests/fixtures/aws_client_test/ec2/2019-03-04/paginators-1.json

Refactors client iterator tests to use mocked model data instead of actual model data, which is subject to change by the service.

Iterator test refactor

---

.changes/nextrelease/stream_wrapper_fixes.json
src/S3/StreamWrapper.php
tests/S3/StreamWrapperTest.php

* Updates the S3 stream wrapper to be able to write empty files for PHP 7+
Fixes #1724

S3 stream wrapper write empty files

---

.changes/nextrelease/cloudfront-signer-optimization
src/CloudFront/Signer.php
tests/CloudFront/SignerTest.php

openss_sign() is abysmally slow. On a fast CPU with a small amount of
data it takes 1.5ms of CPU time.
Turns out, half of that was parsing the private key. If we have
openssl parse the key ahead of time, `openssl_sign()` takes half the
time.
This change brought it from 1.5ms to 0.7ms per call, still really
slow but much better.
Note: We started running into performance issues with *lots* of image
urls being rendered on long pages.
---

CloudFront Signer: parse private key once

---

.changes/nextrelease/parse_ini_hash_comment.json
src/ClientSideMonitoring/ConfigurationProvider.php
src/Credentials/CredentialProvider.php
src/EndpointDiscovery/ConfigurationProvider.php
src/functions.php
tests/FunctionsTest.php

* Adds helper function to parse full-line hash comments for credentials and config files, which was removed in PHP 7's implemention of parse_ini_file.
Closes #1754

Parse ini update

---

.changes/nextrelease/expect-http-config
src/Handler/GuzzleV5/GuzzleHandler.php

Change for #1733 
Allows Expect config option to be passed through to Guzzle: http://docs.guzzlephp.org/en/stable/request-options.html#expect

pass through expect on http config

---

.changes/nextrelease/process_credential_provider.json
src/Credentials/CredentialProvider.php
tests/Credentials/CredentialProviderTest.php

Adds a credential_process provider.  
The SDK will execute the command specified as a credential_process in the shared INI configuration file (at ~/.aws/credentials by default).  This command should return JSON containing valid credentials.

add credential_process provider

---

.changes/nextrelease/bugfix_php_input_stream_s3_multipart_upload.json
src/S3/ObjectUploader.php

**#1767 S3 Multipart Upload php://input stream bug**
Updates ObjectLoader's requiresMultipart() to handle php://input streams without data loss.

Bugfix php input stream s3 multipart upload

---

.changes/nextrelease/psr16-adapter
composer.json
src/Psr16CacheAdapter.php
tests/Psr16CacheAdapterTest.php

This change adds implementation of [PSR-16](https://www.php-fig.org/psr/psr-16/) compatible cache adapter.

Added simple cache (PSR-16) adapter.

---

.changes/nextrelease/1755_php_7_throwable_support_abstract_upload_manager.json
src/Multipart/AbstractUploadManager.php

Closes #1755
Requesting a pull to aws:master from bradynpoulsen:bug/1755_php_7_throwable_support_by_multipart_abstractuploadmanager
Write a message for this pull request. The first block
of text is the title and the rest is the description.

Make Multipart\AbstractUploadManager accept PHP 7+ Throwable as a failure type

---

.gitignore
src/DynamoDb/LockingSessionConnection.php
src/DynamoDb/SessionConnectionConfigTrait.php
src/DynamoDb/SessionHandler.php
src/DynamoDb/StandardSessionConnection.php
tests/DynamoDb/SessionConnectionConfigTraitTest.php
tests/DynamoDb/SessionHandlerTest.php
tests/DynamoDb/StandardSessionConnectionTest.php

We needed to configure the DynamoDB Session data and session lifetime attributes as we share the session across different micro-services built upon different languages and frameworks and saving session data in different attributes than the ones supported by this default. Hence the PR:
- Added SessionConnectionConfigTrait with standard configurations defined both for Standard and Locking Session connections.
- Added tests for Standard and Custom configurations
@srchase opening a new one so that we have a full rebase and just one commit :) hope it's ok

DynamoDB SessionHandler - Configurable data & session lifetime attr

---

.changes/nextrelease/changelog_behat_scalars.json
behat.yml

Fixes integration test runner when Behat depends on symfony yaml ~4.0
Adds quotes surrounding path scalars.
Tested with symfony/yaml versions 2.8.50, 3.4.27 and 4.2.8.

fix scalars when using symfony/yaml ~4.0

---

.changes/nextrelease/changelog_rest_json_content_type.json
src/Api/Serializer/RestJsonSerializer.php
tests/Api/Serializer/RestJsonSerializerTest.php

Fix for https://github.com/aws/aws-sdk-php-laravel/issues/161
Use ```application/json``` on rest-json requests, instead of using ```x-amz-json-...``` 

fix content-type on rest-json serializer

---

.changes/nextrelease/changelog_decryption_trait.json
src/Crypto/DecryptionTrait.php

*Issue #1787 *
When using the _S3EncryptionClient::getObject()_ to fetch previously client side encrypted document, as described [here](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-encryption-client.html), errors like this was encountered.
`
Argument 1 passed to Aws\S3\Crypto\S3EncryptionClient::getTagFromCiphertextStream() must be an instance of GuzzleHttp\Psr7\Stream, instance of GuzzleHttp\Psr7\LazyOpenStream given, called in .../vendor/aws/aws-sdk-php/src/Crypto/DecryptionTrait.php on line 149
Argument 1 passed to Aws\S3\Crypto\S3EncryptionClient::getStrippedCiphertextStream() must be an instance of GuzzleHttp\Psr7\Stream, instance of GuzzleHttp\Psr7\LazyOpenStream given, called in .../vendor/aws/aws-sdk-php/src/Crypto/DecryptionTrait.php on line 156
`
I fixed this by …

Changed type hints from Stream to StreamInterface in DecryptionTrait

---

.changes/nextrelease/changelog_fix_xml_body_escaping.json
src/Api/Serializer/XmlBody.php
tests/Api/test_cases/protocols/input/rest-xml.json

Escape strings in XML body requests
Resolves https://github.com/aws/aws-sdk-php/issues/1790

fix XML body escaping

---

.changes/nextrelease/changelog_endpoint_path.json
src/Api/Serializer/RestSerializer.php
tests/Api/Serializer/RestJsonSerializerTest.php

Resolves https://github.com/aws/aws-sdk-php/issues/1730
Removes leading slash of relative path when resolving URIs.  This preserves the path when a custom endpoint with a path is specified for a client.

fix endpoint path removal

---

.changes/nextrelease/streaming_request_payloads.json
src/AwsClient.php
src/Exception/IncalculablePayloadException.php
src/StreamRequestPayloadMiddleware.php
tests/StreamRequestPayloadMiddlewareTest.php

* Adds support for 'requiresLength' trait, adding headers as necessary for streaming operations.

Streaming request payloads

---

Makefile

Use --suite instead of --tags to identify smoke tests to keep Behat from loading all integ contexts.

use Behat --suite for smoke tests

---

tests/Integ/CredentialsContext.php

Fixes integration tests failing when using --tags, due to BeforeSuite and AfterSuite steps getting invoked.
Use BeforeFeature and AfterFeature instead.

Fix failing integ tests

---

.changes/nextrelease/changelog_fix_json_parse_header.json
src/Api/Parser/AbstractRestParser.php
tests/Api/test_cases/protocols/output/rest-json.json

resolves https://github.com/aws/aws-sdk-php/issues/1813
ignore headers that cannot be parsed as JSON

fix json parse error on empty headers

---

src/Handler/GuzzleV5/GuzzleHandler.php

Enables 'cert' http config option to be passed through to GuzzleV5
Adds 'cert' to whitelisted http config options.

whitelist cert http option on GuzzleV5

---

.changes/nextrelease/changelog_csm_agent_host_config.json
src/ClientSideMonitoring/AbstractMonitoringMiddleware.php
src/ClientSideMonitoring/Configuration.php
src/ClientSideMonitoring/ConfigurationInterface.php
src/ClientSideMonitoring/ConfigurationProvider.php
tests/ClientSideMonitoring/ApiCallAttemptMonitoringMiddlewareTest.php
tests/ClientSideMonitoring/ApiCallMonitoringMiddlewareTest.php
tests/ClientSideMonitoring/ConfigurationProviderTest.php
tests/ClientSideMonitoring/ConfigurationTest.php

host for client side monitoring can be configured via `AWS_CSM_HOST` environment variable or `csm_host` in profile.
Resolves #1659 

configurable host for client side monitoring

---

.changes/nextrelease/changelog_assume_role_from_config.json
src/Credentials/CredentialProvider.php
tests/Credentials/CredentialProviderTest.php

Enables profiles in ~/.aws/config to be used in auto-assuming role.
When environment variable ```AWS_SDK_LOAD_NONDEFAULT_CONFIG``` is set, profiles will be read from ```~/.aws/config```.  Any profiles returned from ```~/.aws/config``` can be used as a ```source_profile``` or the profile of the role to be assume.
Given this credential file at ~/.aws/credentials:
```
[profile1]
output = json
region = us-east-1
aws_access_key_id = A**************
aws_secret_access_key = *****************
```
And this config file at ~/.aws/config:
```
[profile profile2]
output = json
region = us-east-1
role_arn = arn:aws:iam::123456789012:role/Developer
source_profile = profile1
```
profile2 will be assumed using the credentials from profile1.  The reverse also works, as well as using one profile in …

assume role using profile(s) in ~/.aws/config

---

.changes/nextrelease/standard_connection_session_data_type.json
src/DynamoDb/SessionConnectionConfigTrait.php
src/DynamoDb/StandardSessionConnection.php
tests/DynamoDb/SessionConnectionConfigTraitTest.php
tests/DynamoDb/StandardSessionConnectionTest.php

Allows configuration of dataAttributeType on StandardSessionConnection.  Defaults to ```string``` (```S```) to preserve backward compatibility, but can be set to ```binary``` (```B```) to make session data binary safe.
```
$sessionHandler = SessionHandler::fromClient($dynamoDbClient, [
'data_attribute_type' => 'binary',
]);
```
Resolves https://github.com/aws/aws-sdk-php/issues/1831

Configuration for StandardSessionConnection data type

---

.changes/nextrelease/presigned_url_options.json
src/S3/S3Client.php
src/S3/S3ClientInterface.php
src/S3/S3MultiRegionClient.php
src/Signature/AnonymousSignature.php
src/Signature/SignatureInterface.php
tests/S3/S3ClientTest.php

Implements https://github.com/aws/aws-sdk-php/issues/1839
Allows options to be passed through S3Client to presigner, enabling reproducible presigned URLs to be generated via setting the start_time.
```
use Aws\S3\S3Client;
$s3Client = new S3Client([
'version' => 'latest',
'region' => 'us-east-1',
'credentials' => ['key' => 'foo', 'secret' => 'bar']
]);
$cmd = $s3Client->getCommand('GetObject', [
'Bucket' => 'foo',
'Key' => 'bar'
]);
$request = $s3Client->createPresignedRequest(
$cmd,
'+120 minutes',
['start_time' => 1562349099]
);
$presignedUrl = (string)$request->getUri();
```

S3 presigned options

---

.changes/nextrelease/assume_with_web_identity.json
src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php
src/Credentials/CredentialProvider.php
src/RetryMiddleware.php
tests/Credentials/AssumeRoleWithWebIdentityCredentialProviderTest.php
tests/Credentials/CredentialProviderTest.php
tests/RetryMiddlewareTest.php

Implements credential provider that allows role to be assumed using web_identity_token_file, specified as an environmental variable, ```AWS_WEB_IDENTITY_TOKEN_FILE``` or as ```web_identity_token_file``` option in shared credentials/config.

Assume role with web identity

---

.changes/nextrelease/redundant_includes.json
src/functions.php
tests/FunctionsTest.php

PHP include (require) only release file handles after script stop, use include for variables, may cause "failed to open stream too many open files" error.
I found this problem when I run coverage test, also happen to long running tasks (such as use loop to load sqs without quit script 24/7).

Avoid repeatedly include same files for variables

---

.changes/nextrelease/fix_empty_credential_profile.json
src/Credentials/CredentialProvider.php
tests/Credentials/CredentialProviderTest.php

Resolves https://github.com/aws/aws-sdk-php/issues/1843
Checks that profile exists for ```assumeRoleWithWebIdentityCredentialProvider``` on default chain.

fixes default chain failing on missing profile

---

CONTRIBUTING.md
build/changelog/ChangelogBuilder.php

Adds ```documentation``` changelog type.  
Clarifies CONTRIUBUTING.md.

add documentation changelog type

---

.changes/nextrelease/instance_profile_provider_retries.json
src/Credentials/InstanceProfileProvider.php
src/Exception/InvalidJsonException.php
tests/Credentials/InstanceProfileProviderTest.php

resolves https://github.com/aws/aws-sdk-php/issues/1664
Implements exponential backoff when invalid JSON is returned to InstanceProfileProvider.
By default, the provider will retry three times.
Retries can be adjusted on the provider with the ```retries``` config option:
```
$provider = new InstanceProfileProvider([
'retries' => 5
]);
```
And can be disabled by setting to ```0```:
```
$provider = new InstanceProfileProvider([
'retries' => 0
]);
```

Instance profile provider retries

---

src/S3/S3Client.php
src/S3/S3ClientInterface.php

Added docblock from "Aws\S3\S3ClientInterface::getObjectUrl()" to
"Aws\S3\S3Client::getObjectUrl()"
Recent update got me a Indirect deprecation notice on my own phpunit tests inside my project that is using this library
>   1x: The "Aws\S3\S3Client::getObjectUrl()" method will require a new "array $options" argument in the next major version of its parent class "Aws\S3\S3ClientInterface", not defining it is deprecated.
>     1x in S3ManagerTest::testPutFileOnS3 from App\Manager\Tests
Resolved this notice by adding the docblock from the interface method to the object method itself.

Indirect deprecation notices fixed

---

features/smoke/sms.feature

Only smoke test SMS failure, not specific InvalidParameterException.

Update SMS Smoke Test for Failure Only

---

.travis.yml

Travis should default to Trusty (14.04).  This makes the build distribution explicit.

pin travis to trusty (14.04)

---

.changes/nextrelease/smoke_cleanup_waiter.json
tests/Integ/S3Context.php

* Add waiter to S3 integration test to prevent failed bucket deletions on cleanup.

Smoke cleanup waiter

---

tests/Build/Changelog/CurrentChangesTest.php

add documentation type for current changes test on changelog.  Fixes https://github.com/aws/aws-sdk-php/pull/1845

add documentation type for current changes test

---

.changes/nextrelease/client_region_for_web_identity_sts.json
src/ClientResolver.php
src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php
src/Credentials/CredentialProvider.php

AssumeRoleWithWebIdentityCredentialProvider should use configured region instead of 'us-east-1'.
StsClient used by AssumeRoleWithWebIdentityCredentialProvider will now respect region configured on the parent client, or the region specified in profile.

Use region for AssumeRoleWithWebIdentityCredentialProvider

---

.changes/nextrelease/fix-1877-caching-credentials.json
src/Credentials/CredentialProvider.php
tests/Credentials/CredentialProviderTest.php

Fix #1877 
Correct expires for `Credentials`.

Instantiate Credentials with expires correctly.

---

.changes/nextrelease/webidentityexceptions.json
src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php
tests/Credentials/AssumeRoleWithWebIdentityCredentialProviderTest.php

Fix #1891 
Modified existing catch block for `assumeRoleWithWebIdentity` to catch AwsExceptions, added new catch block to handle generic exceptions.

Catch generic exceptions when assuming role using web identity creds

---

.changes/nextrelease/phpunit_74_patch.json
.travis.yml
tests/bootstrap.php
tests/bootstrap/PHPUnit_Framework_MockObject_Generator_7.4.php

* Adds a test bootstrap patch for a PHPUnit class file that triggers deprecation warnings for PHP 7.4+. This is necessary because the SDK supports older versions of PHP and currently relies on older, now unsupported, versions of PHPUnit.

Phpunit 74 patch

---

composer.json

`jmespath.php` causes deprecation exceptions to be raised on PHP 7.2 or higher, and totally crashes on PHP 7.4 due to the usage of the `fn` reserved word. This is fixed in the 1.5.0 release.
---
NB There is one outstanding jmespath spec compliance issue, affecting (all versions of) the PHP library: https://github.com/jmespath/jmespath.php/issues/56.

Bumped minimum jmespath.php

---

.changes/nextrelease/guzzle7.json
.travis.yml
composer.json
src/functions.php
tests/Credentials/EcsCredentialProviderTest.php
tests/Credentials/InstanceProfileProviderTest.php
tests/RetryMiddlewareTest.php

We just released a beta of Guzzle 7 today. The [BC breaking changes](https://github.com/guzzle/guzzle/blob/master/UPGRADING.md#60-to-70) have been kept to a minimum. 
This PR allows users to use AWS SDK with Guzzle 7.

Allow Guzzle 7

---

.changes/nextrelease/default_config_file.json
src/AbstractConfigurationProvider.php
src/ClientSideMonitoring/ConfigurationProvider.php
src/EndpointDiscovery/ConfigurationProvider.php
src/S3/RegionalEndpoint/ConfigurationProvider.php
src/S3/UseArnRegion/ConfigurationProvider.php
src/Sts/RegionalEndpoints/ConfigurationProvider.php
tests/ClientSideMonitoring/ConfigurationProviderTest.php
tests/EndpointDiscovery/ConfigurationProviderTest.php
tests/S3/RegionalEndpoint/ConfigurationProviderTest.php
tests/S3/UseArnRegion/ConfigurationProviderTest.php
tests/Sts/RegionalEndpoints/ConfigurationProviderTest.php

* Adds support for the `AWS_CONFIG_FILE` environment variable to set the default config file location. This is implemented for all configuration provider classes extending `AbstractConfigurationProvider`.
Resolves #1931

Add support for AWS_CONFIG_FILE environment variable for default config file location

---

.changes/nextrelease/cloudfront_signer.json
src/CloudFront/Signer.php
tests/CloudFront/SignerTest.php

*Issue #, if available:* 
Resolves #1928 
Added logic to CF signer's construct function to allow for private keys stored as variables in addition to those stored on disk.

Load private key for cloudfront signer from variable

---

src/Credentials/CredentialProvider.php

**Description of changes:**
Very little contribution. This is about removing inaccurate documentation for `CredentialProvider::cache()` method
------

Update inaccurate documentation for CredentialProvider::cache() method

---

.travis.yml

HHVM 3.18 LTS can run both composer and PHPUnit, so it should be used to test against.

HHVM 4 doesn't support PHP anymore, as such

---

.changes/nextrelease/1953-host-style-ip-address-check.json
src/S3/S3EndpointMiddleware.php
tests/S3/S3EndpointMiddlewareTest.php

Resolves issue #1953 
We validate for host while trying to use host-style requests (we have to make sure that it's not a valid IP address)

#1953 Host validation for IP address while trying to use host-style requests

---

.changes/nextrelease/fix_invalid_debug_option
src/S3/Transfer.php
tests/S3/TransferTest.php

Hello, 
When a S3 transfer is initiated with the `debug` option set to false, an error occurs, preventing us using the library like this:
```php
$transfer = new Transfer($client, $folder, $target, [
'debug' => $output->isVeryVerbose(),
]);
```
This patch fixes this, asserting the output is a resource before writing

Fix error thrown when invalid debug option is passed

---

docs/guide/credentials.rst
src/Credentials/InstanceProfileProvider.php
tests/Credentials/InstanceProfileProviderTest.php

Correcting the name of the instance metadata service (not server).

Correct name of instance metadata service

---

.travis.yml

* Addresses newly failing builds for PHP 7.1 - 7.4
* Increase memory capacity for Travis builds
* Pins phpstan to version 0.12.11 temporarily to avoid memory issues introduced by newer versions. Should be rolled back when confirmed fixed.

Fix Travis build memory issues

---

.changes/nextrelease/abstract_crypto_impl.json
src/Crypto/DecryptionTrait.php
src/Crypto/EncryptionTrait.php

*Issue #, if available:* https://github.com/aws/aws-sdk-php/issues/1983
PHP 7.4.2 released a patch (https://bugs.php.net/bug.php?id=78776) to verify method signature of traits implementing methods for abstract classes. This is breaking breaking classes that extend `AbstractCryptoClient` and use the `EncryptionTrait` and `DecryptionTrait` traits on PHP >= `7.4.2`.
Let me know if there is anything else I can add to this change. The tests didn't even previously run for `S3EncryptionClient`, was getting:
```
PHP Fatal error:  Access level to Aws\Crypto\EncryptionTrait::encrypt() must be public (as in class Aws\Crypto\AbstractCryptoClient) in /Users/trajano/dev/aws-sdk-php/src/S3/Crypto/S3EncryptionClient.php on line 51
```
This change fixes it.
By submitting this …

fix for encrypt/decrypt implementation method signature

---

.changes/nextrelease/parition_endpoint_provider_tweak.json
src/Endpoint/PartitionEndpointProvider.php
src/data/endpoints_prefix_history.json
src/data/endpoints_prefix_history.json.php
tests/Endpoint/PartitionEndpointProviderTest.php

* Fix for partition endpoint history logic for keys with hyphens.
* Adds elastic-inference to endpoint history aliases

Elastic inference prefix change

---

.changes/nextrelease/package_builder.json
build/packager.php

Fix #2006 
Add [Symfony Polyfill / Intl: Idn](https://github.com/symfony/polyfill-intl-idn) to build as required by GuzzleHTTP version 6.5.3

Add dependency symfony/polyfill-intl-idn to build

---

.changes/nextrelease/version_update_tweaks.json
build/packager.php
build/test-phar.php
phpstan.neon
tests/bootstrap/PHPUnit_Framework_MockObject_Generator_7.4.php

* Fix failing Travis tests due to PHP warnings in static and unit tests for new versions of Guzzle and PHP 7.4.

Tweaks for Guzzle version update

---

.travis.yml

We test with Guzzle 5 on "prefer-lowest".
We test with Guzzle 6 on PHP < 7.2
We test with Guzzle 7 on PHP ≥ 7.2

Guzzle 7 is released, no beta test needed

---

.changes/nextrelease/bugfix-parse-null-timestamps.json
src/Api/DateTimeResult.php
tests/Api/Parser/JsonParserTest.php
tests/Api/Parser/XmlParserTest.php

bugfix on parsing empty timestamps

---

.changes/nextrelease/cse_wrap_name_tweak.json
src/Crypto/KmsMaterialsProviderV2.php
tests/Crypto/KmsMaterialsProviderV2Test.php
tests/S3/Crypto/S3EncryptionMultipartUploaderV2Test.php

* Tweaks the wrap algorithm name for KmsMaterialsProviderV2 for the sake of cross-SDK consistency.

Client-side encryption wrap name tweak

---

.changes/nextrelease/region_validation.json
src/ClientResolver.php
src/functions.php
tests/ClientResolverTest.php
tests/FunctionsTest.php

* Adds region validation as a valid host label when region is being used to construct an endpoint. Note this does not take effect when a custom endpoint is supplied.

Region validation

---

.github/workflows/stale_issues.yml

Lowering the ancient issue threshold from 3 years to 1. Issues can be excluded from the stale-issue-cleanup workflow by applying the `no-autoclose` label.

Reducing ancient issue threshold to 1 year

---

.changes/nextrelease/webidentity_credentialprovider.json
src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php

Fix #2014 
Clear realpath cache for web identity token file & related directories if token file fails to load. This allows the SDK to retrieve the new token file's location once the previous token file expires.

Clear expired web id token path cache

---

.changes/nextrelease/php-8-patch.json
src/Credentials/CredentialProvider.php

Fixes:
```
Error: Unknown named parameter $env
.../vendor/aws/aws-sdk-php/src/Credentials/CredentialProvider.php:124
.../vendor/aws/aws-sdk-php/src/ClientResolver.php:473
.../vendor/aws/aws-sdk-php/src/ClientResolver.php:295
.../vendor/aws/aws-sdk-php/src/AwsClient.php:199
.../vendor/aws/aws-sdk-php/src/S3/S3Client.php:328
```
---
Evidence this fix is correct: https://3v4l.org/LJchL, https://3v4l.org/IBO1U.

Fixed crash on PHP 8.0

---

CONTRIBUTING.md

It isn't clear for a newcomer that you should use Makefile command, instead of just running it via phpunit directly

CONTRIBUTING.md: Specify how to run test suite

---

.changes/nextrelease/s3_copy_source_encoding_fix.json
src/S3/MultipartCopy.php
tests/S3/ObjectCopierTest.php

Corrected urlencoding of CopySource key for S3 MultipartCopy. It was encoding it three times.
Fixed incorrect unittest.

Corrected urlencoding of CopySource key for S3 MultipartCopy

---

.changes/nextrelease/bugfix-undefined-source-index.json
src/Credentials/CredentialProvider.php

When using credential_source in default profile, source_profile is not defined. 

undefined index source_profile when using credential_source

---

.changes/nextrelease/validate-nonempty-bucket.json
src/InputValidationMiddleware.php
src/S3/S3Client.php
tests/InputValidationMiddlewareTest.php
tests/Multipart/TestUploader.php
tests/S3/BatchDeleteTest.php
tests/S3/S3ClientTest.php
tests/S3/S3EndpointMiddlewareTest.php

validate non empty bucket

---

.changes/nextrelease/enhancement-make-tests-more-strict.json
.changes/nextrelease/mockhandlerExcpetionFix.json
src/MockHandler.php
tests/MockHandlerTest.php

*Issue #2143, 
Code changes to mock exceptions, for example `S3MultipartUploadException` which extends from Exception and not `AwsException`, using the previous code will throw an exception like: `InvalidArgumentException: Expected an Aws\ResultInterface or Aws\Exception\AwsException.`

MockHandler exceptions fix

---

src/CloudFront/Signer.php

The openssl_pkey_free() function, used in PHPMailer::DKIM_Sign(), is deprecated since PHP 8.0 and may start throwing notices.
https://github.com/aws/aws-sdk-php/issues/2152
Wrap calls to openssl_pkey_free to prevent notices throw.

Wrap calls to openssl_pkey_free for PHP 8 compatibility

---

.changes/nextrelease/allow_changing_RDS_authtoken_lifetime.json
src/Rds/AuthTokenGenerator.php
tests/Rds/AuthTokenGeneratorTest.php

All the docs I can find for IAM based RDS access say tokens have a 15 minute lifetime, but I can't find a documented reason why this value couldn't be configurable, it appears to be signed using standard AWS signature version 4.
Having generated tokens manually they seem to work fine with much shorter lifetimes, which is what I would like to happen in a particular project of mine. Shorter token lifetime == a bit more secure.
Seems to be a fairly small edit to make this user adjustable.

Allow changing RDS AuthToken lifetime

---

.changes/nextrelease/bugfix-fix-empty-getenv-in-ecs-credentials-provider.json
src/Credentials/CredentialProvider.php
src/Credentials/EcsCredentialProvider.php
tests/Credentials/CredentialProviderTest.php

*Issue #2154 
Changes how env variable is taken for `EcsCredentialProvider` (non-thread safe `getenv()` to `$_SERVER`)
This fixed the issue we had on PHP script triggered by a cronjob on ECS task where `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` was available only in `$_SERVER` and `$_ENV` but not by `getenv()`.
This resulted with a different CredentialsProvider being used and failing with an error.

EcsCredentialProvider - Replace getenv() with $_SERVER

---

.changes/nextrelease/bugfix-content-type-in-lexmodelsv2.json
src/LexModelsV2/LexModelsV2Client.php
tests/LexModelsV2/LexModelsV2ClientTest.php

Added handler to update the content type of the LexModelsV2 client to 'application/x-amz-json-1.1'

bugfix to update content type in lexmodelsv2

---

.changes/nextrelease/s3-endpoint-middleware-bugfix
src/S3/BucketEndpointArnMiddleware.php
src/S3/S3EndpointMiddleware.php
src/S3Control/S3ControlEndpointMiddleware.php
tests/S3/S3EndpointMiddlewareTest.php

When the endpoint option is set the way the Uri was being generated resulted in a Uri with a blank scheme, and the scheme included in the host value.
*Issue #, if available: 2189
https://github.com/aws/aws-sdk-php/issues/2189
*Description of changes: Changed to pass host to Uri via constructor rather than generating new Uri using the withHost method.

Fix issue with s3 request uri generation

---

src/Signature/AnonymousSignature.php
src/Signature/S3SignatureV4.php
src/Signature/SignatureInterface.php
src/Signature/SignatureV4.php

Updated PHPDoc about the signatures.
The change concerns more particularly the "presign" method which can take a larger object than a simple DateTime.
Edit : I am using a DateTimeImmutable and my PHPStan detect an error on this

PHPDoc update on signature

---

composer.json

The later releases of guzzle and jmespath have had PHP7.4 compatibility issues resolved.

Update to later releases of guzzle and jmespath

---

tests/S3/S3EndpointMiddlewareTest.php

Test is breaking in LCK region due to customization on us-east-1 as a legacy global endpoint.  This PR marks this test as skipped in the LCK region

bugfix-breaking-LCK-test

---

src/Credentials/CredentialProvider.php

Improves a variable name and changes an empty() call to an isset() call in order to avoid a warning when the an array key does not exist

SSO logic enhancement

---

.changes/nextrelease/bugfix-xml-encoding.json
src/Api/Serializer/RestXmlSerializer.php
tests/Api/Serializer/RestXmlSerializerTest.php

XML encoding now encodes new line characters, apostrophes, and carriage returns

XML encoding update

---

.changes/nextrelease/remove-bad-smoke-test.json
features/smoke/devicefarm.feature

Removes a broken smoke test from device farm

removes a bad smoke test

---

src/Api/DateTimeResult.php
src/Crypto/MetadataEnvelope.php
src/DynamoDb/BinaryValue.php
src/DynamoDb/NumberValue.php
src/DynamoDb/SessionHandler.php
src/DynamoDb/SetValue.php

This PR adds the new `ReturnTypeWillChange` attribute from PHP 8.1 to several internal method overrides so these are compatible with PHP 8.1. This is similarly to how we've done it in the Laravel framework: https://github.com/laravel/framework/pull/37838
At the moment the PHP 8.1 build for the Laravel framework is failing because AWS is not yet compatible with it (understandable because it's still a while out). By merging this PR, the AWS PHP SDK will be one step closer to PHP 8.1 compatibility and we can run our own build to prepare Laravel. Now with the recent PHP 8.1 Alpha 3 being out it's a good time to start testing: https://www.php.net/archive/2021.php#2021-07-08-1
See the failing build on `laravel/framework` here: https://github.com/laravel/framework/runs/3022524466#step:7:61
PS.: …

Add ReturnTypeWillChange attribute

---

src/Api/AbstractModel.php
src/Api/DateTimeResult.php
src/CloudTrail/LogRecordIterator.php
src/Crypto/MetadataEnvelope.php
src/DynamoDb/BinaryValue.php
src/DynamoDb/NumberValue.php
src/DynamoDb/SessionHandler.php
src/DynamoDb/SetValue.php
src/HandlerList.php
src/HasDataTrait.php
src/History.php
src/LruArrayCache.php
src/MockHandler.php

This PR implements more ReturnTypeWillChange attributes where type hints were added in PHP 8.1. 
I've also moved all use imports to the more easy to use inline usage so they can be more easily removed in a future version. I should have done that in my original PR as well. This will also be consistent with Laravel and Symfony.

Implement more ReturnTypeWillChange attributes

---

.changes/nextrelease/enhancement-add-missing-phpdoc-annotations
src/Api/AbstractModel.php
src/Crypto/MetadataEnvelope.php
src/DynamoDb/SetValue.php
src/HandlerList.php
src/HasDataTrait.php
src/History.php
src/LruArrayCache.php

While upgrading to Symfony 5.4 I noticed the follow reported deprecations:
* Method `ArrayAccess::offsetExists()` might add `bool` as a native return type declaration in the future. Do the same in implementation `Aws\Api\AbstractModel` now to avoid errors or add an explicit `@return` annotation to suppress this message.
* Method `ArrayAccess::offsetExists()` might add `bool` as a native return type declaration in the future. Do the same in implementation `Aws\Endpoint\Partition` now to avoid errors or add an explicit `@return` annotation to suppress this message.
* Method `ArrayAccess::offsetGet()` might add `mixed` as a native return type declaration in the future. Do the same in implementation `Aws\Api\AbstractModel` now to avoid errors or add an explicit `@return` annotation to …

Add missing PHPDoc annotations for `ArrayAccess` and `Countable` implementations

---

.changes/nextrelease/bugfix-php81-hash_init
src/PhpHash.php

Retry of #2365 that includes required changelog document

[PHP 8.1] fixed "hash_init(): Passing null to parameter #3 ($key) of type string is deprecated

---

src/S3/ApplyChecksumMiddleware.php

*Issue #, if available:* N/A
*Description of changes:* fix PHP 7.4+ deprecation - "Passing the $glue and $pieces parameters in reverse order to implode has been deprecated since PHP 7.4"

Fix PHP 7.4+ deprecation in src/S3/ApplyChecksumMiddleware.php

---

tests/Api/ServiceTest.php

Adds missing serializer and parser creation tests for `Aws\Api\Service`

Add serializer and parser tests

---

.changes/nextrelease/ecsenvvars.json
src/Credentials/CredentialProvider.php
src/Credentials/EcsCredentialProvider.php
tests/Credentials/CredentialProviderTest.php
tests/Credentials/EcsCredentialProviderTest.php

*Issue #2323 , if available:*
Added supports for AWS_CONTAINER_CREDENTIALS_FULL_URI in EcsCredentialProvider.php, this will allows aws-php-sdk to works with CloudShell correctly. Permission in Cloudshell to follow IAM User.

Allows Cloudshell to acquire perm from AWS_CONTAINER_CREDENTIALS_FULL v2

---

tests/DynamoDb/DynamoDbClientTest.php

*Issue #, if available:* n/a
Because global state is preserved by default when running a test in a separate process, added annotation to disable this behavior for testing purposes.

chore: re-enable sessionhandler unit test

---

.changes/nextrelease/existence-methods.json
src/S3/S3ClientInterface.php
src/S3/S3ClientTrait.php
tests/S3/S3ClientTest.php

Implements #1561, closes #2342 
New object/bucket existence helper methods with changed exception handling behavior.  Previously, `false` was returned any time an exception was thrown by the underlying S3 APIs (`headObject` and `headBucket`) unless the exception's status code was >= `500` (then exception was thrown) or the exception's error code was `AccessDenied` (`true` was returned).  This was problematic because `false` could be returned in the cases of an unresolvable endpoint, expired credentials, invalid credentials, or if bucket permissions were not granted to the calling entity and resources did in fact exist.
This implementation makes fewer assumptions in cases where status codes are ambiguous, namely `403` status codes. a `403` …

feat: doesObjectExist and doesBucketExist v2

---

src/Credentials/Credentials.php

N/A
Shortening IMDS credential extensibility refresh window due to the possibility of overshooting the TTL for STS credentials proxied through a faux-IMDS endpoint.

chore: IMDS extensibility refresh window

---

.changes/nextrelease/enhancement-add-missing-phpdoc-annotation
src/CommandPool.php
src/S3/BatchDelete.php
src/S3/ObjectCopier.php
src/S3/ObjectUploader.php
src/S3/Transfer.php
src/Waiter.php

*Issue #2353*
This fixes the following deprecation produced by the Symfony PHPUnit Bridge:
```
Method "GuzzleHttp\Promise\PromisorInterface::promise()" might add "PromiseInterface" as a
native return type declaration in the future. Do the same in implementation "Aws\S3\ObjectUploader"
now to avoid errors or add an explicit @return annotation to suppress this message.
```

Add missing PHPDoc annotation for `PromiseInterface` implementations

---

src/CloudFront/Signer.php

it's not like we're using some evil __get() magic to actually do something when pkHandle is fetched?
this else looks useless.
nitpicking

nitpicking, remove useless else{}

---

composer.json

Bumping Guzzle & PSR7 to address [CVE-2022-31043](https://www.cve.org/CVERecord?id=CVE-2022-31043).  Similar changes had been made and reverted due to confusion around which advisories were being addressed. 

Bump guzzle

---

.changes/nextrelease/rus.json
README.md
composer.json
src/Script/Composer/Composer.php
src/Script/Composer/README.md
tests/Script/ComposerTest.php

**Description of changes:**
In response to requests in https://github.com/aws/aws-sdk-php/discussions/2420, https://github.com/aws/aws-sdk-php/issues/2369, https://github.com/aws/aws-sdk-php/issues/808.
A composer script which runs at pre-autoload-dump. Removes AWS services that aren't specified by the user in their `composer.json` file.  Usage is as follows:
```
"require": {
"aws/aws-sdk-php": "<version>",
},
"scripts": {
"pre-autoload-dump": "Aws\\Script\\Composer\\Composer::removeUnusedServices"
},
"extra": {
"aws/aws-sdk-php": [
"S3"
]
}
}
```
For this example, running `composer install` or `composer update` will remove all AWS services but S3. More information can be found in the [ReadMe](https://github.com/stobrien89/aws-sdk-php/tree/remove-unused-services/src/Script/Composer).
By …

feat: Remove unused services

---

tests/EventBridge/EventBridgeEndpointMiddlewareTest.php
tests/S3/BucketEndpointArnMiddlewareTest.php
tests/S3/S3EndpointMiddlewareTest.php

Removing markTestSkipped method to allow tests to run in airgapped regions.

chore: unskip LCK tests

---

src/ClientSideMonitoring/ConfigurationProvider.php
src/Credentials/CredentialProvider.php
src/DefaultsMode/ConfigurationProvider.php
src/Endpoint/UseDualstackEndpoint/ConfigurationProvider.php
src/Endpoint/UseFipsEndpoint/ConfigurationProvider.php
src/EndpointDiscovery/ConfigurationProvider.php
src/Retry/ConfigurationProvider.php
src/S3/RegionalEndpoint/ConfigurationProvider.php
src/S3/UseArnRegion/ConfigurationProvider.php
src/Sts/RegionalEndpoints/ConfigurationProvider.php

These changes are necessary to solve some deprecation notices for PHP 8.2 where `self::` is used in a callable context. This isn't supported anymore. I didn't add any tests because this should technically get a new 8.2 build. However, the 8.0 and 8.1 builds are also still pending so I figured it didn't make sense to add an 8.2 build before that PR was merged: https://github.com/aws/aws-sdk-php/pull/2403
Here's the upgrade notice: https://github.com/php/php-src/blob/PHP-8.2/UPGRADING#L157-L167
Right now, we're trying to get a passing PHP 8.2 build for Laravel. This library is one of the last blockers to get a passing build. See failures in the Laravel build:
It would be great to get a merge and a release for this @SamRemis. Thanks!

Fix self callables

---

.changes/nextrelease/ziyanli-amazon-php-master.json
src/Api/ErrorParser/JsonParserTrait.php
src/Api/ErrorParser/JsonRpcErrorParser.php
tests/Api/ErrorParser/JsonRpcErrorParserTest.php
tests/TestServiceTrait.php

As we decided to parse `AwsQuery` Compatible `Error` in the Http response header, the required changes need to take in place on both SDK client and Service. 
This will be a pre-requisite for migrating services from AWSQuery wire protocol to AWSJson.
Error code can be fetched from response content (for example __type#fooException). This PR takes another scenario into consideration, of which when `x-amzn-query-error` header with valid value is found from the Http response. 
- The parsed error code remains unchanged if this header is missing, or contains null or invalid value.
[link](https://code.amazon.com/packages/AwsDrSeps/blobs/main/--/seps/accepted/shared/query-protocol-migration-compatibility.md)
By submitting this pull request, I confirm that you can use, …

Parse Json error code if it is present in HTTP response header

---

src/S3/S3ClientInterface.php

Changes S3ClientInterface `doesObjectExistV2` to match definition on S3ClientTrait - see:
https://github.com/aws/aws-sdk-php/blob/47aa3e427371af4449cd9cb07af7209376a535bb/src/S3/S3ClientTrait.php#L317-L322

Make doesObjectExistV2 match S3ClientTrait

---

.changes/nextrelease/endpoint-patch-2.json
src/Api/Serializer/RestSerializer.php
src/S3/BucketEndpointArnMiddleware.php
src/S3Control/EndpointArnMiddleware.php

#2558, #2559
Makes `$endpointV2` params option in both endpointarn middleware and adds a strict check for `?` when appending query params.

bugfix: add fixes for #2558, #2559

---

src/Api/Serializer/RestSerializer.php

#2563
Evaluates relative path for leading `/` to account for removal of members from requestUri paths.  

bugfix: account for leading / in rest serializer

---

.changes/nextrelease/endpoint-patch.json
src/EndpointV2/EndpointV2SerializerTrait.php
tests/EndpointV2/EndpointV2SerializerTraitTest.php

#2572 
Fixes issue in Sns `subscribe` where the `Endpoint` parameter overrides an SDK-level configuration value.

bugfix: collision in endpoint command arguments

---

.changes/nextrelease/creds-extensibility-update.json
src/Credentials/Credentials.php
tests/Credentials/InstanceProfileProviderTest.php

Triggers error (error level warning) upon credentials extension rather than logging an error.

enhancement: improve credential extensibility messaging

---

README.md

*Issue #2586*
Remove links to twitter from the readme since the aws for php twitter account is not active.

fix: remove twitter from the readme 

---

.changes/nextrelease/std-lib-patch.json
src/EndpointV2/Ruleset/RulesetStandardLibrary.php

Splits arn resource Ids on both `:` and `/` delimiters rather than selecting one or the other.

bugfix: update to standard library

---

.changes/nextrelease/bucket-endpoint-patch.json
src/S3/BucketEndpointMiddleware.php
tests/S3/BucketEndpointMiddlewareTest.php

closes #2588, potentially addresses #2585
Prevents duplication of bucket in bucket endpoint path.  Additionally, users will need to be more explicit about what type of endpoint they expect when using the `bucket_endpoint` customization — with EndpointV2 resolution custom endpoints _must_ be passed to the provider, which means a bucket name is always prepended to the hostname unless `use_path_style_endpoint` is set to a value of `true`. 

bugfix: duplicated bucket in bucket endpoint path

---

.changes/nextrelease/restserializer-patch.json
src/Api/Serializer/RestSerializer.php
src/S3/S3Client.php
tests/S3/S3ClientTest.php

Handles cases when there is an empty request path, but a non-empty query. This is a non-issue with standard signing, but resolves an issue with calculating SigV4A signatures and reflects legacy endpoint resolution behavior prior to S3 model processing.

bugfix: S3 query patch

---

.changes/nextrelease/nextrelease.json
src/S3/S3Client.php

#2615 
Update to `bucket_endpoint` documentation which lets users know they'll need to be more explicit about the type of endpoint they expect after Endpoints 2.0 changes.

enhancement: update bucket_endpoint documentation

---

.changes/nextrelease/nextrelease.json
src/Api/DocModel.php
src/S3/S3Client.php

closes #2304, addresses #2256
Restores `PutObject` and `UploadPart` `ContentMD5` documentation, removes note that states "the value will be computed on your behalf" from operations where `ContentMD5` is required. 
S3 already includes a note that states SDKs will compute the MD5 for operations that require it. This is visible in our api docs.  Example: https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#putbucketacl. 
The S3 `ContentMD5` docs for `UploadPart`: 
```
The base64-encoded 128-bit MD5 digest of the part data. This parameter is auto-populated when using the command from the CLI. This parameter is required if object lock parameters are specified.
```
The S3 `ContentMD5` docs for `PutObject`:
```
The …
```

enhancement: update S3 ContentMD5 documentation

---

.changes/nextrelease/nextrelease.json
src/EndpointV2/EndpointV2SerializerTrait.php
tests/EndpointV2/EndpointProviderV2Test.php
tests/EndpointV2/EndpointV2SerializerTraitTest.php
tests/EndpointV2/invalid-rules/invalid-scheme.json

Adds fix to account for `signingRegionSet` field yielded by a `sigv4a` auth scheme. 

Bugfix: EndpointV2 sigv4a tests

---

.changes/nextrelease/nextrelease.json
src/S3/ApplyChecksumMiddleware.php
src/S3/MultipartUploader.php
src/S3/ObjectUploader.php
src/S3/S3Client.php
src/S3/Transfer.php
tests/S3/MultipartUploaderTest.php
tests/S3/ObjectUploaderTest.php
tests/S3/S3ClientTest.php
tests/S3/TransferTest.php

Closes #2256 
Adds `AddContentMD5` parameter, which allows ApplyChecksumMiddleware to compute MD5 checksums for `PutObject` and `UploadPart`.  Additionally, the ObjectLoader, MultiPartUploader and the Transfer utility will now accept an option of `add_content_md5`, which when set to `true` will have the MD5 checksum calculated by ApplyChecksumMiddleware.

bugfix: add ability to calculate ContentMD5 for PutObject and UploadPart

---

.changes/nextrelease/enhancement-sso-updates.json
src/Credentials/CredentialProvider.php
src/Script/Composer/Composer.php
src/Token/ParsesIniTrait.php
src/Token/SsoTokenProvider.php
tests/Credentials/CredentialProviderTest.php
tests/Script/ComposerTest.php
tests/Token/SsoTokenProviderTest.php

sso improvements

---

.changes/nextrelease/fix-integ-tests.json
behat.yml
features/s3/postObject.feature
features/s3Encryption/encryption.feature
features/s3EncryptionV2/encryptionV2.feature
src/Crypto/EncryptionTraitV2.php
tests/Integ/NativeStreamContext.php
tests/Integ/S3Context.php
tests/Integ/S3EncryptionContext.php
tests/Integ/S3EncryptionContextV2.php

Updates crypto test resources, removes deprecated block cipher uploads, switches `S3EncryptionClient` to `S3EncryptionClientV2`.  Same with the KMS materials provider.  Switches `PostObjectV4` test to bucket owner read permissions, removes test for deprecated `PostObjectV2`.

bugfix: fix integ tests

---

.changes/nextrelease/signature-provider-fix.json
src/Signature/SignatureProvider.php
tests/Signature/SignatureProviderTest.php

Previously, sigv4a was determined in the s3 signer by looking for an mrap identifier.  With dynamic endpoint resolution, sigv4a can be specified beforehand, leading to the incorrect signer being selected for s3 sigv4a.  This results in the content-sha256 header (which is required for all s3 payloads) not being added to the request.

bugfix: signature provider when sigv4a is specified

---

src/Crypto/EncryptionTrait.php

changed the default value to empty string for getting rid of deprecation warning on openssl_encrypt using PHP 8.1

Set default to empty string (fix PHP 8.1 deprecation warnings)

---

.github/workflows/closed-issue-message.yml
.github/workflows/stale_issues.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

src/S3/MultipartCopy.php
src/S3/ObjectCopier.php
tests/S3/ObjectCopierTest.php

*Issue  2299*
S3 client fails to copy when the source bucket is specified through an access point arn, and this is caused because the path of the object specified should contain "/object/" in between the generated bucket url and the object to be copied, and the current implementation does not have this special handling. To fix this behavior I added a condition in the function that generates the source path, where I validate if is an access point then I add the "/object/" part to the path to be returned.

fix: Copy file fails when bucket is an access point arn

---

src/Endpoint/Partition.php
tests/Endpoint/PartitionTest.php

Allows boolean values to be passed for `use_fips_endpoint` and `use_dual_stack_endpoint` Partition config.  This code path can be reached when instantiating a PartitionEndpointProvider.  Use case here is to bypass dynamic endpoint resolution for testing purposes while also being able to use endpoint variants. 

enhancement: update partition to accept boolean values for variants

---

src/MockHandler.php
tests/MockHandlerTest.php

`count()` on empty MockHandler results in error
```php
count(): Parameter must be an array or an object that implements Countable
```
```shell
vendor/bin/phpunit --filter=MockHandlerTest
PHPUnit 9.5.25 #StandWithUkraine
Warning:       No code coverage driver available
..E......                                                           9 / 9 (100%)
Time: 00:00.266, Memory: 54.00 MB
There was 1 error:
1) Aws\Test\MockHandlerTest::testCanCountEmpty
count(): Parameter must be an array or an object that implements Countable
```
Initialise `$this->queue` as empty array when MockHandler instantiates.

Fix count() empty MockHandler

---

src/Api/TimestampShape.php
tests/Api/TimestampShapeTest.php

By checking `DateTimeInterface` instead of `DateTime`.
DateTimeInterface was added in PHP 5.5, which is the minimum PHP version
the SDK supports.
I couldn't find any, but there are a few closed PRs around this https://github.com/aws/aws-sdk-php/pull/422

Support DateTimeImmutable in Timestamp API Fields

---

.changes/nextrelease/streamwrapper-acl.json
composer.json
src/S3/StreamWrapper.php
tests/Crypto/RandomByteStream.php
tests/S3/StreamWrapperPathStyleTest.php
tests/S3/StreamWrapperTest.php
tests/S3/StreamWrapperV2ExistenceTest.php

#2674 
Unsets ACL param when calling `createBucket` from S3StreamWrapper.  Starting this month, all new S3 buckets automatically enable BPA upon creation, meaning the only valid ACL option upon creation is `private`.  This is automatically handled on the S3 side.

bugfix: ACL on bucket creation in S3 Streamwrapper

---

.changes/nextrelease/http-message-fix.json
composer.json

Takes explicit dependency on `psr/http-message`, which prevents resolution to incompatible versions.

Take dependency on http-message ^1.0

---

src/S3/S3Client.php
tests/S3/S3ClientTest.php

When getting http 40x error and using the standard retry strategy, the 40x error was being retried when this type of error should not be retried, because it could lead to a loop, causing a huge number of retries that will never succeed. This behavior was caused by the way how the conditions were defined in the retry decider logic, that was overridden the decision of not retry this type of error. For reference check and compare the changes.
*Issue #2650, #2496, P85307087*
Fix the condition that prevent http 40x errors from not being retried.

fix: standard retry retries on 40x errors

---

tests/Api/ShapeTest.php
tests/ClientSideMonitoring/ApiCallAttemptMonitoringMiddlewareTest.php
tests/ClientSideMonitoring/ApiCallMonitoringMiddlewareTest.php
tests/ClientSideMonitoring/ConfigurationProviderTest.php
tests/Credentials/CredentialProviderTest.php
tests/Endpoint/UseDualstackEndpoint/ConfigurationProviderTest.php
tests/Endpoint/UseFipsEndpoint/ConfigurationProviderTest.php
tests/EndpointDiscovery/ConfigurationProviderTest.php
tests/EndpointDiscovery/EndpointDiscoveryMiddlewareTest.php
tests/S3/UseArnRegion/ConfigurationProviderTest.php

Fixes PHPUnit warnings for invalid annotations.

chore: update invalid covers annotations

---

build/build-manifest.php
src/data/cloudsearchdomain/2013-01-01/api-2.json
src/data/entitlement.marketplace/2017-01-11/api-2.json
src/data/importexport/2010-06-01/api-2.json
src/data/mobile/2017-07-01/api-2.json

Sync out-of-date models without the `serviceId` attribute.  Additionally adds a `config` option to the manifest file for per-service endpoint url config.

chore: update models without serviceid, add config to manifest

---

.changes/nextrelease/feature-default-version.json
src/ClientResolver.php
tests/ClientResolverTest.php

Use `latest` as default version

---

Makefile

Temporarily unsets `AWS_REGION` when running unit tests.

bugfix: unset aws_region during unit tests

---

src/Crypto/Polyfill/ByteArray.php
src/EndpointV2/Ruleset/RulesetStandardLibrary.php
tests/Endpoint/UseDualstackEndpoint/ConfigurationProviderTest.php

Fixes deprecation warnings related to passing null as an argument to `strpos` and `parseurl`.

enhancement: address deprecation warnings

---

README.md

After August 15, 2023, AWS SDK for PHP will not longer support PHP versions 7.2.4 and below, and therefore we are updating our documentation to reflect the new minimum PHP version required, that is PHP 7.2.5.
*Issue #2799*

chore: update documentation to reflect php support

---

tests/Integ/BatchingContext.php

Suppresses warning which causes integ test to fail.

bugfix: update batching integ

---

.changes/nextrelease/disable-imdsv1.json
src/Credentials/InstanceProfileProvider.php
tests/Credentials/InstanceProfileProviderTest.php

Right now IMDSv1 fallback is enabled by default, but this implementation allows customer to decided whether or not they want this behavior when using the InstanceProfileProvider. Here is how this can be set:
- Explicit configuration: $provider = new InstanceProfileProvider(['ec2_metadata_v1_disabled' => true|false]);
- Environment variable: AWS_EC2_METADATA_V1_DISABLED set to true or false
- Config file. Example: [default] ec2_metadata_v1_disabled=true|false
Add a function that resolves for whether or not we should fallback to IMDSv1.

feat: add option to make IMDSv1 fallback optional

---

.changes/nextrelease/remove-sqs-middleware.json
src/Sqs/SqsClient.php
tests/Sqs/SqsClientTest.php

Closes #2822 
Removes SQS queue url middleware, which replaced the base url with the queue url, when `QueueUrl` was provided.  Because SQS has migrated to JSON protocol, this is now being handled by SQS using the `QueueUrl` value provided in the JSON payload.

bugfix: remove queueurl middleware

---

.changes/nextrelease/sqs-response-middleware.json
src/Sqs/SqsClient.php
tests/Sqs/SqsClientTest.php

Closes #2827
Updates validation of response MD5s.  If the value for `MessageAttributes` is empty, do not expect an MD5.  `SqsClient::calculateMessageAttributesMd5` returns `null` on an empty value anyway.

enhancement: sqs response md5 validation

---

.changes/nextrelease/cloudfront-signed-urls.json
src/CloudFront/Signer.php

See #2608
On recent RHEL/RockyLinux/Alma 9 the default system security policies disable SHA-1 in OpenSSL.
This cause `CloudFrontClient` to silently fail signature generation in `getSignedUrl` and generate an URL with empty signature.
I've added a check for empty signature and an exception with OpenSSL errors to help to identify the issue.
I'd like to add a test but I'm struggling to find a way to dynamically disable the algorithm during unit tests, any suggestion is welcome.

[CloudFront] Add exception when signature generation fails

---

src/Api/DocModel.php

Since PHP 8.2 the syntax "${var}" is deprecated.
"{$var}" should be used instead.
PHPCompatibility detected the following issues with PHP 8.2:
```
FILE: /.../aws/aws-sdk-php/src/Api/DocModel.php
--------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
--------------------------------------------------------------------------------------------------------
93 | WARNING | Using ${var} in strings is deprecated since PHP 8.2, use {$var} instead. Found: ${ref}
|         | (PHPCompatibility.TextStrings.RemovedDollarBraceStringEmbeds.DeprecatedVariableSyntax)
94 | WARNING | Using ${var} in strings is deprecated since PHP 8.2, use {$var} instead. Found: ${ref}
|         | …
```

Fix deprecated use of ${var} in DocModel.php

---

src/ClientSideMonitoring/AbstractMonitoringMiddleware.php

https://github.com/aws/aws-sdk-php/issues/2527
In PHP v8 on, Sockets are now classes instead of resources. This PR fixes the PHP v8 compatibility issue in this library.

Switch resource check to class check for PHP v8 compatibility

---

.changes/nextrelease/feat-imds-custom-endpoint-support.json
src/Credentials/CredentialsUtils.php
src/Credentials/EcsCredentialProvider.php
src/Credentials/InstanceProfileProvider.php
tests/Credentials/CredentialsTest.php
tests/Credentials/CredentialsUtilsTest.php
tests/Credentials/InstanceProfileProviderTest.php

When using IMDS for fetching credentials, customers should be able to provide their custom endpoint when desired, and that is what this change does. Basically, customer can provide a custom endpoint by doing one of the following options: Please note that a valid URI value needs to be provided, otherwise a credential exception will be thrown.
- Providing a parameter called 'ec2_metadata_service_endpoint' to the constructor of the InstanceProfileProvider.
- By setting an environment variable called AWS_EC2_METADATA_SERVICE_ENDPOINT.
- By defining a key-value config in the config file ~/.aws/config
*Issue #2847*

feat: IMDS support for providing custom endpoint

---

src/ClientSideMonitoring/AbstractMonitoringMiddleware.php

To prevent check errors in PHP versions below to 8, I am changing the check for if self::$socket is an instance of \Socket by using dynamic class name instead of direct reference.

fix: use dynamic class name instead of reference

---

.changes/nextrelease/configure-presigned-urls.json
Makefile
src/AwsClient.php
src/ClientResolver.php
tests/AwsClientTest.php
tests/ClientResolverTest.php

Fixes issue with configured endpoint urls when used during presigning.

bugfix: presigned configured urls

---

tests/Api/test_cases/protocols/output/json.json

Adds protocol test case to ensure the `__type` field is ignored during union type deserialization.  

chore: add protocol test case for ignoring __type during union deserialization

---

.changes/nextrelease/auth-scheme-update.json
src/Auth/Exception/UnresolvedAuthSchemeException.php
src/EndpointV2/EndpointV2Middleware.php
tests/EndpointV2/EndpointProviderV2Test.php
tests/EndpointV2/EndpointV2MiddlewareTest.php
tests/EndpointV2/EndpointV2SerializerTraitTest.php
tests/Identity/S3Express/S3ExpressIdentityProviderTest.php

Updates to auth scheme resolution, which allows for multiple auth schemes to be modeled in priority order.  For example, a service might prioritize `sigv4a`, which requires the `awscrt` extension, but list `sigv4` as a fallback.  

enhancement: update auth scheme resolution

---

tests/S3/BucketEndpointArnMiddlewareTest.php

With the possibility of multiple auth schemes (with v4a using a region set) for outposts, assertions on the region being present in the auth string are no longer valid. 

chore: update outposts tests

---

src/Credentials/InstanceProfileProvider.php
tests/Credentials/InstanceProfileProviderTest.php

This change makes the ConfigurationResolver to load configuration from aws shared config files based on the configuration `use_aws_shared_config_files` either provided as provider arguments or as service client arguments.
*Issue #2887*

fix: set use_aws_shared_config_files opts-in

---

features/smoke/dynamodbstreams.feature

Updates test to account for exception change from ddb-streams.  Unknown if this change is intended from the ddb-streams side, but behavior is confirmed to be consistent regardless of account used.  The example stream arn used in the test is sourced from the [DescribeStream documentation](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_DescribeStream.html#API_streams_DescribeStream_Example_1_Request).

update ddb-streams smoke test

---

.changes/nextrelease/configured-signature-version.json
src/AwsClient.php
src/ClientResolver.php
tests/AwsClientTest.php

closes #2912 
Fixes issue with manually configured signature versions being overridden by signature versions resolved with a service endpoint.

bugfix: configured signature versions

---

.changes/nextrelease/json-rpc-streaming-support.json
src/Api/Parser/DecodingEventStreamIterator.php
src/Api/Parser/EventParsingIterator.php
src/Api/Parser/JsonRpcParser.php
src/Api/Parser/NonSeekableStreamDecodingEventStreamIterator.php
src/CloudWatchLogs/CloudWatchLogsClient.php
tests/Api/Parser/EventParsingIteratorTest.php
tests/Api/Parser/JsonRpcParserTest.php
tests/Api/Parser/NonSeekableStreamDecodingEventStreamIteratorTest.php
tests/CloudWatchLogs/CloudWatchLogsClientTest.php

Add event streaming capabilities on the JSON RPC parser, so that operations such as StartLiveTail from CloudwatchLogs are properly handled/parsed. This change also includes an extension of the DecodingEventStreamIterator for handling streamable responses where the stream as response is not seekable, and a handling for when the `event-type` is `initial-response

feat: add streaming support on JSON RPC parser

---

.changes/nextrelease/fix-clear-cached-path-ecs.json
src/Credentials/EcsCredentialProvider.php

fix: clear cached path for ECS auth token file

---

build/docs/.phpdoc/template/components/summary.html.twig

Updates condition for inserting api versions table on client documentation pages: currently missing from [Lambda](https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Lambda.LambdaClient.html) and some other legacy services.  This is an example of how the page should look: https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.AccessAnalyzer.AccessAnalyzerClient.html

bugfix: update summary condition

---

.changes/nextrelease/multi-auth.json
phpunit.xml.dist
src/Auth/AuthSchemeResolver.php
src/Auth/AuthSchemeResolverInterface.php
src/Auth/AuthSelectionMiddleware.php
src/AwsClient.php
src/ClientResolver.php
src/Command.php
src/Credentials/Credentials.php
src/EndpointV2/EndpointV2Middleware.php
src/Identity/AwsCredentialIdentity.php
src/Identity/BearerTokenIdentity.php
src/Identity/IdentityInterface.php
src/Identity/S3/S3ExpressIdentityProvider.php
src/S3/ApplyChecksumMiddleware.php
src/S3/S3Client.php
src/Token/SsoTokenProvider.php
src/Token/Token.php
tests/Auth/AuthSchemeResolverTest.php
tests/Auth/AuthSelectionMiddlewareTest.php
tests/AwsClientTest.php
tests/ClientResolverTest.php
tests/CommandTest.php
tests/Credentials/CredentialsTest.php
tests/EndpointV2/EndpointProviderV2Test.php
tests/EndpointV2/EndpointV2MiddlewareTest.php
tests/Token/SsoTokenProviderTest.php
tests/Token/TokenProviderTest.php
tests/Token/TokenTest.php

**Description of changes**:
Adds support for the service and operation-level auth trait, which allows a service to model multiple signature versions. When modeled, this trait will contain a non-empty priority-ordered list of signature versions to select from.  Selection is dependent on a few different factors: e.g. `v4a` signatures require installation of the crt extension; `bearer` signatures require that you are using bearer token credentials.  Selection will be performed on a per-request basis, with the operation-level modeled `auth` taking precedence over the service level modeled `auth`.

feat: multi-auth

---

.changes/nextrelease/multi-auth-update.json
src/Command.php
src/EndpointV2/EndpointV2Middleware.php
tests/CommandTest.php

#2937 
Removes suppressed call to a deprecated method.  Lowers error level of deprecated call to `E_USER_WARNING`.

bugfix: update deprecated command methods

---

.changes/nextrelease/fix-ec2-empty-list-serialization.json
src/Api/Serializer/Ec2ParamBuilder.php
tests/Ec2/Ec2ClientTest.php

Empty list parameters should not be serialized when doing EC2 requests, instead the parameters must be ignored. Otherwise, the service will return an InvalidRequest exception

fix: EC2 empty list serialization

---

Makefile
build/remove-method-annotations.php

Removes `@method` annotations on client classes prior to doc generation.  The documentation generated by these methods does not provide useful information— service methods are documented in their respective api version pages.

enhancement: stop service method generation on client classes

---

src/Script/Composer/Composer.php
src/Script/Composer/README.md

Before people always to removing those unused services in any environments, If they miss some services that they are still using, that will cause some risks.
Now you can use the `onlyRemoveUnusedServicesInDev` method to avoid the risks.

feat: Support removing unused services only in dev environment

---

src/Credentials/Credentials.php

**trim(): Passing null to parameter # 1 ($string) of type string is deprecated on Credentials.php**
A casting to string was applied to ensure this type is been used in trim function.
The behavior keeps the same on [older versions of php](https://onlinephp.io/c/dc989) (no break changes). 
[Reference](https://stackoverflow.com/questions/71707325/migration-to-php-8-1-how-to-fix-deprecated-passing-null-to-parameter-error-r)

enhancement: treat php >=8.1 deprecation warning on Credentials.php

---

.changes/nextrelease/feat-urldecode-location.json
src/S3/PutObjectUrlMiddleware.php
tests/S3/ObjectCopierTest.php
tests/S3/PutObjectUrlMiddlewareTest.php

When using the multipart upload option, for larger files, the returned Url in the Location parameter from CompleteMultipartUploadResponse, this URL comes with special characters due to its encoding, and therefore a decoding is needed so the URL is returned in a better readable way to the end user.
*Issue #2933*

feat: decoded encoded URLs

---

.github/workflows/tests.yml
composer.json

The [earlier changes](https://github.com/aws/aws-sdk-php/commit/d550c5e7f704f155fca85e1be52898c1b1407c7f) were silently included without an explanation and have important consequences for everyone else who uses Guzzle for reasons unrelated to this SDK. This may result in people simply not upgrading to the newer version of the SDK, or worse, cause downgrades to Guzzle. Only Guzzle 7.9.x is currently supported for security fixes. None of the versions of Guzzle you currently allow are supported. It's important that people can use Guzzle 7.9.x.

Revert bad changes to Guzzle version constraints

---

composer.json

Some static analysis tools have to scan the dependencies of the project. That includes walking through each autoloaded file of each package.
PHP files in `src/data` don't declare any usable symbols, so skipping those improves build times.
Tools like [ComposerRequireChecker](https://github.com/maglnet/ComposerRequireChecker) rely on `exclude-from-classmap` to improve the search time.
----

composer: exclude src/data from classmaps

---

.changes/nextrelease/expires-customization.json
src/Api/Service.php
src/InputValidationMiddleware.php
src/S3/ExpiresParsingMiddleware.php
src/S3/S3Client.php
tests/Api/ServiceTest.php
tests/S3/ExpiresParsingMiddlewareTest.php
tests/S3/S3ClientTest.php

S3 will soon be changing the `Expires` shape type to `string` due to inconsistencies in handling of timestamp formats.  We will be modifying the S3 model to keep `Expires` type as `timestamp` for backward compatibility.  We will also be adding a new shape to output structures which contain `Expires`: `ExpiresString`.  This will be the unparsed (into timestamp) string format of the `expires` header.

feat: s3 expires customization

---

src/S3/S3MultiRegionClient.php

*Issue: None
This tiny change will make it possible to sign pre-signed-requests with optional parameters, this can be used to make use of this part of the code:
https://github.com/aws/aws-sdk-php/blob/725492580ef8a49108e39803dc266c25faa30d5a/src/Signature/SignatureV4.php#L169-L171
This wil make it possible to sign the S3 links with a timestamp in the past!
This is very handy if you want to make use of short caching.
Without the options, every signed url will have an unique signature, because time() function is used.
Found here:
https://github.com/clauculo/aws-sdk-php/blob/725492580ef8a49108e39803dc266c25faa30d5a/src/Signature/SignatureV4.php#L171
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …

Add options to createPresignedRequest method

---

.changes/nextrelease/enhancement-add-phpdoc-doctrine-cache
src/DoctrineCacheAdapter.php

This fixes the following deprecations produced by Symfony:
* User Deprecated: Method `Doctrine\Common\Cache\Cache::fetch()` might add `mixed` as a native return type declaration in the future. Do the same in implementation `Aws\DoctrineCacheAdapter` now to avoid errors or add an explicit `@return` annotation to suppress this message.
* User Deprecated: Method `Doctrine\Common\Cache\Cache::save()` might add `bool` as a native return type declaration in the future. Do the same in implementation `Aws\DoctrineCacheAdapter` now to avoid errors or add an explicit `@return` annotation to suppress this message.
* User Deprecated: Method `Doctrine\Common\Cache\Cache::delete()` might add `bool` as a native return type declaration in the future. Do the same in implementation …

Add missing PHPDoc annotation for Doctrine Cache implementations

---

src/ClientResolver.php

This is a simple fix to the use the env variable when it's set because it's fetching from `$_SERVER`

fix: env variable usage of `AWS_SUPPRESS_PHP_DEPRECATION_WARNING`

---

.changes/nextrelease/fix-waiter-matcher-boolean.json
src/Waiter.php
tests/WaiterTest.php

When the expected value from acceptor is a boolean then, the matcher should:
- if expected is true then an error should be matched.
- if expected is false then no error should has been occurred.

fix: error matcher on booleans

---

.changes/nextrelease/creds-unserialize.json
src/Credentials/Credentials.php
tests/Credentials/CredentialsTest.php

https://github.com/aws/aws-sdk-php/pull/2884#discussion_r1743974113
Fixes issue where previously cached credentials may fail to unserialize due to missing `accountId` property.

bugfix: unserialize accountid

---

.changes/nextrelease/s3-locationconstraint.json
src/S3/S3Client.php
tests/S3/S3ClientTest.php

**Description of changes:**
Updates middleware to skip directory buckets (`LocationRestraint` is not supported) and fixes a long-running bug where the middleware would override previously configured `CreateBucketConfiguration`. See https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateBucket.html#AmazonS3-CreateBucket-request-LocationConstraint

bugfix: LocationConstraint middleware

---

features/smoke/autoscaling.feature

Remove smoke test for CreateLaunchConfiguration operation since it is not supported. Please see: https://docs.aws.amazon.com/autoscaling/ec2/userguide/migrate-to-launch-templates.html

enhancement: remove smoke test for autoscaling

---

.changes/3.135.2
.changes/3.138.5
.changes/3.150.1
.changes/3.154.5
.changes/3.158.20
.changes/3.164.0
.changes/3.172.4
.changes/3.174.0
.changes/3.181.0
.changes/3.193.4
.changes/3.199.0
.changes/3.204.3
.changes/3.212.7
.changes/3.241.1
.changes/3.248.0
CHANGELOG.md
tests/Integ/CrtContext.php

Removes erroneously published changelog entries/references for `TranscribeStreaming`, which is not supported by the SDK.

chore: remove references to TranscribeStreaming

---

src/Api/Parser/DecodingEventStreamIterator.php
src/Api/Parser/EventParsingIterator.php
src/ResultPaginator.php

Addresses: https://github.com/aws/aws-sdk-php/issues/2665
Some SDK classes implement only some parts of the `Iterator` interface, causing warnings for customers that are using PHP version 7.x. Adding return type annotations help mitigate those warnings.

adding return annotations to supress warnings

---

features/smoke/marketplacecommerceanalytics.feature
tests/Integ/SmokeContext.php

Skip SubscriptionRequired exceptions for Marketplace Commerce Analytics service.

chore: skip SubscriptionRequired exceptions

---

.changes/nextrelease/query-mode-header.json
src/AwsClient.php
tests/AwsClientTest.php

Adds opt-in header `x-amzn-query-mode` for query-compatible services (that have migrated to json or another protocol).

chore: add query mode header

---

.changes/nextrelease/simple-cache.json
composer.json

I don't think i need to create an issue for this.
I need this change when peer-dependencies require different version of the `psr/simple-cache` package.
In my case, the package `mobiledetect/mobiledetectlib` require version 3. Since these versions do not change public interface (only type safety was added) i think it is safe to allow this.

Add support for psr/simple-cache v2 and v3

---

.changes/nextrelease/generic-method-for-config-resolve.json
src/ClientResolver.php
tests/ClientResolverTest.php

Honor the `use_aws_shared_config_files` config from `default_region` and `default_sigv4a_signing_region_set` by passing `$args` along to the `ConfigurationResolver::resolve` call.
*Issue #3026*

fix: honor use_aws_shared_config_files

---

CHANGELOG.md

Update changelong for `3.324.6 - 2024-10-18` with a more detailed breaking change message for the Athena service model change.

chore: update changelong with breaking change

---

src/ClientResolver.php
src/UserAgentMiddleware.php
tests/UserAgentMiddlewareTest.php

This change is needed because the parameter `endpoint` will always be populated even if a value was not provided at client construction, and therefore we can not relay on it to determine its source.

fix: add endpoint override flag

---

src/Credentials/EcsCredentialProvider.php
tests/Credentials/EcsCredentialProviderTest.php

*Issue #3056*
In order to support account id endpoint resolution on ECS when ECS does not return an AccountId field as part of its response. What is being done in this change is trying to populate the AccountId field from the RoleArn returned in the response.

fix: account_id resolution in ecs

---

.changes/nextrelease/8-deprecation.json
.github/workflows/docs-build.yml
.github/workflows/tests.yml
composer.json
phpstan.neon
src/functions.php
tests/CloudFront/SignerTest.php

Deprecates PHP versions 8.0.x and below.  Adds support for PHP 8.4.

feat: 8.0.x deprecation

---

src/EndpointV2/EndpointProviderV2.php
src/EndpointV2/EndpointV2Middleware.php
src/MetricsBuilder.php
src/UserAgentMiddleware.php
tests/UserAgentMiddlewareTest.php

- Captures the AccountIdEndpointMode metric just if the parameter is defined in the ruleset.
- Captures the account id endpoint metric whenever an account id endpoint was resolved by the endpoint middleware.

fix: account id endpoint metric

---

.changes/nextrelease/update-token-generator.json
src/DSQL/AuthTokenGenerator.php
tests/DSQL/AuthTokenGeneratorTest.php

Updates default expiration time from 700 to 900 seconds.

chore: update auth token generator default expiry time

---

.changes/nextrelease/sso-expires-fix.json
src/Credentials/CredentialProvider.php
tests/Credentials/CredentialProviderTest.php

Fixes #3063 
Updates handling of expiration value sent from the `SSO` service, which returns epoch milliseconds.  Converts to epoch seconds, which is what the `Credentials` class expects.

bugfix: sso provider expiration

---

.changes/nextrelease/sigv4a-headers.json
src/Signature/SignatureV4.php
tests/Signature/SignatureV4Test.php

Adds `transfer-encoding` to list of headers to be removed prior to v4a signing.

chore: update illegal v4a headers

---

.changes/nextrelease/remove-paragonie-random_compat-dev-dependency.json
composer.json

#3020
Removing the paragonie/random_compat dev dependency, because it is unnecessary, given the fact that the AWS SDK requires PHP 7.2. PHP 7.0+ guarantees the existence of the CSPRNG.
This cleans up the list of dependencies and reduces unnecessary network traffic.

feat: remove paragonie/random_compat dev dependency

---

.changes/nextrelease/auth-selection.json
src/Auth/AuthSchemeResolver.php
tests/Auth/AuthSchemeResolverTest.php

Adds exception handling for when an invalid (or no) identity is resolved.  For example, if no credentials are provided and no credential sources are found, an exception will be thrown from the instance profile provider- the last provider in the default chain.  If, for this same client, someone provided a bearer token and the service supported bearer auth, the `AuthSchemeResolver` should be able to fall back to this auth scheme.  These changes make that possible

bugfix: auth fallbacks

---

.github/workflows/handle-stale-discussions.yml

N/A
Running this GHA on forked repos will most likely fail and we should prevent this from happening.

chore: run GHA HandleStaleDiscussions only on aws repo

---

.changes/nextrelease/auth-selection.json
.changes/nextrelease/endpoint-arn-updates.json
src/S3Control/S3ControlClient.php
tests/S3Control/EndpointArnMiddlewareTest.php
tests/S3Control/S3ControlClientTest.php
tests/S3Control/S3ControlTestingTrait.php

Disables `EndpointArnMiddleware` when the (newer) dynamic endpoint provider is in use.  This middleware used to handle endpoint construction for arns provided to the `S3ControlClient`, but it is no longer necessary or useful when `EndpointProviderV2` is in use.

chore: endpoint arn middleware updates

---

.changes/.nextrelease/fix-duplicate-metrics-middleware.json
src/HandlerList.php
src/MetricsBuilder.php
tests/MetricsBuilderTest.php

*Issue #3086*
- Prevent adding the same metrics middleware multiple times.

fix: prevent duplicating metrics middleware

---

.changes/nextrelease/protocol-selection.json
src/Api/Service.php
src/Api/SupportedProtocols.php
tests/Api/ServiceTest.php
tests/Api/SupportedProtocolsTest.php

Adds protocol selection behavior for services that specify the `protocols` field.  The protocols field is a non-empty array of priority-ordered service protocols. The SDK will select the first compatible protocol, or fall back to the `protocol` field if it is set and no compatible protocols are found.

feat: protocol selection

---

build/Burgomaster.php

Implicitly nullable parameter types are deprecated in PHP 8.4
https://www.php.net/manual/it/migration84.deprecated.php#migration84.deprecated.core.implicitly-nullable-parameter

Make nullable parameter explicity nullable for PHP 8.4

---

.changes/.nextrelease/feature-progress-tracker.json
.changes/nextrelease/fix-waiter-matchers.json
src/Waiter.php
tests/WaiterTest.php

- Makes matchesPath to return false when the result value does not match the same value and type as the expected value.
- Makes matchesPathAll to return false when an empty array or a non-array value is resolved by the jmespath evaluator.
- Makes matchesPathAny to return false when a non-array value is resolved by the jmespath evaluator.
This change also refactor the test case providers so that they are more idiomatic by naming them.

fix: adjust waiter matchers

---

.changes/nextrelease/fix-skip-non-seekable-responses.json
src/S3/Parser/S3Parser.php
tests/S3/Parser/S3ParserTest.php

Prevent 200 errors parsing in responses where its body stream is not seekable. By specification streamable operations should be skipped.

fix: prevent 200 error parsing

---

features/smoke/geoplaces.feature

Removes smoke test which suddenly started throwing `AccessDeniedException`s instead of the expected `ValidationException`.

chore: remove geoplaces smoke test

---

src/MockHandler.php

In this pull request, I have updated the PHPDoc return type to explicitly include `null`, reflecting that the function may return `null` in certain cases. This change helps to avoid raising PHPStan error `method.impossibleType` when asserting that the last request was `null`.

Changing the return type of getLastRequest to include null

---

.changes/nextrelease/auth-selection-updates.json
src/Auth/AuthSelectionMiddleware.php
tests/Auth/AuthSelectionMiddlewareTest.php

Closes #3105, #3097 
Update which swallows exception in the event of credential retrieval errors during auth selection.  Credentials may not always be available during this stage in the request lifecycle.

enhancement: treat credential retrieval failures as non-terminal during auth selection

---

.changes/nextrelease/fix-query-header-mode.json
src/AwsClient.php
tests/AwsClientTest.php
tests/Integ/CredentialsContext.php

This change makes the `x-amzn-query-mode` header to be a string value instead of a boolean one.

fix: fix x-amzn-query-mode header

---

CONTRIBUTING.md

Under "Feature Requests" in CONTRIBUTING.md, there was a missing hyperlink associated with "issue"
Linked the missing hyperlink for "issue" to [https://github.com/aws/aws-sdk-php/issues](https://github.com/aws/aws-sdk-php/issues)

Fixed missing hyperlink in CONTRIBUTING.md

---

tests/Api/Parser/DecodingEventStreamIteratorTest.php
tests/ClientResolverTest.php
tests/Credentials/EcsCredentialProviderTest.php
tests/EndpointV2/EndpointProviderV2Test.php

Switches over to generator-based yields for test cases constructed from fixture files; Removes unnecessary `rmdir()` call causing errors. 

chore: yield dynamic test cases

---

.changes/nextrelease/fix-xml-serialiation.json
src/Api/Serializer/RestSerializer.php
src/Api/Serializer/XmlBody.php
tests/Api/Serializer/ComplianceTest.php
tests/Api/Serializer/RestXmlSerializerTest.php

Closes #3153 
Reverts to previous behavior when resolving root element names with requests that specify a payload member.  The behavior prescribed by smithy in the cases added in #3144 contradict expected behavior in actual AWS services.

bugfix: rest-xml payload member serialization

---

.changes/nextrelease/bedrock-token-provider.json
src/AwsClient.php
src/ClientResolver.php
src/Configuration/ConfigurationResolver.php
src/Middleware.php
src/Token/BedrockTokenProvider.php
src/Token/Token.php
src/Token/TokenProvider.php
tests/AwsClientTest.php
tests/Token/BedrockTokenProviderTest.php

Adds a provider to fetch token values from environment.  If found, sets auth scheme preference to prefer `bearer`.  Additional tests will be added once #3156 is approved and merged.

feat: bedrock token provider
