src/ClientFactory.php
This commit adds a way for us to create custom error messages for
missing required client configuration options. In this commit, I've
added helpful error messages for a missing region (i.e., a link to
rande.html), and a helpful error message for a missing version (i.e., a
list of available versions on disk and a link to the API docs).
=> Adding a system for more helpful factory errors.

src/DynamoDb/BinaryValue.php, src/DynamoDb/Marshaler.php, src/DynamoDb/NumberValue.php, src/DynamoDb/SetValue.php, tests/DynamoDb/MarshalerTest.php
This includes support for binary and set values via special methods/classes.
=> Added the DynamoDB Marshaler

docs/credentials.rst
Outer array of 'credentials' array removed.
=> Configuration file format fixed

composer.json
Depends on https://github.com/guzzle/promises/pull/4, https://github.com/guzzle/psr7/pull/5, and https://github.com/guzzle/aws-guzzle-handler/pull/4.
=> Composer tweaks

composer.json, src/ClientResolver.php, src/Handler/GuzzleV5/GuzzleHandler.php, src/Handler/GuzzleV5/GuzzleStream.php, src/Handler/GuzzleV5/PsrStream.php, src/Sdk.php, src/Sns/MessageValidator/MessageValidator.php, tests/Handler/Guzzle5/HandlerTest.php, tests/Handler/Guzzle5/StreamTest.php, tests/Integ/GlacierMultipartTest.php, tests/Integ/GuzzleV5HandlerTest.php, tests/Integ/S3MultipartTest.php
@mtdowling - I moved the things!
=> Moves the aws-guzzle-handler project into the SDK.

src/History.php, src/Middleware.php, src/S3/StreamWrapper.php, tests/HistoryTest.php, tests/MiddlewareTest.php, tests/S3/StreamWrapperTest.php
=> Updating stream wrapper and adding a history middleware

src/Aws/Common/Client/AbstractClient.php, src/Aws/Common/Client/ClientBuilder.php, src/Aws/Common/Client/ExpiredCredentialsChecker.php, src/Aws/Common/Client/UploadBodyListener.php, src/Aws/DynamoDb/Model/BatchRequest/WriteRequestBatchTransfer.php, src/Aws/Ec2/CopySnapshotListener.php, src/Aws/Glacier/GlacierUploadListener.php, src/Aws/Glacier/Model/MultipartUpload/AbstractTransfer.php, src/Aws/Glacier/Model/MultipartUpload/ParallelTransfer.php, src/Aws/Glacier/Model/MultipartUpload/SerialTransfer.php, src/Aws/Glacier/Model/MultipartUpload/UploadBuilder.php, src/Aws/ImportExport/JobManifestListener.php, src/Aws/MachineLearning/PredictEndpointListener.php, src/Aws/S3/AcpListener.php, src/Aws/S3/Model/Acp.php, src/Aws/S3/Model/MultipartUpload/AbstractTransfer.php, src/Aws/S3/Model/MultipartUpload/ParallelTransfer.php, src/Aws/S3/ResumableDownload.php, src/Aws/S3/Sync/AbstractSyncBuilder.php, src/Aws/S3/Sync/UploadSyncBuilder.php, src/Aws/Sqs/QueueUrlListener.php
Going through the code I noticed some inconsistencies.
See http://www.phpdoc.org/docs/latest/references/phpdoc/tags/var.html
=> Fix inconsist @var PhpDoc & use statements

src/Credentials/RefreshableCredentials.php, src/Credentials/RefreshableCredentialsInterface.php
Adding a way to refresh credentials. This would be useful if you know that credentials have been revoked OR if you get an exception about invalid credentials before the credentials expire and want to force them to refresh.
=> Adding RefreshableCredentialsInterface

src/Aws/S3/IncompleteMultipartUploadChecker.php, src/Aws/S3/S3Client.php, tests/Aws/Tests/S3/S3ClientTest.php, tests/mock/s3/complete_multipart_upload_error
=> Prevents S3 CompleteMultipartUpload failures by retrying the request.

src/Aws/Common/Credentials/Credentials.php, tests/Aws/Tests/Common/Credentials/.aws/credentials, tests/Aws/Tests/Common/Credentials/CredentialsTest.php
Updates credential chain so that it fails over to instance profile credentials when ini credentials are invalid.
=> Better failover for INI credentials.

composer.json
=> Tweaked composer.json

src/S3/S3Client.php, tests/S3/S3ClientTest.php
Fixes #627. /cc @mtdowling @jeskew
=> Adding support for the SaveAs parameter to the S3 GetObject operation.

docs/getting-started/basic-usage.rst
=> Typo in exception example

src/Api/Parser/Crc32ValidatingParser.php
=> Loosen crc32 checksum comparison

src/S3/StreamWrapper.php, tests/S3/StreamWrapperTest.php
Closes #590 
@jeremeamia @jeskew
=> Determining object size correctly

src/Aws/S3/StreamWrapper.php, tests/Aws/Tests/S3/Integration/StreamWrapperTest.php
Closes #609
@jeremeamia @jeskew
=> Updating stream wrapper to check response status

src/Api/Serializer/JsonBody.php, tests/Api/test_cases/protocols/input/json.json
Addresses #650
/cc @jeremeamia && @mtdowling
=> Replace input values with formatted values in JSON list serialization

src/Exception/CouldNotCreateChecksumException.php
Guzzle6 changed location of this class.
=> Updated Guzzle5 classname to Guzzle6 classname for CachingStream

src/Glacier/GlacierClient.php, src/S3/ApplyChecksumMiddleware.php, src/S3/S3Client.php, tests/S3/ApplyChecksumMiddlewareTest.php
Inspired by #655, this PR aims to do the following:
* Support `ContentSHA256` as a documented parameter for S3 and Glacier upload operations.
* Remove `ContentMD5` from API documentation for S3 upload operations (still works, just doesn't show up in docs).
* Support a non-capitalized `contentSHA256` in Glacier to match other params (capitalized still works).
* Fixes a bug in the Glacier middleware where the operation name for `UploadMultipartPart` was incorrect.
* Fixes the API documentation for Glacier upload operations for the `sourceFile` param. Was previously listed with a capital "S".
* Updates the API docs for all Glacier operations such that `accountId` is no longer marked as required.
@mtdowling and @jeskew, please take a look and let me know if you have any more ideas about ways …
=> Updating checksum middlewares and related API docs for S3/Glacier

src/Api/StructureShape.php
=> Cache the members list in StructureShape

src/Api/Serializer/QueryParamBuilder.php, tests/Api/test_cases/protocols/input/query.json
=> Use the locationName in query serialization if present

src/Api/Parser/AbstractRestParser.php, src/Api/Parser/XmlParser.php, src/Api/Serializer/XmlBody.php, tests/Api/test_cases/protocols/input/json.json, tests/Api/test_cases/protocols/input/rest-json.json, tests/Api/test_cases/protocols/input/rest-xml.json, tests/Api/test_cases/protocols/output/query.json, tests/Api/test_cases/protocols/output/rest-json.json, tests/Api/test_cases/protocols/output/rest-xml.json
Fix parser tests
Fix serializer tests
Use locationName of shapes even when they are flattened lists whose members have no locationName
=> Sync updated protocol test cases and apply necessary fixes

features/smoke/codedeploy/codedeploy.feature, features/smoke/codepipeline/codepipeline.feature, features/smoke/devicefarm/devicefarm.feature, features/smoke/emr/emr.feature, tests/Integ/SmokeContext.php
(and make account state-related failures count as a skip instead of a fail)
=> Make the smoke tests less dependent on account state 

docs/service/s3-multipart-upload.rst, src/S3/MultipartUploader.php, tests/S3/MultipartUploaderTest.php
=> Reconcile S3Client::putObject and MultipartUploader args

README.md, docs/guide/migration.rst, docs/service/s3-multipart-upload.rst, src/CodeCommit/CodeCommitClient.php, src/CodeCommit/Exception/CodeCommitException.php
Some documentation updates.
/cc @mtdowling
=> Documentation updates

features/smoke/efs/efs.feature, tests/Integ/SmokeContext.php
EFS is still tweaking their error messaging.
/cc @mtdowling
=> Adjust to new error message

Makefile, build/packager.php
Backporting the phar fix to the 2.8 branch.
/cc @mtdowling
=> Map phar in stub file and set a versioned alias

src/Aws/Sns/MessageValidator/MessageValidator.php, tests/Aws/Tests/Sns/MessageValidator/MessageValidatorTest.php
For testing and SNS-compatible services.
/cc @mtdowling
=> Allow constructor overrides of the SNS host pattern

Makefile, behat.yml, features/bootstrap/Aws/Test/PerformanceContext.php, features/bootstrap/Aws/Test/UsesServiceTrait.php, features/performance/clients.feature, features/performance/streaming.feature, tests/PerformanceContext.php
=> Add some tests to catch memory and resource links

src/Api/Serializer/RestSerializer.php, tests/Api/test_cases/protocols/input/rest-json.json, tests/Api/test_cases/protocols/input/rest-xml.json, tests/Integ/SmokeContext.php
Adds support for querystring maps and adds a few test cases to validate.
/cc @mtdowling
=> Add support for maps as querystrings

src/CloudFront/UrlSigner.php, tests/CloudFront/UrlSignerTest.php
=> Policy url matches

CHANGELOG.md
Fixed a simple typo in the changelog. (This is my first attempt at contributing to a major github project, so please forgive me if I've done something wrong or made a mistake!)
=> Fixed a typo.

src/Aws/Lambda/Resources/lambda-2015-03-31.php
/cc @mtdowling @chrisradek 
This would solve #801
=> Add back location of Payload on Lambda::Invoke

src/Api/Parser/JsonParser.php, src/Api/Serializer/JsonBody.php, src/Api/Serializer/QueryParamBuilder.php, tests/Api/Parser/ComplianceTest.php, tests/Api/Serializer/ComplianceTest.php, tests/Api/test_cases/protocols/input/query.json, tests/Api/test_cases/protocols/input/rest-json.json, tests/Api/test_cases/protocols/input/rest-xml.json, tests/Api/test_cases/protocols/output/ec2.json, tests/Api/test_cases/protocols/output/json.json, tests/Api/test_cases/protocols/output/query.json, tests/Api/test_cases/protocols/output/rest-xml.json
This PR adds support for sparse lists and named locations in query lists and JSON structures.
=> Sync compliance tests

build/docs.php, build/docs/classes/DocsBuilder.php, build/docs/theme/@layout.latte, build/docs/theme/js/main.js, build/docs/theme/namespace.latte, build/docs/theme/overview.latte, build/docs/theme/package.latte, composer.json
This PR will add API operations and class methods to the client-side search functionality in our API docs.
=> Build out an index of terms to search

docs/faq.rst
=> Add FAQ entry on Parse errors

compatibility-test.php
=> Update compatibility test

src/Api/Parser/JsonRpcParser.php, src/Api/Parser/QueryParser.php, tests/Api/Parser/JsonRpcParserTest.php
=> Handle null JSON responses

src/DynamoDb/SessionHandler.php, tests/DynamoDb/SessionHandlerTest.php
This PR ports the changes from #825 to v3 to address the concern raised in #821 across all versions. There's less tomfoolery with `__get` and such because the instance members requiring modification were already private.
=> Change sessions written/read trackers from scalars to id => scalar mappings

src/Ses/SesClient.php
=> Add a docblock to the generateSmtpPassword method

build/docs/theme/namespace.latte, build/docs/theme/overview.latte, build/docs/theme/package.latte
=> Update documentation on namespace, overview, and package pages

src/CloudFront/Signer.php
=> Normalize CloudFront policies before encoding them

docs/service/s3-transfer.rst
The docs for the transfer manager were a bit stale. This PR updates them and adds an example for `before` callbacks.
=> Update Transfer Manager documentation to highlight before callbacks

features/bootstrap/Aws/Test/Integ/BatchingContext.php, features/bootstrap/Aws/Test/Integ/BlockingContext.php, features/bootstrap/Aws/Test/Integ/ConcurrencyContext.php, features/bootstrap/Aws/Test/Integ/MultipartContext.php, features/bootstrap/Aws/Test/Integ/NativeStreamContext.php
=> Expose all cucumber tests to the test-phar make target

composer.json, docs/guide/migration.rst
=> Better document the SNS validator package. Resolves #625

src/ResultPaginator.php, tests/ResultPaginatorTest.php
This would allow the use of optional response parameters as pagination tokens.
=> Track next tokens as a map instead of a pair of arrays

.travis.yml, src/S3/S3Client.php, tests/S3/S3ClientTest.php
Also, url decode affected fields if the EncodingType was set to URL by the SDK.
/cc @mtdowling @xibz @chrisradek
=> Automatically request URL encoding on ListObjects

src/Exception/MultipartUploadException.php, tests/Exception/MultipartUploadExceptionTest.php
This will resolve #923 
/cc @chrisradek @xibz @mtdowling
=> Ensure MultipartUploadExceptions caused by a single AwsException have a descriptive message

docs/guide/configuration.rst, docs/guide/handlers-and-middleware.rst, src/AwsClient.php, src/ClientResolver.php, src/DynamoDb/DynamoDbClient.php, src/Exception/AwsException.php, src/Handler/GuzzleV5/GuzzleHandler.php, src/Handler/GuzzleV6/GuzzleHandler.php, src/Middleware.php, src/RetryMiddleware.php, src/WrappedHttpHandler.php, tests/ClientResolverTest.php, tests/DynamoDb/DynamoDbClientTest.php, tests/Handler/GuzzleV5/HandlerTest.php, tests/Handler/GuzzleV6/HandlerTest.php, tests/MiddlewareTest.php, tests/RetryMiddlewareTest.php, tests/WrappedHttpHandlerTest.php
This PR binds the number of retries attempted to exceptions and results returned by `Aws\RetryMiddleware`. This will resolve #913.
/cc @xibz @chrisradek @mtdowling
=> Add transfer stats

src/AwsClient.php, src/DynamoDb/DynamoDbClient.php, src/Middleware.php, src/RetryMiddleware.php, tests/MiddlewareTest.php, tests/RetryMiddlewareTest.php
1. Update error code handling
2. Make Consistent Retry Scheme
/cc @jeskew
=> Make retry logic consistent for php sdk

src/Aws/Lambda/Resources/lambda-2015-03-31.php
Closes #958
/cc @cjyclaire @mtdowling @xibz
=> Patching the UpdateFunctionCode Lambda operation.

docs/service/s3-presigned-post.rst, features/s3/postObject.feature, src/S3/PostObjectV4.php, src/Signature/SignatureTrait.php, src/Signature/SignatureV4.php, tests/Integ/S3Context.php, tests/S3/PostObjectV4Test.php, tests/S3/sig_hack.php
Update S3 post object to SigV4.
cc:\ @jeskew
=> Update S3 POST object to Signature V4

src/S3/ApplyChecksumMiddleware.php
=> Add Content-MD5 for S3 PutBucketReplication

src/Aws/Lambda/Resources/lambda-2015-03-31.php
=> Patch ZipFile location in UpdateFunctionCode

src/RetryMiddleware.php, tests/RetryMiddlewareTest.php
Add retry logic for Http Error Code 502 & 504.
cc: @jeskew @mtdowling
=> Add 502 & 504 error code for retry

docs/faq.rst, src/Signature/S3SignatureV4.php
This PR update FAQ in SDK guide for disabling body signing in S3 as an option.
cc: @xibz @petermoon @mtdowling @jeskew
=> Add documentation for disable body signing in S3

docs/faq.rst, features/s3/presignedUrls.feature, src/Signature/S3SignatureV4.php
Fix the S3 presign  #996, #997 
cc: @mtdowling @xibz @jeskew
=> Fix S3 presign request

src/RetryMiddleware.php
=> Fix for mixed return from min causing mt_rand issues

README.md
=> Update README with clarification on related projects

docs/configuration.rst, src/Aws/CloudSearchDomain/CloudSearchDomainClientBuilder.php, src/Aws/Common/Client/ClientBuilder.php, src/Aws/Common/Enum/ClientOptions.php, src/Aws/DynamoDb/DynamoDbClient.php, src/Aws/S3/S3Client.php, tests/Aws/Tests/Common/Client/ClientBuilderTest.php, tests/Aws/Tests/DynamoDb/DynamoDbClientTest.php, tests/Aws/Tests/S3/S3ClientTest.php
Debugging an odd socket idle timeout error I wanted to increase the backoff number of retries. Although it's possible to create your own backoff I thought of this simple change to allow configuration of the backoff num of retries.
=> configurable backoff retries

composer.json
This PR updates composer dependency before next release.
@mtdowling
=> Update composer dependency

composer.json
I assume this is what you meant to change them to, to keep the behaviour the same?
=> Fixed broken version constraints

src/CloudSearchDomain/CloudSearchDomainClient.php, tests/CloudSearchDomain/CloudSearchDomainTest.php
Issue #1044 
Similar fixed issue related in [`aws-sdk-js`](https://github.com/aws/aws-sdk-js/issues/614) 
cc:\ @mtdowling @xibz @chrisradek @LiuJoyceC
=> Use POST instead of GET for CloudSearch Domain Search

src/RetryMiddleware.php, tests/RetryMiddlewareTest.php
Issue related: #1055 
Disable autoload when checking class existence.
cc:\ @mtdowling @xibz
=> Disable autoload when checking class existence

README.md, docs/faq.rst
Address issue #1060 and aws/aws-php-sns-message-validator#15
cc:\ @xibz @mtdowling @petermoon
=> [Doc-Only]Add Error code handling documentation and split project information

src/S3/DualStackMiddleware.php, src/S3/S3Client.php, tests/S3/DualStackMiddlewareTest.php, tests/S3/S3ClientTest.php
Adding support for dual stack endpoint that enables IPv6.
cc:\ @mtdowling @xibz
=> Adding support for S3 IPv6

build/docs/classes/DocsBuilder.php, src/ElasticLoadBalancingV2/ElasticLoadBalancingV2Client.php, tests/ElasticLoadBalancingV2/ElasticLoadBalancingV2ClientTest.php
Addressing issue #1071 
Resolving ElasticLoadBalancingV2 with ElasticLoadBalancing endpoints.
cc:\ @mtdowling @xibz
=> Fix ElasticLoadBalancingV2 endpoints resolving issue

src/Credentials/CredentialProvider.php
issue #1107 
cc: @mtdowling @xibz
=> [Doc fix] Remove (optional) in documentation

src/Credentials/EcsCredentialProvider.php, tests/Credentials/EcsCredentialProviderTest.php
Separate Ecs fix part from PR #1077  to address issue #1125 
Ecs part of PR #1077 has been reviewed.
=> Fix ECS credential throws exception outside of a rejected promise

Makefile, build/build-redirect-map.php, build/docs/classes/RedirectMapBuilder.php, build/docs/classes/Service.php, src/Api/Service.php, tests/Api/ServiceTest.php
This PR has been reviewed offline.
Adding support for doc-crossing linking between SDK API docs and AWS Doc website.
=> Add Doc cross linking support

src/Signature/SignatureV4.php
Adding a new blacklist header.
@shorea
=> Blacklist 'x-amzn-trace-id' header

src/RetryMiddleware.php, tests/RetryMiddlewareTest.php
Addressing issue #1186 
@jeskew @imshashank
=> Fix retry jitter logic in #exponentialDelay

composer.json, src/Api/Serializer/RestSerializer.php, src/Sqs/SqsClient.php
=> Force usage of the latest version of guzzlehttp/psr7 due to BC concerns

docs/examples/cw-examples-create-alarms.rst, docs/examples/cw-examples-work-with-alarms.rst, docs/examples/cw-examples.rst, docs/examples/index.rst, docs/index.rst
Initial pull request. If this process works, I'll do more topics at a time next time.
=> 5x5: Working with Amazon Cloudwatch Alarms

build/changelog/ChangelogBuilder.php, tests/Build/Changelog/ChangelogBuilderTest.php, tests/Build/Changelog/resources/.changes/nextrelease/test.json, tests/Build/Changelog/resources/release-json-valid
Also removed method to fix endpoints.json file as it's no longer needed.
=> Update Changelog to include Docs Only Release

README.md
As title describes.
@imshashank @kstich
=> Fix gitter badge link in README.md

src/Api/Operation.php, src/Api/Serializer/JsonBody.php, src/Api/Serializer/XmlBody.php, src/S3/S3Client.php, tests/Api/OperationTest.php, tests/Api/Serializer/JsonBodyTest.php, tests/S3/S3ClientTest.php
Follow up to #1168 to clean up other foreach-by-reference locations.
=> Fix dangling references

.gitignore, .travis.yml, codecov.yml, composer.json, phpunit.xml.dist
Adding CodeCov to the repo.
This update deprecated phpunit 4 in favor of phpunit 4.8
Please review the code @kstich @mtdowling @jeskew @cjyclaire
=> Add CodeCov to repo

docs/guide/configuration.rst
Example had some typos that prevent to copy & paste for test
=> Fix typos on code

phpunit.xml.dist, tests/FunctionsTest.php
Add PHPUnit coverage for functions.php. Clean up + mark coverage on existing tests and add several more for increased coverage.
Resolution of issue #1242
=> PHPUnit coverage for functions.php

Makefile, behat.yml, features/smoke/importexport.feature, features/smoke/sts.feature
Add filter to skip specific smoe tests.
=> Skip Broken Smoke test

build/docs/classes/DocsBuilder.php
Update documentation `$title` check to resolve service and and service version documentation discrepancies.
=> Broken Service Version Documentation

src/ClientResolver.php, tests/ClientResolverTest.php
Fix for Issue : https://github.com/aws/aws-sdk-php/issues/1257
=> Validation check for is_callable

docs/guide/configuration.rst
Acknowledge that clients have configuration options specific to them and direct users to their location.
Resolution for #1302
=> Configuration Document Update

.travis.yml
Move back to precise while we work on the trusty build issues.
=> Specify Travis dist: precise

README.md
Fix broken services listing link.
=> Link fix in Readme

.changes/nextrelease/s3_stream_uri_parser, src/S3/S3UriParser.php, tests/S3/S3UriParserTest.php
Properly parse s3:// uri used with StreamWrapper, with tests.
Resolves #1383
=> S3 Stream Uri Parsing

README.md, docs/glossary.rst, docs/guide/credentials.rst, docs/guide/migration.rst, docs/index.rst
Update a chunk of broken or redirecting links in documentation.
=> Doc Link Fixes

build/docs/theme/@layout.latte, docs/_templates/layout.html
Updating analytics code on the Guide and API Doc pages along with some minor formatting updates.
=> Analytics JS Fixes

src/DynamoDb/Marshaler.php, src/S3/Exception/S3MultipartUploadException.php
=> Cleanup for each() calls

src/ClientResolver.php, tests/ClientResolverTest.php
Add HHVM version to User-Agent if it is defined. Expand ClientResolver test to handle it optionally.
=> HHVM version in User-Agent

docs/service/cloudfront-signed-url.rst
Update service guides to be consistent with functionality in url param usage.
=> Cloudfront Guide Fix

.changes/nextrelease/new_retry_code.json, src/RetryMiddleware.php
Add support for retrying exception code RequestThrottledException.
=> Retry RequestThrottledException

.changes/nextrelease/clean-elses, build/changelog/ChangelogBuilder.php, build/docs/classes/CodeSnippetGenerator.php, src/Api/Serializer/RestSerializer.php, src/Crypto/MetadataEnvelope.php, src/DynamoDb/Marshaler.php, src/HandlerList.php, src/HashingStream.php, src/History.php, src/RetryMiddleware.php, src/S3/Crypto/CryptoParamsTrait.php, src/S3/ObjectUploader.php, src/S3/S3EndpointMiddleware.php, src/S3/StreamWrapper.php, src/Waiter.php, src/functions.php, tests/Api/ValidatorTest.php, tests/AwsClientTest.php, tests/ResultPaginatorTest.php, tests/WaiterTest.php
I've removed the `else`s when we have already returned something :put_litter_in_its_place:
[`PHP-CS-Fixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer) helped me find them.
=> Clean elses

docs/guide/configuration.rst
=> Change default timeouts documentation to reflect real world value

.travis.yml, codecov.yml
Update Travis to send coverage for optimal and lowest settings of PHP 7.1. Update CodeCov to report after receiving both coverages.
/cc @jeskew
=> Travis / CodeCov Updates

.travis.yml
[Based on PHPUnit Changelog](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-5.7.md#5711---2017-02-05)
/cc @chrisradek
=> Correct phpunit/phpunit Version for 7.2 with Lowest Dependencies.

features/smoke/application-autoscaling.feature, features/smoke/autoscaling.feature, features/smoke/cognitoidentity.feature, features/smoke/cognitosync.feature, features/smoke/dynamodbstreams.feature
Update tags on features for correct usage.
/cc @cjyclaire
=> Smoke Feature Tags

tests/S3/PostObjectV4Test.php, tests/S3/S3ClientTest.php
Update coverage annotations on test classes.
/cc @cjyclaire
=> Coverage Annotations

docs/guide/paginators.rst
Missing `function` in the docs.
=> Add missing function in docs

src/Api/Serializer/RestSerializer.php, src/Api/Service.php, src/ClientResolver.php, src/Crypto/EncryptionTrait.php, src/DynamoDb/Marshaler.php, src/HandlerList.php, src/History.php, src/IdempotencyTokenMiddleware.php, src/Multipart/AbstractUploadManager.php, src/RetryMiddleware.php, src/S3/Crypto/CryptoParamsTrait.php, src/S3/S3Client.php, src/S3/S3EndpointMiddleware.php, src/Sdk.php, src/TraceMiddleware.php, src/Waiter.php, src/functions.php
As a title, I removed the useless else after returns.
(Without changing the logic)
=> Removed useless else after return

.changes/nextrelease/retry_index_fix.json, src/RetryMiddleware.php
Fixes an undefined index issue.
/cc @jeskew
=> Retry Undefined Index Fix

.changes/nextrelease/changelog_document_tests.json, tests/Build/Changelog/CurrentChangesTest.php
Add tests to validate location, naming, and JSON compilability of Changelog Documents.
=> Add Changelog Document Verification Tests

tests/S3/Crypto/S3EncryptionMultipartUploaderTest.php
additional fix to https://github.com/aws/aws-sdk-php/pull/1423
=> use namespaced phpunit

.changes/nextrelease/override_ecs_proxy.json, src/Credentials/EcsCredentialProvider.php, tests/Credentials/EcsCredentialProviderTest.php
Disables proxies on EcsCredentialProvider credential lookups.
=> Disable ECS Credentials Lookup Proxies

.changes/nextrelease/s3_addressing_tests.json, tests/S3/S3EndpointMiddlewareTest.php, tests/S3/test_cases/uri_addressing.json
Adds compliance tests for S3 addressing.
=> S3 Addressing Compliance Tests

.changes/nextrelease/service_id_getter.json, src/Api/Service.php, tests/Api/ServiceTest.php
Add a getter for Service ID to the Aws\Api\Service class.
=> Add Service ID getter to Service class

src/RetryMiddleware.php
=> Adds link to explainer of exponential backoff with jitter.

.changes/nextrelease/timestampFormat_updates.json, src/Api/Parser/AbstractRestParser.php, src/Api/Parser/JsonParser.php, src/Api/Parser/XmlParser.php, src/Api/Serializer/JsonBody.php, src/Api/Serializer/QueryParamBuilder.php, src/Api/Serializer/RestSerializer.php, src/Api/Serializer/XmlBody.php, tests/Api/Serializer/ComplianceTest.php, tests/Api/test_cases/protocols/input/ec2.json, tests/Api/test_cases/protocols/input/json.json, tests/Api/test_cases/protocols/input/query.json, tests/Api/test_cases/protocols/input/rest-json.json, tests/Api/test_cases/protocols/input/rest-xml.json, tests/Api/test_cases/protocols/output/ec2.json, tests/Api/test_cases/protocols/output/json.json, tests/Api/test_cases/protocols/output/query.json, tests/Api/test_cases/protocols/output/rest-json.json, tests/Api/test_cases/protocols/output/rest-xml.json
Updates parsers and serializers to handle the `timestampFormat` trait while maintaining original behaviors. Includes updates to the test suite to validate.
=> Timestamp format updates

build/packager.php
=> Use include-guarded functions from GuzzleHttp

.changes/nextrelease/lambda_tcp_keepalive.json, src/Lambda/LambdaClient.php, tests/Lambda/LambdaClientTest.php
Added default TCP Keep-Alive Curl setting for the Lambda client.
=> Lambda TCP Keep-Alive

.changes/nextrelease/docsbuilder_required_fix.json, build/docs/classes/DocsBuilder.php
=> Fix API docs issue with required members in shapes

.changes/nextrelease/static_closure_fix.json, features/bootstrap/Aws/Test/Integ/ClientSideMonitoringContext.php, src/ClientSideMonitoring/AbstractMonitoringMiddleware.php, src/ClientSideMonitoring/ApiCallAttemptMonitoringMiddleware.php, src/ClientSideMonitoring/ApiCallMonitoringMiddleware.php
* Static closure fix for PHP 5.5.x 
* Integ test object variable assignment fix for PHP 5.5.x
Fixes #1640
=> Static closure fix

.changes/nextrelease/csm_spec_updates.json, features/bootstrap/Aws/Test/Integ/csm/cases.json, features/bootstrap/Aws/Test/Integ/csm/cases_php_sdk.json, src/ClientSideMonitoring/ApiCallMonitoringMiddleware.php, src/ClientSideMonitoring/ConfigurationProvider.php, tests/ClientSideMonitoring/ApiCallMonitoringMiddlewareTest.php, tests/ClientSideMonitoring/ConfigurationProviderTest.php
* Add region to API call event entries 
* Change csm config key to match updated spec
=> ClientSideMonitoring spec updates

.changes/nextrelease/refactor_error_suppression.json, src/functions.php
=> Refactor error suppression

.changes/nextrelease/csm_final_entries.json, features/bootstrap/Aws/Test/Integ/ClientSideMonitoringContext.php, features/bootstrap/Aws/Test/Integ/csm/cases.json, features/bootstrap/Aws/Test/Integ/csm/cases_php_sdk.json, src/ClientSideMonitoring/AbstractMonitoringMiddleware.php, src/ClientSideMonitoring/ApiCallAttemptMonitoringMiddleware.php, src/ClientSideMonitoring/ApiCallMonitoringMiddleware.php, tests/ClientSideMonitoring/ApiCallMonitoringMiddlewareTest.php
* Adds User-Agent entry to API call event
* Adds final API call attempt entries to API call event
=> Client-Side Monitoring API Call event additions

.changes/nextrelease/credential_provider_loop_fix.json, src/Credentials/CredentialProvider.php, tests/Credentials/CredentialProviderTest.php
=> Fixes infinite loop in CredentialProvider

README.md
* Add S3 Sig V2 deprecation notice to Readme
=> Add S3 Sig V2 deprecation notice

.changes/nextrelease/api_docs_feedback.json, build/docs/theme/@layout.latte, build/docs/theme/js/main.js, build/docs/theme/resources/css/style.css
* Add feedback link to api docs
=> Api docs feedback

tests/Integ/CredentialsContext.php
No change in functionality. Aligns role setup/tear-down within feature itself.
=> Refactor role setup/tear-down into feature

tests/Endpoint/PartitionEndpointProviderTest.php
* Remove outdated endpoint provider test
=> Remove outdated endpoint test

features/smoke/configservice.feature
* Remove outdated Config Service smoke test
=> Remove outdated Config smoke test

src/RetryMiddleware.php
* Adds TooManyRequestsException to retryable error codes
Resolves #1825
=> Add TooManyRequestsException to retry codes

tests/RetryMiddlewareTest.php
Adds additional retry codes to RetryMiddlewareTest
=> additional retry codes

.changes/nextrelease/dynamo_local_endpoint_tests.json, tests/ClientResolverTest.php, tests/Endpoint/PartitionEndpointProviderTest.php
* Add back partition endpoint tests for dynamodb local
=> Add back dynamo local tests

.changes/nextrelease/modeled_exception_api_docs.json, build/docs.php, build/docs/classes/DocsBuilder.php, build/docs/classes/Service.php, build/docs/theme/class.latte, src/Api/Service.php, tests/Api/ErrorParser/JsonRpcErrorParserTest.php, tests/Api/ErrorParser/RestJsonErrorParserTest.php, tests/Api/ErrorParser/XmlErrorParserTest.php, tests/Api/ServiceTest.php, tests/TestServiceTrait.php, tests/WrappedHttpHandlerTest.php
* Add modeled exceptions to API docs generation for exception classes.
=> Modeled exception api docs

.changes/nextrelease/web_identity_provider_tweak.json, src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php
* Update web identity provider to handle all exceptions.
=> Web identity provider tweak

src/Api/DocModel.php, src/Api/ErrorParser/AbstractErrorParser.php, src/Api/ErrorParser/JsonRpcErrorParser.php, src/Api/Parser/DecodingEventStreamIterator.php, src/Api/Parser/Exception/ParserException.php, src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php, src/Credentials/EcsCredentialProvider.php, src/Credentials/InstanceProfileProvider.php, src/DynamoDb/DynamoDbClient.php, src/DynamoDb/SessionConnectionConfigTrait.php, src/EndpointDiscovery/EndpointDiscoveryMiddleware.php, src/EndpointParameterMiddleware.php, src/Glacier/GlacierClient.php, src/Handler/GuzzleV5/GuzzleHandler.php, src/MultiRegionClient.php, src/ResponseContainerInterface.php, src/S3/S3Client.php, src/S3/StreamWrapper.php
* Code cleanup for parameter usage, class properties, typehints, etc.
=> Code cleanup

tests/Integ/S3Context.php
* Fix issue with integration test waiter
=> Fix issue with integration test waiter

.changes/nextrelease/s3_integ_waiter_tweak.json, tests/Integ/S3Context.php
* Modify waiter settings for S3 integration test
=> S3 integ waiter tweak

.changes/nextrelease/eventstream_example.json, build/docs/classes/EventStreamExampleBuilder.php
Fixes EventParsingIterator example in documentation.
=> Fix EventParsingIterator example

.changes/nextrelease/s3_seekable_stream_fix.json, src/S3/StreamWrapper.php
* Tweak S3 stream wrapper size logic for seekable streams.
Resolves #1871
=> S3 seekable stream fix

.changes/nextrelease/update-workspaces-smoke-test.json, features/smoke/workspaces.feature
Updates smoke test for WorkSpaces
=> update WorkSpaces smoke test

.changes/nextrelease/s3_regional_endpoint.json, src/AbstractConfigurationProvider.php, src/ClientResolver.php, src/ConfigurationProviderInterface.php, src/Endpoint/Partition.php, src/Endpoint/PartitionEndpointProvider.php, src/S3/RegionalEndpoint/Configuration.php, src/S3/RegionalEndpoint/ConfigurationInterface.php, src/S3/RegionalEndpoint/ConfigurationProvider.php, src/S3/RegionalEndpoint/Exception/ConfigurationException.php, src/S3/S3Client.php, tests/AbstractConfigurationProviderTest.php, tests/ClientResolverTest.php, tests/Endpoint/PartitionTest.php, tests/Endpoint/fixtures/s3_us_east_1_regional_endpoint.json, tests/S3/RegionalEndpoint/ConfigurationProviderTest.php, tests/S3/RegionalEndpoint/ConfigurationTest.php, tests/S3/S3ClientTest.php
* Added support for S3 us-east-1 regional endpoint setting and corresponding configuration.
=> Release S3 regional endpoint

.changes/nextrelease/signed_imds_tweak.json, src/Credentials/InstanceProfileProvider.php
=> InstanceProfileProvider tweak

tests/S3/S3ClientTest.php
* Fix incorrect config key in test
=> Fix incorrect config key in test

.travis.yml, composer.json
prepares for release of PHP 7.4
=> prepares for release of PHP 7.4

.changes/nextrelease/validate_account_id.json, src/S3Control/S3ControlEndpointMiddleware.php, tests/S3Control/S3ControlEndpointMiddlewareTest.php
Validate S3Control input paramater for host name compatibility.
=> S3 control account id validation

.changes/nextrelease/s3_accesspointarn_examples.json, build/docs/classes/CodeSnippetGenerator.php, build/docs/classes/DocsBuilder.php, src/S3/S3Client.php, tests/Build/Docs/CodeSnippetGeneratorTest.php
* Adds a hook for custom examples in API documentation generation.
* Adds S3 access point ARN examples
=> S3 accesspointarn examples

tests/Integ/S3Context.php
* Add logging to S3 integ test cleanup
=> Add logging to S3 integ test cleanup

.changes/nextrelease/ec2throttledexception.json, src/RetryMiddleware.php, tests/RetryMiddlewareTest.php
Adds retries for EC2ThrottledException
=> retry EC2ThrottledException

.changes/nextrelease/tweak_s3_integ.json, tests/Integ/S3Context.php
* Modify S3 integration context event hooks, as well as retry logic to take into account S3 eventual consistency characteristics.
=> S3 integration test context tweaks

.changes/nextrelease/s3_bucket_arn_copy.json, tests/S3/BucketEndpointArnMiddlewareTest.php
* Add test for CopyObject with source arn
=> Add test for CopyObject with source arn

.changes/nextrelease/pi_doc_redirect_fix.json, build/docs/classes/RedirectMapBuilder.php
* Adds customization in docs redirect map builder to avoid service name conflict.
=> Redirect map builder customization for Pi

.changes/nextrelease/gh_release_upload_retries.json, build/gh-release.php
* Add custom retry handling for github release artifact uploads to handle github API quirks.
=> Add custom retry handling for github release artifact uploads

.github/workflows/stale_issues.yml
Commented out dry-run flag so the action processes stale issues.
=> Remove dry-run flag from SIC action

.changes/nextrelease/s3_dualstack_partition_fix.json, src/S3/S3Client.php, src/S3/S3EndpointMiddleware.php, tests/S3/test_cases/uri_addressing.json
* Fixes incorrect host for dualstack and accelerate endpoints in non-AWS partitions.
=> S3 dualstack partition fix

.changes/nextrelease/docs_redirect_tweak.json, build/docs/classes/RedirectMapBuilder.php
* Tweak docs redirect logic to use uid if possible.
=> Docs redirect tweak

.travis.yml, phpstan.neon
* Fix dependency issue for Travis builds using phpstan.
=> Tweak phpstan dependency version requirement

.changes/nextrelease/retries_stats_fix.json, src/Retry/RetryHelperTrait.php, tests/RetryMiddlewareTest.php, tests/RetryMiddlewareV2Test.php
* Fixes issue with transfer stats not being populated for calls with retried exceptions.
=> Retries stats fix

README.md
*Jump links navigate to 404 not found page*
=> Fix README.md jump links

.changes/nextrelease/docs-update-copyobject.json, src/S3/S3Client.php
=> new docs message

README.md
Added a link to the AWS serverless LAMP stack repo
=> The serverless LAMP Stack Link added to readme

.changes/nextrelease/bugfix-s3-compressed-transfer.json, src/S3/Transfer.php, tests/S3/TransferTest.php
=> Bugfix s3 compressed transfer

.changes/nextrelease/s3_endpoint_test_fix.json, tests/Credentials/testlink, tests/Endpoint/PartitionEndpointProviderTest.php
* Tweaks test for PartitionEndpointProvider to accomodate changed S3 endpoint.
=> S3 endpoint test fix

docs/service/s3-stream-wrapper.rst, src/Crypto/DecryptionTrait.php, src/Crypto/DecryptionTraitV2.php
=> Fixed typo

src/Credentials/CredentialProvider.php
=> Remove redundant space

.changes/nextrelease/bugfix-sso-provider-empty-profile.json, .changes/nextrelease/enhancement-sso-provider-empty-profile.json, src/Credentials/CredentialProvider.php, tests/Credentials/CredentialProviderTest.php
=> enhancement-sso-provider-missing-profile

.changes/nextrelease/enhancement-circular-reference-check.json, .gitignore, src/Credentials/CredentialProvider.php, tests/Credentials/CredentialProviderTest.php
=> added circular source_profile check

.changes/nextrelease/bugfix-supress-file-warning.json, src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php, tests/Credentials/AssumeRoleWithWebIdentityCredentialProviderTest.php
This reverts commit b657810558194c337664922e38979503dbc89bec.
=> Revert "suppress file warning (#2103)"

.changes/nextrelease/bugfix-polyfill-folder.json, build/packager.php
2092
Fix polyfill filepath for packager
=> Bugfix polyfill idn

features/smoke/storagegateway.feature
* Updates StorageGateway smoke test to check for more inclusive failure
=> Update StorageGateway smoke test

.travis.yml
* Add PHP 8.0 to Travis CI tests
=> Add php 8.0 to travis ci

.travis.yml
=> Lower Phpstan version

.changes/nextrelease/feature-use-shared-credentials-file.json, src/Credentials/CredentialProvider.php, tests/Credentials/CredentialProviderTest.php
=> Use aws shared credential file

CHANGELOG.md, src/Sdk.php
=> fix changelog

.changes/nextrelease/bugfix-corrupted-multipart-copies.json, src/Multipart/AbstractUploader.php
=> Bugfix corrupted multipart copy

src/Credentials/CredentialProvider.php, src/Credentials/EcsCredentialProvider.php
=> Internal test fix

.changes/nextrelease/bugfix-guzzhandler-accepts-errors.json, src/Handler/GuzzleV6/GuzzleHandler.php, tests/Handler/GuzzleV6/HandlerTest.php
=> Guzzle handler now accepts errors

.changes/nextrelease/bugfix-empty-tokenfile.json, src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php, tests/Credentials/AssumeRoleWithWebIdentityCredentialProviderTest.php
=> bugfix empty token file

src/Credentials/EcsCredentialProvider.php, tests/Credentials/EcsCredentialProviderTest.php
=> redo missed getenv change

.changes/nextrelease/feature-privatelink.json, Makefile, src/ClientResolver.php, src/Handler/GuzzleV6/GuzzleHandler.php, src/S3/BucketEndpointArnMiddleware.php, src/S3/S3Client.php, src/S3/S3EndpointMiddleware.php, src/S3Control/EndpointArnMiddleware.php, src/S3Control/S3ControlClient.php, src/S3Control/S3ControlEndpointMiddleware.php, tests/ClientResolverTest.php, tests/S3/BucketEndpointArnMiddlewareTest.php, tests/S3/S3ClientTest.php, tests/S3Control/S3ControlClientTest.php
=> feature-privatelink

src/S3/S3Client.php
=> Add docs note to S3 putobject

src/ClientResolver.php, tests/EndpointDiscovery/EndpointDiscoveryMiddlewareTest.php
=> Add OS to user agent

CHANGELOG.md, src/Sdk.php
Added support in SES Client for generating V4 SMTP credentials as V2 deprecation will create a breaking change
=> Bugfix ses credential generation update

.changes/nextrelease/content-type-lookout-metrics.json, src/LookoutMetrics/LookoutMetricsClient.php, tests/LookoutMetrics/LookoutMetricsClientTest.php
=> bugfix on lookout metrics content type

.github/workflows/tests.yml, tests/Crypto/Polyfill/AesGcmTest.php
=> Stabilize tests.yml

.changes/nextrelease/bugfix-fips-endpoints.json, src/Endpoint/Partition.php, src/S3/BucketEndpointArnMiddleware.php, src/S3/EndpointRegionHelperTrait.php, src/S3Control/EndpointArnMiddleware.php, tests/Endpoint/PartitionTest.php, tests/S3/BucketEndpointArnMiddlewareTest.php, tests/S3/S3EndpointMiddlewareTest.php, tests/S3Control/EndpointArnMiddlewareTest.php
=> Bugfix fips endpoint provider

.changes/nextrelease/feature-imds-ipv6-resolution.json, src/ClientResolver.php, src/Credentials/CredentialProvider.php, src/Credentials/EcsCredentialProvider.php, src/Credentials/InstanceProfileProvider.php, src/functions.php, tests/Credentials/InstanceProfileProviderTest.php, tests/FunctionsTest.php
=> IMDS dualstack support

tests/EventBridge/EventBridgeEndpointMiddlewareTest.php
N/A
Updates Eventbridge endpoint middleware test case configuration values
=> fix: eventbridge test cases

.changes/nextrelease/bump-guzzle.json, composer.json
Description of changes:
Bumping Guzzle 6 & 7 to address [GHSA-cwmx-hcrq-mhc3](https://github.com/guzzle/guzzle/security/advisories/GHSA-cwmx-hcrq-mhc3)
=> chore: bump guzzle

.changes/nextrelease/bump-guzzle.json, composer.json
Bumping Guzzle version per https://github.com/guzzle/guzzle/security/advisories/GHSA-f2wf-25xc-69c9
=> chore: bump guzzle 

.changes/nextrelease/bump-guzzle.json, .changes/nextrelease/revert-guzzle.json, composer.json
Reverting Guzzle bump due to lack of exposure to previously mentioned security advisories.
=> chore: revert guzzle bump

src/Script/Composer/Composer.php
#2492
Addresses a conflict with autoload files/imports when script is invoked.
=> bugfix: fix function redeclaration in removeunusedservices

.changes/nextrelease/transfer-update.json, src/S3/Transfer.php
Ensures files downloaded using S3 transfer are not downloaded outside target directory.
=> enhancement: refactor path resolution

src/Middleware.php, tests/MiddlewareTest.php
Updates trace id environment variable and escapable characters.
=> bugfix: update to recursion detection

src/ClientResolver.php
=> Make two user agents identical

build/compile-json.php
=> Feature zip endpoints v2 files

phpstan.neon
Ignores data directory when running static analysis.  
=> enhancement: ignore data dir in static analysis

.changes/nextrelease/fix-sts-endpoints.json, src/Sts/StsClient.php, tests/AwsClientTest.php
#2556 
Fixes issue where default regional endpoint value is incorrectly derived.
=> bugfix: sts regional endpoints fix

.changes/nextrelease/ep-test-update.json, src/AwsClient.php, tests/EndpointV2/EndpointProviderV2Test.php
Adds endpoint protocol failure cases as well as updates client builtin resolution to allow for DualStack and FIPS options to be passed to the resolver when a custom endpoint is specified in client config.
=> enhancement: updates to endpoints tests

.changes/nextrelease/ep-discovery-patch.json, src/AwsClient.php, tests/EndpointDiscovery/EndpointDiscoveryMiddlewareTest.php
#2593 
Re-enables endpoint discovery for operations/services that require it. 
=> bugfix: re-enable endpointdiscovery

.changes/nextrelease/bugfix-crt-invalid-headers.json, src/Signature/SignatureV4.php
=> Bugfix seg fault in sig v4a

.changes/bugfix-rollback-signature-changes, src/S3/ApplyChecksumMiddleware.php, src/Signature/SignatureV4.php, tests/S3/ApplyChecksumMiddlewareTest.php
=> Bugfix rollback

.changes/nextrelease/php8-compatibility.json, src/Crypto/DecryptionTrait.php, src/Crypto/DecryptionTraitV2.php
=> Set default to empty string

.changes/nextrelease/bump-minimum-crt.json, composer.json
=> bump version

.changes/nextrelease/crt-integ.json, Makefile, behat.yml, features/crt/eventbridge.feature, features/crt/mrap.feature, tests/Integ/CrtContext.php, tests/Integ/S3Context.php
Add Integ tests for CRT features.  Both MRAP and Eventbridge Global Endpoints.
=> Enhancement: add crt integration tests

README.md
There is no related issue
Update readme link the current one goes to 404 page.
=> Update README link to access key

.changes/nextrelease/bugfix-sso-provider.json, .changes/nextrelease/enhancement-remove-deprecated-function.json, src/Credentials/CredentialProvider.php, src/Token/SsoTokenProvider.php
=> Bugfix sso provider

build/docs/theme/combined.js.latte, build/docs/theme/js/main.js
Adds missing JS functionality and missing Jquery variables.
=> update combined.js and add missing vars

build/docs/theme/@layout.latte
Adds viewport tag to api reference documentation. 
=> add viewport tag

build/docs/theme/@layout.latte, build/docs/theme/js/jquery.autocomplete.js, build/docs/theme/resources/css/style.css
Stops autocomplete tabbing behavior which selects suggestion upon a tab keypress.  Updates live region element to be visually hidden, but still displayed in the DOM.
=> enhancement: api reference search bar

build/docs/theme/@layout.latte, build/docs/theme/js/main.js
Corrects change in text injection for a visually hidden element.
=> bugfix: inject help text into hidden element

.changes/nextrelease/bugfix-crc32-flexible-checksum.json, src/S3/CalculatesChecksumTrait.php
=> bugfix flexible checksums

tests/Integ/CrtContext.php
=> Fix flaky integ test

src/data/entityresolution/2018-05-10/endpoint-rule-set-1.json, src/data/entityresolution/2018-05-10/endpoint-tests-1.json, src/data/managedblockchain-query/2023-05-04/endpoint-rule-set-1.json, src/data/managedblockchain-query/2023-05-04/endpoint-tests-1.json
Adds missing endpoints artifacts for two new services.
=> add new service endpoint artifacts

.changes/nextrelease/fix-services.json, src/data/entityresolution/2018-05-10/endpoint-rule-set-1.json, src/data/entityresolution/2018-05-10/endpoint-tests-1.json, src/data/managedblockchain-query/2023-05-04/endpoint-rule-set-1.json, src/data/managedblockchain-query/2023-05-04/endpoint-tests-1.json
=> add changelog entry for endpoint artifacts

src/CloudFront/CloudFrontClient.php
=> Typo: Update CloudFrontClient.php

.changes/nextrelease/compression-updates.json, src/RequestCompressionMiddleware.php
Adjusts request body size check to look at the content-length header, if available.
=> enhancement: update compression size logic

.changes/nextrelease/enhancement-php-version-bump.json, .github/workflows/tests.yml, build/packager.php, build/test-phar.php, composer.json, src/AwsClient.php, src/ClientResolver.php, src/CommandPool.php, src/Crypto/AesDecryptingStream.php, src/Crypto/AesEncryptingStream.php, src/Crypto/AesGcmDecryptingStream.php, src/Crypto/AesGcmEncryptingStream.php, src/HashingStream.php, src/Multipart/AbstractUploadManager.php, src/Rds/AuthTokenGenerator.php, src/S3/BatchDelete.php, src/S3/BucketEndpointArnMiddleware.php, src/S3/ObjectCopier.php, src/S3/ObjectUploader.php, src/S3/S3Client.php, src/S3/StreamWrapper.php, src/S3/Transfer.php, src/Token/TokenProvider.php, src/Waiter.php, tests/ClientSideMonitoring/ApiCallAttemptMonitoringMiddlewareTest.php, tests/Crypto/RandomByteStream.php, tests/MiddlewareTest.php
This reverts commit 84d4539e72daf415e1d421dcaa0f76e607d1fd48.  There has been an unanticipated issue in our docs build which needs to resolved before we're able to move forward with the deprecation. 
=> Revert "Deprecation below 7.2.5 (#2707)"

src/EndpointV2/Ruleset/RulesetStandardLibrary.php
=> Fixed double assignment

.changes/nextrelease/script-retries.json, src/Script/Composer/Composer.php, tests/Script/ComposerTest.php
#2786 
Adds retry mechanism to `removeUnusedServices`.  
=> enhancement: add retries to removeunusedservices

src/Credentials/InstanceProfileProvider.php
Removes two function imports, which our docs build system is rejecting.
=> remove function imports

src/Identity/S3/S3ExpressIdentityProvider.php, tests/Identity/S3Express/S3ExpressIdentityProviderTest.php
=> Identity provider refactor

src/EndpointV2/EndpointV2Middleware.php
Updates endpointv2 middleware due to test-phar failures.
=> update endpointv2 middleware

src/Api/Serializer/RestSerializer.php, tests/Integ/CrtContext.php, tests/S3/S3ClientTest.php
Fixes issue with path-style dot segment handling.  Handles paths ending with dot segment.  Updates test cases.
=> enhancement: s3 dot segment handling

.changes/nextrelease/8_3-support.json, .github/workflows/tests.yml, src/Crypto/AesDecryptingStream.php, src/Crypto/AesGcmDecryptingStream.php, src/Crypto/AesGcmEncryptingStream.php, src/PresignUrlMiddleware.php, tests/AbstractConfigurationProviderTest.php, tests/EndpointDiscovery/EndpointDiscoveryMiddlewareTest.php, tests/QueryCompatibleInputMiddlewareTest.php
=> 8.3 support

.github/workflows/docs-build.yml
Run a docs build workflow in order to catch errors in this staged before merging. 
=> chore: add docs build workflow

tests/EndpointV2/EndpointProviderV2Test.php
Updates endpoint tests for authscheme fallbacks.
=> enhancement: endpoint-test-update

src/Crypto/Polyfill/AesGcm.php, src/Crypto/Polyfill/ByteArray.php, src/Crypto/Polyfill/Gmac.php, src/Crypto/Polyfill/Key.php, src/Crypto/Polyfill/NeedsTrait.php, src/Exception/CryptoPolyfillException.php, tests/Crypto/Polyfill/AesGcmTest.php, tests/Crypto/Polyfill/ByteArrayTest.php, tests/Crypto/Polyfill/GmacTest.php, tests/Crypto/Polyfill/KeyTest.php, tests/TestServiceTrait.php
This messes with api doc generation.
=> chore: fix incorrectly used package annotations

.changes/nextrelease/fix-sso-token-refresh.json, src/Token/SsoToken.php, src/Token/SsoTokenProvider.php, src/Token/TokenProvider.php, tests/Token/SsoTokenProviderTest.php, tests/Token/TokenProviderTest.php
Fix the refresh implementation for SSO token provider.
=> fix: sso token provider refresh

.changes/nextrelease/fix-user-agent-header.json, src/AwsClient.php, src/ClientResolver.php, tests/ClientResolverTest.php
AppID is an user agent parameter that can be sourced from either client config, config file, and environment variable.
=> feat: add AppID user agent parameter

.changes/nextrelease/multi-auth-updates.json, src/Auth/AuthSchemeResolver.php, tests/Auth/AuthSchemeResolverTest.php, tests/Auth/AuthSelectionMiddlewareTest.php
closes #2944
Updates incorrect value for `noAuth`.
=> bugfix: update noauth

build/Burgomaster.php
fix for case sensitive const name replace
=> str_replace fix

.changes/nextrelease/crt-config.json, composer.json, src/AwsClient.php, src/ClientResolver.php, src/Signature/S3SignatureV4.php, src/Signature/SignatureV4.php, tests/AwsClientTest.php
Updates the CRT signing config's handling of the region option
=> enhancement: update to crt signing config

tests/Credentials/CredentialProviderTest.php, tests/Credentials/CredentialsTest.php, tests/Sts/StsClientTest.php
=> update to test account values

tests/Sts/StsClientTest.php
Updates test values caught by git secrets
=> update test values

.changes/nextrelease/s3-200-errors.json
Adds missing changelog from #2968 
=> add changelog for 8/13 release

.github/workflows/git-secrets-scan.yml
=> enhancement: update to git secrets scan

.changes/3.319.3, CHANGELOG.md
As the changelog has mixed line endings, this also normalizes them to Windows-style (CRLF)
=> fix typo in CHANGELOG.md

build/docs/.phpdoc/template/base.html.twig
Adds origin to api doc feedback url.  
=> chore: add origin param to feedback url

docs/_ext/aws/__init__.py
Adds jinja2 autoescape to doc generation.
=> chore: add jinja2 autoescape

build/docs/.phpdoc/template/layout.html.twig
Removes calls to CDN for assets that are already bundled with the docs.
=> chore: remove call to CDN

build/docs/.phpdoc/template/layout.html.twig
Removes call to CDN since resource is now bundled.
=> chore: remove fa cdn

src/Api/Serializer/RestSerializer.php, src/Api/Service.php
#3037 
Excludes S3 from rest path handling changes.
=> bugfix: s3 path handling

composer.json
fixes #3036
Add support for psr/cache 2.0, 3.0
=> Add support for psr/cache 2.0, 3.0

build/docs/.phpdoc/template/layout.html.twig
Adds analytics to the base layout.
=> Adds analytics to the base layout

.changes/nextrelease/user_agent_2_1.json
Add changelogs for user agent 2.1 implementation.
=> chore: add changelog for user_agent2.1

.changes/nextrelease/dsql-token-generator.json, src/DSQL/AuthTokenGenerator.php, src/Rds/AuthTokenGenerator.php, tests/DSQL/AuthTokenGeneratorTest.php
Adds new `AuthTokenGenerator` class which generates connection tokens for DSQL database clusters.
=> feat: DSQL auth token generator

src/S3/S3Client.php
Corrects application of S3 `response_checksum_validation` config value.
=> chore: update checksum-validation-config'

.github/workflows/closed-issue-message.yml, .github/workflows/docs-build.yml, .github/workflows/git-secrets-scan.yml, .github/workflows/issue-regression-labeler.yml, .github/workflows/stale_issues.yml, .github/workflows/tests.yml
N/A
I split the change into three commits for easier review.
- chore: fix GHA workflow 'Close stale issues'
The inputs `exempt-issue-labels` and `exempt-pr-labels` of the action `aws-actions/stale-issue-cleanup` were misspelt and missing a plural 's'.
- chore: fix GHA workflow 'Build API documentation'
The entry `composer-options` is not configured for the matrix definition and is, therefore, not available at this point.
- chore: consistently format GHA workflow definition files
This prevents the YAML linting from screaming at us for formatting issues of the GHA YAML files. It was mostly inconsistent indentation and excessive whitespace.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> chore: fix GHA workflow files

.changes/nextrelease/remove-guzzlev6-support.json, src/Handler/Guzzle/GuzzleHandler.php, src/Handler/GuzzleV6/GuzzleHandler.php, src/functions.php, tests/Credentials/EcsCredentialProviderTest.php, tests/FunctionsTest.php, tests/Handler/Guzzle/HandlerTest.php, tests/Handler/GuzzleV6/HandlerTest.php, tests/Integ/GuzzleStreamHandlerTest.php
n/a
Remove code for unsupported version v6 of Guzzle.
This is based on #2923.
=> feat: remove code for unsupported version v6 of Guzzle

.changes/nextrelease/update-rest-path-handling.json, src/Api/Serializer/RestSerializer.php
Fixes #3099.
Updates path handling for REST services.
=> bugfix: updates to path handling for rest services

.changes/nextrelease/changelogbuilder-update.json, build/changelog/ChangelogBuilder.php, tests/Build/Changelog/ChangelogBuilderTest.php, tests/Build/Changelog/resources/invalid/.changes/nextrelease/test.json, tests/Build/Changelog/resources/invalid/.changes/nextrelease/test2.json, tests/Build/Changelog/resources/invalid/CHANGELOG.md
Validates tag input for `ChangelogBuilder`
=> chore: update ChangelogBuilder

features/smoke/inspector.feature
Removes handwritten inspector smoke test
=> chore: remove inspector smoke test

features/smoke/inspector.feature
Removes remaining inspector smoke tests.
=> remove inspector smoke tests

.changes/nextrelease/geo-clients.fix.json, src/Api/Serializer/RestSerializer.php
Temporary fix for issue in resolving endpoints for GeoPlaces, GeoMaps and GeoRoutes clients.
=> bugfix: geo-clients

features/smoke/geoplaces.feature
Adds geoplaces smoke test for extra coverage for Amazon Location service endpoint resolution.
=> chore: add geoplaces smoke test

features/smoke/cloudwatch.feature, tests/Integ/SmokeContext.php
Add smoke test to cloudwatch using the query compatible mode enabled.
=> chore: add smoke test for cloudwatch

.changes/nextrelease/query-compat-updates.json, src/Api/ErrorParser/AbstractErrorParser.php, src/Api/ErrorParser/JsonRpcErrorParser.php, tests/Api/Parser/ComplianceTest.php, tests/Api/test_cases/protocols/output/json_1_0-query-compatible.json
Adds support for extracting error codes from within an error shape's nested `error` property.  Updates query compatible protocol tests.
=> enhancement: update error parsing and protocol tests

tests/S3/S3ClientTest.php
Adds test to enforce checksum calculation (not happening again) on retries
=> chore: add checksum-reuse-test

.changes/nextrelease/bugfix-rest-uri-resolution.json, src/Api/Serializer/RestSerializer.php, src/S3/BucketEndpointMiddleware.php, src/S3/S3Client.php, tests/Api/Serializer/RestJsonSerializerTest.php, tests/Api/Serializer/RestXmlSerializerTest.php, tests/S3/BucketEndpointMiddlewareTest.php, tests/S3/S3ClientTest.php, tests/S3/StreamWrapperPathStyleTest.php
Standardizes endpoint URI resolution logic in RestSerializer::buildEndpoint() to address multiple path resolution issues.
=> bugfix: standardize rest protocol URI resolution

.changes/nextrelease/update-deserialization.json, src/Api/ErrorParser/JsonParserTrait.php, src/Api/ErrorParser/RestJsonErrorParser.php, src/Api/Parser/AbstractRestParser.php, src/Api/Parser/JsonParser.php, src/Api/Parser/MetadataParserTrait.php, src/Api/Parser/QueryParser.php, src/Api/Parser/RestJsonParser.php, src/Api/Parser/XmlParser.php, tests/Api/Parser/ComplianceTest.php, tests/Api/Parser/ParserTestServiceTrait.php, tests/Api/Parser/RestJsonParserTest.php, tests/Api/test_cases/protocols/output/ec2.json, tests/Api/test_cases/protocols/output/json.json, tests/Api/test_cases/protocols/output/json_1_0.json, tests/Api/test_cases/protocols/output/legacy/ec2.json, tests/Api/test_cases/protocols/output/legacy/json.json, tests/Api/test_cases/protocols/output/legacy/query.json, tests/Api/test_cases/protocols/output/legacy/rest-json.json, tests/Api/test_cases/protocols/output/legacy/rest-xml.json, tests/Api/test_cases/protocols/output/query.json, tests/Api/test_cases/protocols/output/rest-json.json, tests/Api/test_cases/protocols/output/rest-xml.json, tests/WrappedHttpHandlerTest.php
Updates to deserialization for all AWS protocols.
=> bugfix: aws protocol deserialization updates

.changes/nextrelease/sts-updates.json, src/Sts/RegionalEndpoints/ConfigurationProvider.php, tests/AwsClientTest.php, tests/Credentials/CredentialProviderTest.php, tests/EndpointV2/EndpointV2MiddlewareTest.php, tests/Sts/RegionalEndpoints/ConfigurationProviderTest.php, tests/UserAgentMiddlewareTest.php
Switches default STS endpoint configuration to `regional`.
=> enhancement: change sts default endpoint to regional

.github/workflows/closed-issue-message.yml, .github/workflows/docs-build.yml, .github/workflows/git-secrets-scan.yml, .github/workflows/issue-regression-labeler.yml, .github/workflows/stale_issues.yml, .github/workflows/tests.yml
Updates to permissions, repository scope and formatting
=> chore: update workflows

.changes/nextrelease/feat-manual-auth-scheme.json, src/Auth/AuthSchemeResolverInterface.php, src/Auth/AuthSelectionMiddleware.php, src/AwsClient.php, src/ClientResolver.php, tests/Auth/AuthSelectionMiddlewareTest.php, tests/ClientResolverTest.php
- Add support to configure manual schemes based on user's preference.
=> feat: manual auth schemes configuration
